# -*- coding: utf-8 -*-
"""Recipe library, part 1: Breakfast (B) and Lunch/Dinner (L).
Every ingredient is (key, grams, household_measure). Macros are COMPUTED from grams.
All recipes are gluten-free and vegetarian unless they appear in the separate M section."""

RECIPES_1 = [
dict(id="B-01", cat="Breakfast", name="Chocolate Peanut Butter Protein Overnight Oats",
 servings=1, prep=5, cook=0,
 ing=[("oats_gf_dry",60,"3/4 cup dry"),("milk_2",200,"3/4 cup + 1 tbsp"),("whey_isolate",30,"1 scoop"),
      ("pb_powder",12,"2 tbsp"),("cocoa_powder",5,"1 tbsp"),("chia",12,"1 tbsp"),("banana",60,"1/2 medium")],
 steps=["Stir the oats, chia, cocoa and powdered peanut butter together in a jar so the powders do not clump.",
        "Add the milk and protein powder. Stir hard for 20 seconds until smooth.",
        "Slice the banana on top, seal, and refrigerate at least 6 hours or overnight.",
        "Eat cold, or microwave 45 seconds if you want it warm."],
 storage="Airtight in the fridge up to 4 days. Do not freeze.",
 prep_notes="Make 4 jars at once. Add banana the morning you eat it so it does not brown.",
 subs=["No whey: use 30 g casein and add 30 ml extra milk.",
       "No powdered PB: 16 g real peanut butter (adds ~60 kcal, 8 g fat).",
       "Dairy-free: unsweetened soy milk keeps protein closest."],
 variations=["Swap cocoa for 2 tsp cinnamon and use apple instead of banana."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY"]),

dict(id="B-02", cat="Breakfast", name="Cottage Cheese Berry Crunch Bowl",
 servings=1, prep=4, cook=0,
 ing=[("cottage_cheese_2",226,"1 cup"),("mixed_berries_frozen",100,"3/4 cup"),("almonds",15,"~12 almonds"),("honey",10,"1.5 tsp")],
 steps=["Thaw the berries in the microwave 40 seconds so they release juice.",
        "Spoon cottage cheese into a bowl, top with berries and their juice.",
        "Chop the almonds roughly, scatter on top, drizzle honey."],
 storage="Assemble fresh. Cottage cheese keeps per its own date once opened.",
 prep_notes="Zero cook. Good first thing on a work morning.",
 subs=["Cottage cheese texture is a problem for some people: blend it 20 seconds and it becomes a thick cream.",
       "Skyr or nonfat Greek yogurt swap 1:1."],
 variations=["Savory version: skip honey and berries, use tomato, cucumber, olive oil, black pepper."],
 manual_tags=["QUICK","BUDGET FRIENDLY"]),

dict(id="B-03", cat="Breakfast", name="Big Veggie Scramble",
 servings=1, prep=5, cook=8,
 ing=[("egg_whole",100,"2 large eggs"),("egg_white",132,"4 large whites"),("spinach",60,"2 packed cups"),
      ("mushrooms",60,"~5 mushrooms"),("bell_pepper",60,"1/2 pepper"),("olive_oil",7,"1/2 tbsp"),("cheddar",20,"~2 tbsp shredded")],
 steps=["Heat the oil in a nonstick pan over medium. Cook mushrooms and pepper 4 minutes until the water cooks off.",
        "Add spinach, stir 30 seconds until it collapses.",
        "Pour in the whisked eggs and whites. Stir slowly with a spatula, pulling from the edges.",
        "Kill the heat while it still looks slightly wet, fold in the cheddar, and let residual heat finish it."],
 storage="Best fresh. Cooked eggs keep 3 days refrigerated.",
 prep_notes="Pre-chop the vegetables for the week in one container. Cuts this to 6 minutes.",
 subs=["No whites in a carton: 2 more whole eggs (adds ~140 kcal, 19 g fat)."],
 variations=["Add 60 g cooked potato for a training-day carb bump."],
 manual_tags=["QUICK"]),

dict(id="B-04", cat="Breakfast", name="Blueberry Protein Parfait",
 servings=1, prep=4, cook=0,
 ing=[("greek_yogurt_nonfat",200,"~7 oz"),("whey_isolate",15,"1/2 scoop"),("blueberries",80,"1/2 cup"),
      ("oats_gf_dry",20,"1/4 cup dry"),("pb_powder",10,"1.5 tbsp")],
 steps=["Whisk the protein powder and powdered peanut butter into the yogurt with a splash of water until smooth.",
        "Layer half the yogurt, half the oats, half the berries. Repeat.",
        "Eat immediately, or refrigerate overnight so the oats soften."],
 storage="Up to 3 days sealed.",
 prep_notes="Whisking dry protein into thick yogurt clumps unless you add 20 to 30 ml water first.",
 subs=["Raw oats bother some stomachs: toast them 5 minutes in a dry pan first."],
 variations=["Use frozen cherries and cocoa for a black forest version."],
 manual_tags=["QUICK","MEAL PREP"]),

dict(id="B-05", cat="Breakfast", name="Gluten-Free Protein Pancakes",
 servings=1, prep=5, cook=8,
 ing=[("gf_oat_flour",50,"1/2 cup"),("whey_isolate",30,"1 scoop"),("egg_whole",50,"1 large egg"),
      ("egg_white",66,"2 large whites"),("milk_2",100,"1/3 cup + 1 tbsp"),("baking_powder",3,"3/4 tsp"),("cinnamon",1,"1/2 tsp")],
 steps=["Blend everything for 20 seconds, or whisk hard. The batter should pour thick, not run.",
        "Rest the batter 5 minutes. This matters with oat flour; it hydrates and stops the pancakes tasting gritty.",
        "Cook on a nonstick pan over medium-low, roughly 2 minutes per side. Protein pancakes burn faster than normal ones, so keep the heat lower than you think.",
        "Stack and top with berries, sugar-free syrup, or powdered peanut butter thinned with water."],
 storage="Cooked pancakes freeze well, 2 months, separated by parchment. Reheat in a toaster.",
 prep_notes="Triple the batch on Sunday, freeze flat.",
 subs=["Blend GF rolled oats to make your own oat flour, cheaper than buying it.",
       "Casein makes them fluffier than whey but needs ~40 ml more milk."],
 variations=["Add 15 g mini chocolate chips (+70 kcal)."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY"]),

dict(id="B-06", cat="Breakfast", name="Savory Tofu Scramble Hash",
 servings=1, prep=6, cook=12,
 ing=[("tofu_firm",200,"~1/2 block"),("nutritional_yeast",8,"2 tbsp"),("spinach",60,"2 packed cups"),
      ("onion",40,"1/4 onion"),("bell_pepper",60,"1/2 pepper"),("olive_oil",7,"1/2 tbsp"),("potato",150,"1 small, pre-cooked")],
 steps=["Press the tofu 10 minutes under something heavy, then crumble it with your hands into egg-sized curds.",
        "Fry onion, pepper and diced cooked potato in the oil over medium-high for 5 minutes.",
        "Add the tofu and nutritional yeast plus a pinch of turmeric if you have it. Cook 5 minutes without stirring much so it browns.",
        "Fold in spinach at the end."],
 storage="4 days refrigerated. Reheats better than egg scramble.",
 prep_notes="Batch the potato and vegetables Sunday; this becomes an 8 minute meal.",
 subs=["Nutritional yeast is the savory backbone here and is fortified with B12, which matters on a vegetarian diet. Do not skip it."],
 variations=["Wrap it in a GF tortilla with salsa."],
 manual_tags=["VEGAN","MEAL PREP","BUDGET FRIENDLY"]),

dict(id="B-07", cat="Breakfast", name="Peanut Butter Banana French Toast",
 servings=1, prep=5, cook=8,
 ing=[("gf_bread",80,"2 thick slices"),("egg_whole",100,"2 large eggs"),("milk_2",60,"1/4 cup"),
      ("peanut_butter",32,"2 tbsp"),("banana",60,"1/2 medium"),("cinnamon",1,"1/2 tsp")],
 steps=["Whisk eggs, milk and cinnamon in a shallow bowl.",
        "Soak each slice 20 seconds per side. Gluten-free bread falls apart if you soak it longer.",
        "Cook on a nonstick pan over medium 3 minutes per side.",
        "Spread with peanut butter, top with sliced banana, fold into a sandwich."],
 storage="Eat fresh.",
 prep_notes="",
 subs=["Powdered peanut butter mixed with water drops this by about 130 kcal and 15 g fat."],
 variations=["Add 20 g whey to the egg mixture for a higher-protein soak."],
 manual_tags=["HIGH CALORIE"]),

dict(id="B-08", cat="Breakfast", name="Berry Chia Protein Pudding",
 servings=1, prep=4, cook=0,
 ing=[("chia",30,"2.5 tbsp"),("milk_2",200,"3/4 cup + 1 tbsp"),("whey_isolate",30,"1 scoop"),("mixed_berries_frozen",100,"3/4 cup")],
 steps=["Whisk the protein into the milk first, until there are no lumps.",
        "Add chia seeds, whisk again, wait 5 minutes, whisk a third time. That third whisk is what stops it setting in one lump.",
        "Refrigerate at least 4 hours.",
        "Top with thawed berries."],
 storage="5 days refrigerated.",
 prep_notes="Make 4 jars at once, they hold texture well.",
 subs=["Casein sets thicker than whey here."],
 variations=["Cocoa and a chopped date turns it into a dessert."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="B-09", cat="Breakfast", name="Loaded Breakfast Burrito",
 servings=1, prep=5, cook=8,
 ing=[("gf_wrap",60,"1 large GF tortilla"),("egg_whole",100,"2 large eggs"),("egg_white",66,"2 large whites"),
      ("black_beans",90,"1/2 cup"),("cheddar",25,"1/4 cup shredded"),("salsa",45,"3 tbsp")],
 steps=["Scramble the eggs and whites soft, about 2 minutes.",
        "Warm the beans and the tortilla, 30 seconds each in the microwave. A cold GF tortilla cracks when you roll it.",
        "Load eggs, beans, cheese and salsa down the center, fold the sides in, roll tight.",
        "Optional: sear the seam side down in a dry pan 90 seconds to seal it."],
 storage="Wrap in foil, refrigerate 3 days or freeze 1 month. Reheat from frozen 2 to 3 minutes in the microwave.",
 prep_notes="Make 5 on Sunday and freeze. This is the single best breakfast for a 5 a.m. work start.",
 subs=["Corn tortillas instead of a large GF wrap cuts sodium substantially."],
 variations=["Add 60 g cooked potato for a heavier version."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY"]),

dict(id="B-10", cat="Breakfast", name="Apple Cinnamon Protein Oats",
 servings=1, prep=3, cook=5,
 ing=[("oats_gf_dry",50,"2/3 cup dry"),("milk_skim",200,"3/4 cup + 1 tbsp"),("whey_isolate",25,"3/4 scoop"),
      ("apple",100,"1 small, diced"),("cinnamon",2,"1 tsp"),("walnuts",12,"~5 halves")],
 steps=["Simmer oats, milk, diced apple and cinnamon 4 to 5 minutes, stirring.",
        "Take it off the heat and let it cool for one minute.",
        "Stir the protein in off the heat. Adding whey to boiling oats makes it grainy.",
        "Top with chopped walnuts."],
 storage="3 days refrigerated, add a splash of milk when reheating.",
 prep_notes="",
 subs=["Pear works identically."],
 variations=["Use casein instead of whey and it turns creamy rather than grainy even when hot."],
 manual_tags=["BUDGET FRIENDLY"]),

dict(id="B-11", cat="Breakfast", name="Skyr Smoothie Bowl",
 servings=1, prep=5, cook=0,
 ing=[("skyr",200,"~7 oz"),("mixed_berries_frozen",120,"1 cup"),("banana",60,"1/2 medium"),
      ("whey_isolate",20,"2/3 scoop"),("hemp_hearts",10,"1 tbsp"),("pb_powder",10,"1.5 tbsp")],
 steps=["Blend skyr, frozen berries, banana and protein with as little liquid as possible. Use the tamper, not more water, or it turns into a drink.",
        "Pour into a bowl.",
        "Top with hemp hearts and a powdered peanut butter drizzle made with 1 tbsp water."],
 storage="Eat immediately.",
 prep_notes="Freeze the banana in chunks so you never need ice.",
 subs=["Nonfat Greek yogurt swaps 1:1."],
 variations=["Add 20 g GF granola for crunch and 90 kcal."],
 manual_tags=["QUICK","HIGH MICRONUTRIENT DENSITY"]),

dict(id="B-12", cat="Breakfast", name="Sweet Potato and Egg Hash",
 servings=1, prep=8, cook=15,
 ing=[("sweet_potato",250,"1 large"),("egg_whole",150,"3 large eggs"),("spinach",60,"2 packed cups"),
      ("olive_oil",10,"2 tsp"),("onion",50,"1/3 onion")],
 steps=["Dice the sweet potato small, about 1 cm. Microwave 4 minutes first; it halves the pan time.",
        "Fry potato and onion in the oil over medium-high 8 minutes until edges brown.",
        "Push to one side, crack the eggs into the space, cover 3 minutes for runny yolks.",
        "Add spinach in the last 30 seconds."],
 storage="Hash keeps 4 days without the eggs. Cook the eggs fresh.",
 prep_notes="",
 subs=["Regular potato works, slightly lower potassium and vitamin A."],
 variations=["Add 80 g black beans for fiber and protein."],
 manual_tags=["HIGH MICRONUTRIENT DENSITY"]),

dict(id="B-13", cat="Breakfast", name="Cottage Cheese Protein Waffles",
 servings=1, prep=5, cook=10,
 ing=[("cottage_cheese_2",150,"2/3 cup"),("gf_oat_flour",50,"1/2 cup"),("egg_whole",100,"2 large eggs"),
      ("whey_isolate",15,"1/2 scoop"),("baking_powder",3,"3/4 tsp")],
 steps=["Blend everything smooth, about 30 seconds. Blending is required here, otherwise the cottage cheese stays lumpy.",
        "Rest the batter 5 minutes.",
        "Cook in a preheated waffle iron until steam stops, roughly 4 minutes.",
        "Do not open the iron early or it tears."],
 storage="Freeze 2 months. Reheat straight from frozen in a toaster.",
 prep_notes="Double batch, freeze. Toaster waffles with 30 g of protein each.",
 subs=["No waffle iron: cook as pancakes on medium-low."],
 variations=["Savory version: skip protein powder, add nutritional yeast and black pepper."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY"]),

dict(id="B-14", cat="Breakfast", name="Mocha Casein Overnight Oats",
 servings=1, prep=5, cook=0,
 ing=[("oats_gf_dry",60,"3/4 cup dry"),("cold_brew",150,"2/3 cup"),("milk_2",100,"1/3 cup + 1 tbsp"),
      ("casein_powder",30,"1 scoop"),("cocoa_powder",5,"1 tbsp"),("chia",10,"1 tbsp")],
 steps=["Mix oats, chia and cocoa dry.",
        "Whisk casein into the cold brew and milk separately, then pour over. Casein thickens fast, so mixing it into the liquid first prevents lumps.",
        "Refrigerate overnight. It will set almost like a mousse."],
 storage="4 days refrigerated.",
 prep_notes="",
 subs=["Whey works but stays runnier.",
       "Decaf cold brew if you are eating this early and training late."],
 variations=["Add 16 g almond butter for a richer, higher-calorie version."],
 manual_tags=["MEAL PREP"]),

# ---------------------------- LUNCH / DINNER ----------------------------

dict(id="L-01", cat="Lunch/Dinner", name="Chickpea Pasta with Marinara and Whipped Ricotta",
 servings=1, prep=5, cook=12,
 ing=[("chickpea_pasta_dry",85,"~3 oz dry"),("marinara",150,"2/3 cup"),("ricotta_ps",80,"1/3 cup"),
      ("spinach",60,"2 packed cups"),("parmesan",10,"2 tbsp"),("olive_oil",7,"1/2 tbsp")],
 steps=["Boil the chickpea pasta in heavily salted water. Check it two minutes before the box says; it goes from firm to mush quickly.",
        "Warm the marinara with the olive oil, wilt the spinach into it.",
        "Whip the ricotta with a fork and a pinch of salt for 30 seconds until it loosens.",
        "Toss pasta with sauce, spoon ricotta on top, finish with parmesan."],
 storage="4 days refrigerated. Sauce and pasta separately if you can.",
 prep_notes="Chickpea pasta is the single easiest swap that raises protein and fiber in a normal meal.",
 subs=["Red lentil pasta: slightly more protein, softer texture.",
       "Cottage cheese blended smooth replaces ricotta and adds protein."],
 variations=["Add 100 g white beans for +8 g protein and +7 g fiber."],
 manual_tags=["HIGH FIBER","BUDGET FRIENDLY"]),

dict(id="L-02", cat="Lunch/Dinner", name="Black Bean Burrito Bowl",
 servings=1, prep=6, cook=5,
 ing=[("black_beans",172,"1 cup"),("rice_brown_cooked",200,"~1 cup"),("salsa",60,"1/4 cup"),
      ("avocado",50,"1/4 large"),("cheddar",25,"1/4 cup shredded"),("sweet_corn",60,"1/3 cup")],
 steps=["Warm the beans with a pinch of cumin and a squeeze of lime.",
        "Layer rice, beans, corn.",
        "Top with salsa, cheese and sliced avocado."],
 storage="4 days without the avocado. Slice avocado fresh.",
 prep_notes="Cook rice and beans in bulk Sunday. This is a 3 minute assembly on a work night.",
 subs=["White rice if you are eating this close to training; it digests faster."],
 variations=["Add 100 g crumbled baked tofu for +17 g protein."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY","HIGH FIBER"]),

dict(id="L-03", cat="Lunch/Dinner", name="Crispy Teriyaki Tofu Rice Bowl",
 servings=1, prep=10, cook=15,
 ing=[("tofu_extrafirm",200,"1/2 block"),("rice_white_cooked",180,"~1 cup"),("broccoli_cooked",120,"1 cup"),
      ("soy_sauce_gf",15,"1 tbsp tamari"),("honey",10,"1.5 tsp"),("olive_oil",7,"1/2 tbsp")],
 steps=["Press the tofu 15 minutes. This is the difference between crispy and rubbery, and it is not optional.",
        "Cube it, toss with 1 tsp cornstarch if you have it, and pan-fry in the oil over medium-high 8 minutes, turning every 2 minutes.",
        "Mix tamari and honey, pour over the tofu off the heat, and let it reduce onto the cubes for 30 seconds.",
        "Serve over rice with steamed broccoli."],
 storage="4 days. Tofu loses crispness but tastes fine.",
 prep_notes="Bake a full block at 400F for 25 minutes instead of pan-frying if you want it hands-off.",
 subs=["Tempeh instead of tofu raises protein and fiber."],
 variations=["Add sriracha and a spoon of peanut butter to the sauce."],
 manual_tags=["VEGAN","MEAL PREP","POST-WORKOUT FRIENDLY"]),

dict(id="L-04", cat="Lunch/Dinner", name="High-Protein Margherita Pizza",
 servings=1, prep=5, cook=10,
 ing=[("gf_wrap",60,"1 large GF tortilla"),("marinara",60,"1/4 cup"),("mozzarella_ps",70,"~2/3 cup shredded"),
      ("cherry_tomatoes",50,"5 tomatoes"),("parmesan",8,"1.5 tbsp")],
 steps=["Preheat the oven to 425F with a sheet pan already inside. A hot pan is what makes a tortilla crust crisp instead of floppy.",
        "Spread sauce thin, leaving a border. Too much sauce is the main reason these go soggy.",
        "Add mozzarella, halved tomatoes and parmesan.",
        "Bake directly on the hot pan 8 to 10 minutes until the edges are brown and brittle."],
 storage="Eat fresh.",
 prep_notes="",
 subs=["Two corn tortillas stacked with a smear of sauce between them make a sturdier crust."],
 variations=["Protein crust: mix 100 g nonfat Greek yogurt with 100 g GF self-rising flour, knead, roll thin."],
 manual_tags=["QUICK"]),

dict(id="L-05", cat="Lunch/Dinner", name="Red Lentil Pasta with Garlic Spinach and Feta",
 servings=1, prep=5, cook=12,
 ing=[("lentil_pasta_dry",85,"~3 oz dry"),("spinach",80,"3 packed cups"),("feta",40,"~1/4 cup crumbled"),
      ("olive_oil",10,"2 tsp"),("garlic",8,"2 cloves"),("cherry_tomatoes",80,"8 tomatoes")],
 steps=["Boil the pasta, reserving 60 ml of the starchy water before draining.",
        "Meanwhile fry sliced garlic in the oil over low heat 90 seconds. Do not brown it or the whole dish turns bitter.",
        "Add halved tomatoes, cook 3 minutes until they burst, then wilt the spinach in.",
        "Toss the pasta in with the reserved water, kill the heat, crumble feta over the top."],
 storage="3 days refrigerated.",
 prep_notes="",
 subs=["Cottage cheese instead of feta: more protein, far less sodium."],
 variations=["Add a tin of drained white beans for a heavier meal."],
 manual_tags=["HIGH FIBER"]),

dict(id="L-06", cat="Lunch/Dinner", name="Tempeh Pepper Stir-Fry",
 servings=1, prep=8, cook=12,
 ing=[("tempeh",150,"~5 oz"),("bell_pepper",100,"1 pepper"),("onion",60,"1/2 onion"),
      ("rice_white_cooked",180,"~1 cup"),("soy_sauce_gf",15,"1 tbsp tamari"),("olive_oil",7,"1/2 tbsp")],
 steps=["Steam the cubed tempeh 8 minutes first. Tempeh has a bitter edge raw, and steaming removes it.",
        "Get the pan very hot. Sear tempeh in the oil 4 minutes until browned on two sides.",
        "Add pepper and onion, stir-fry 3 minutes; they should stay crisp.",
        "Add tamari off the heat and toss. Serve over rice."],
 storage="4 days refrigerated. Reheats well.",
 prep_notes="",
 subs=["Extra-firm tofu if tempeh's texture is too dense."],
 variations=["Add 1 tbsp peanut butter and sriracha to the sauce."],
 manual_tags=["VEGAN","MEAL PREP","HIGH FIBER"]),

dict(id="L-07", cat="Lunch/Dinner", name="Loaded Baked Potato with Cottage Cheese and Broccoli",
 servings=1, prep=3, cook=12,
 ing=[("potato",350,"1 very large"),("cottage_cheese_2",150,"2/3 cup"),("broccoli_cooked",120,"1 cup"),("cheddar",20,"2 tbsp shredded")],
 steps=["Pierce the potato, microwave 8 to 10 minutes, turning once.",
        "Split it, fluff the inside with a fork, press the sides to open it up.",
        "Load with cottage cheese, steamed broccoli and cheddar. The residual heat melts everything.",
        "Black pepper and hot sauce finish it."],
 storage="4 days. Bake potatoes in bulk.",
 prep_notes="This is the cheapest high-satiety, high-potassium meal in the catalog.",
 subs=["Sweet potato for more vitamin A and fiber."],
 variations=["Add 100 g black beans and salsa for a Tex-Mex version."],
 manual_tags=["BUDGET FRIENDLY","HIGH SATIETY"]),

dict(id="L-08", cat="Lunch/Dinner", name="Chickpea Coconut Curry",
 servings=2, prep=8, cook=18,
 ing=[("chickpeas",400,"2 cups cooked"),("coconut_milk_light",240,"1 cup"),("curry_paste",50,"3 tbsp"),
      ("spinach",120,"4 packed cups"),("rice_white_cooked",360,"2 cups"),("onion",80,"2/3 onion"),("olive_oil",10,"2 tsp")],
 steps=["Fry the onion in oil 4 minutes, then the curry paste for 60 seconds until it smells strong. Frying the paste, not just stirring it into liquid, is where the flavor comes from.",
        "Add coconut milk and chickpeas, simmer 12 minutes uncovered so it thickens.",
        "Wilt spinach in at the end.",
        "Serve over rice."],
 storage="4 days refrigerated, freezes 2 months without the rice.",
 prep_notes="Doubles cleanly to 4 servings in one pot.",
 subs=["Add 200 g cubed firm tofu for a large protein bump.",
       "Full-fat coconut milk adds roughly 150 kcal per serving."],
 variations=["Red lentils instead of chickpeas make it thicker and cheaper."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","HIGH FIBER","VEGAN"]),

dict(id="L-09", cat="Lunch/Dinner", name="Greek Quinoa Power Bowl",
 servings=1, prep=10, cook=0,
 ing=[("quinoa_cooked",200,"~1 cup"),("chickpeas",120,"2/3 cup"),("cucumber",80,"1/3 cucumber"),
      ("cherry_tomatoes",80,"8 tomatoes"),("feta",40,"1/4 cup crumbled"),("olive_oil",10,"2 tsp"),("lemon_juice",10,"2 tsp")],
 steps=["Whisk olive oil, lemon juice, oregano, salt and pepper.",
        "Combine cooled quinoa, chickpeas, diced cucumber and halved tomatoes.",
        "Dress, toss, crumble feta over the top.",
        "Better after 30 minutes in the fridge."],
 storage="4 days and it improves on day 2.",
 prep_notes="Make a 4-serving batch. One of the few salads that does not go limp.",
 subs=["Cottage cheese instead of feta cuts sodium and raises protein."],
 variations=["Add 100 g grilled chicken from the M section if you want it heavier."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="L-10", cat="Lunch/Dinner", name="Black Bean and Sweet Potato Tacos",
 servings=1, prep=8, cook=15,
 ing=[("corn_tortilla",78,"3 small tortillas"),("black_beans",150,"3/4 cup"),("sweet_potato",150,"1 small"),
      ("salsa",45,"3 tbsp"),("avocado",40,"1/5 large"),("cheddar",20,"2 tbsp shredded")],
 steps=["Dice the sweet potato small, toss with oil, cumin and smoked paprika, roast at 425F for 20 minutes or air-fry 12.",
        "Warm the beans with a squeeze of lime.",
        "Char the tortillas directly over a burner or in a dry pan, 20 seconds a side.",
        "Fill with sweet potato, beans, salsa, avocado and cheese."],
 storage="Components keep 4 days separately.",
 prep_notes="",
 subs=["Canned beans, drained and rinsed, cut this to 15 minutes total."],
 variations=["Add 100 g seasoned crumbled tempeh."],
 manual_tags=["HIGH FIBER","BUDGET FRIENDLY"]),

dict(id="L-11", cat="Lunch/Dinner", name="Peanut Tofu Noodle Bowl",
 servings=1, prep=8, cook=12,
 ing=[("gf_pasta_dry",70,"~2.5 oz rice noodles"),("tofu_firm",150,"~1/3 block"),("peanut_butter",20,"1 heaped tbsp"),
      ("soy_sauce_gf",15,"1 tbsp tamari"),("coleslaw_mix",80,"1.5 cups"),("sriracha",8,"1.5 tsp"),("lemon_juice",10,"2 tsp")],
 steps=["Cook the rice noodles, then rinse under cold water. Rinsing is what stops them gluing together.",
        "Pan-fry cubed pressed tofu until golden, about 8 minutes.",
        "Whisk peanut butter, tamari, sriracha, lime or lemon juice and 2 tbsp hot water into a pourable sauce.",
        "Toss noodles, tofu, raw slaw and sauce together."],
 storage="3 days. Eat cold or at room temperature.",
 prep_notes="Good cold, which makes it a real lunchbox option for a job site.",
 subs=["Powdered peanut butter reconstituted saves about 90 kcal."],
 variations=["Add edamame for +11 g protein."],
 manual_tags=["VEGAN","MEAL PREP"]),

dict(id="L-12", cat="Lunch/Dinner", name="White Bean, Kale and Potato Soup",
 servings=2, prep=10, cook=25,
 ing=[("kidney_beans",400,"2 cups cooked white or kidney beans"),("kale",160,"5 packed cups"),("carrot",160,"2 carrots"),
      ("onion",120,"1 onion"),("olive_oil",20,"4 tsp"),("potato",300,"2 small"),("garlic",10,"3 cloves")],
 steps=["Sweat onion, carrot and garlic in the oil for 6 minutes.",
        "Add diced potato and 900 ml water or stock. Simmer 15 minutes.",
        "Mash about a third of the beans before adding them; that is what thickens the broth without cream.",
        "Add all beans and chopped kale, simmer 5 more minutes. Salt aggressively at the end."],
 storage="5 days refrigerated, 3 months frozen.",
 prep_notes="Best freezer meal in the catalog. Portion into containers hot, cool, then freeze.",
 subs=["Spinach instead of kale, added at the very end."],
 variations=["Stir 30 g grated parmesan into each bowl."],
 manual_tags=["FREEZER FRIENDLY","BUDGET FRIENDLY","HIGH FIBER","VEGAN"]),

dict(id="L-13", cat="Lunch/Dinner", name="Protein Mac and Cheese",
 servings=1, prep=5, cook=12,
 ing=[("chickpea_pasta_dry",85,"~3 oz dry"),("cottage_cheese_2",150,"2/3 cup"),("cheddar",30,"1/3 cup shredded"),
      ("milk_skim",60,"1/4 cup"),("nutritional_yeast",8,"2 tbsp")],
 steps=["Blend cottage cheese, milk and nutritional yeast completely smooth. Any lumps left here will look curdled in the final sauce.",
        "Cook and drain the pasta.",
        "Return pasta to the warm pot off the heat, pour the blended sauce in, add cheddar, stir until it melts.",
        "Never boil the sauce. Cottage cheese splits above a simmer."],
 storage="3 days. Add a splash of milk when reheating.",
 prep_notes="",
 subs=["Regular GF pasta drops protein by about 12 g and fiber by 8 g."],
 variations=["Stir in 100 g steamed broccoli."],
 manual_tags=["HIGH SATIETY"]),

dict(id="L-14", cat="Lunch/Dinner", name="Egg Fried Rice",
 servings=1, prep=5, cook=10,
 ing=[("rice_white_cooked",250,"1.5 cups, day-old"),("egg_whole",150,"3 large eggs"),("peas_frozen",80,"1/2 cup"),
      ("carrot",60,"1 small"),("soy_sauce_gf",15,"1 tbsp tamari"),("olive_oil",10,"2 tsp")],
 steps=["Use cold, day-old rice. Fresh rice steams instead of frying and turns to paste.",
        "Scramble the eggs in half the oil, break them up, remove them from the pan.",
        "Get the pan hot, add remaining oil, fry rice, carrot and peas 4 minutes without stirring constantly.",
        "Return the egg, add tamari, toss 30 seconds."],
 storage="3 days. Reheat hot enough to steam through, for food safety with cooked rice.",
 prep_notes="Cooked rice must be cooled fast and refrigerated within an hour. Bacillus cereus is the one real food-safety risk with batch-cooked rice.",
 subs=["Add 150 g cubed tofu for +25 g protein."],
 variations=["Kimchi fried rice version with 60 g kimchi."],
 manual_tags=["QUICK","BUDGET FRIENDLY","POST-WORKOUT FRIENDLY"]),
]
