# -*- coding: utf-8 -*-
"""Recipe library, part 5.
Built from Jaron's own recipe collection (family printouts, saved reels, handwritten list).
Every one has been converted to gluten-free and, where the source used meat, a vegetarian
version sits in the main catalog and the meat version sits in the M section.

DELIBERATELY NOT INCLUDED: seitan. Seitan is vital wheat gluten. It is not a food that can be
made safe with a substitution, because gluten is the entire product. See the celiac notes.
"""

RECIPES_5 = [

# ============================== BREAKFAST ==============================
dict(id="B-31", cat="Breakfast", name="Impossible Egg McMuffin Stack",
 servings=1, prep=5, cook=10,
 ing=[("gf_english_muffin",65,"1 GF English muffin"),("impossible_patty",113,"1 patty"),
      ("egg_whole",100,"2 large"),("hash_brown_patty",64,"1 potato patty"),("cheddar",25,"1 slice"),
      ("ketchup",15,"1 tbsp"),("cholula",8,"1.5 tsp"),("mustard_yellow",8,"1.5 tsp"),
      ("mayo",10,"2 tsp"),("olive_oil",5,"1 tsp")],
 steps=["Get the hash brown patty going first, oven or air fryer at 400F for 10 minutes, since it takes the longest.",
        "Cook the Impossible patty 3 minutes per side in a hot pan. Do not press it down.",
        "Fry the eggs in a ring mould or a wide-mouth jar lid so they stack instead of hanging over the edges.",
        "Toast the muffin. Build: mayo and mustard on the bottom, patty, cheese, egg, hash brown, then ketchup and Cholula on the top half."],
 storage="Eat fresh. The components can be batch-cooked and assembled in 3 minutes on a work morning.",
 prep_notes="Impossible patties are gluten-free by formulation (soy protein base, no wheat). English muffins are not, so the GF version is non-negotiable and it is the expensive part of this build.",
 subs=["Two corn tortillas instead of the muffin cuts the cost by roughly two-thirds and is naturally GF.",
       "Egg whites only drops ~90 kcal and 9 g fat.",
       "Skip the mayo to cut 68 kcal without noticeably changing it, given how much sauce is already on there."],
 variations=["Double stack: two patties, two eggs, roughly 900 kcal and 55 g protein.",
             "Swap Impossible for a black bean patty, cheaper and higher fiber."],
 manual_tags=["HIGH CALORIE","HIGH SATIETY","SAVORY"]),

dict(id="B-32", cat="Breakfast", name="Egg White Wrap Breakfast Burrito",
 servings=1, prep=5, cook=8,
 ing=[("egg_white",264,"8 large whites"),("egg_whole",50,"1 large"),("black_beans",120,"1/2 cup"),
      ("bell_pepper",70,"1/2 pepper"),("spinach",50,"1.5 cups"),("cheddar",35,"scant 1/3 cup"),
      ("salsa",50,"3 tbsp"),("olive_oil",7,"1/2 tbsp"),("cholula",8,"1.5 tsp")],
 steps=["Pour a thin layer of beaten egg white into a wide oiled nonstick pan over low heat and let it set undisturbed, 3 minutes. It becomes the wrap.",
        "Slide that onto a plate. Scramble the whole egg with the pepper and spinach in the same pan.",
        "Fill the egg white wrap with the scramble, beans, cheese and salsa. Roll it."],
 storage="Eat fresh. Egg white wraps do not reheat well.",
 prep_notes="Those social media egg white wraps claiming 5 g protein, 0 fat, 0 carbs are a single small wrap and the macros are rounded down. Eight whites is 28 g of protein, which is what makes this worth eating.",
 subs=["Store-bought egg white wraps save 5 minutes and cost several times more.",
       "A corn tortilla instead of the egg-white wrap adds 44 g carbs and turns it into a normal burrito."],
 variations=["Add tofu crumble or an Impossible patty for more calories."],
 manual_tags=["LOW CALORIE","HIGH SATIETY","LEUCINE PRIORITY"]),

dict(id="B-33", cat="Breakfast", name="Huevos Rancheros",
 servings=1, prep=6, cook=10,
 ing=[("corn_tortilla",52,"2 tortillas"),("egg_whole",150,"3 large"),("refried_beans_ff",180,"scant 1 cup"),
      ("salsa",80,"1/3 cup"),("cheddar",40,"1/3 cup"),("avocado",60,"1/3 large"),
      ("greek_yogurt_nonfat",50,"3 tbsp"),("olive_oil",10,"2 tsp"),("cholula",8,"1.5 tsp"),
      ("spice_generic",2,"cumin, chili")],
 steps=["Char the tortillas directly over a gas flame or in a dry pan until they blister. Soft tortillas make this dish sad.",
        "Warm the refried beans with the cumin and spread them thickly over the tortillas.",
        "Fry the eggs in oil, hard on the bottom, runny on top.",
        "Stack: tortilla, beans, egg, salsa, cheese, avocado, yogurt, Cholula."],
 storage="Eat fresh.", prep_notes="Check that the refried beans are vegetarian. Many brands are made with lard.",
 subs=["Greek yogurt in place of sour cream, four times the protein and a third of the fat."],
 variations=["Add a fried Impossible patty crumbled over the beans."],
 manual_tags=["HIGH SATIETY","SAVORY","HIGH FIBER"]),

dict(id="B-34", cat="Breakfast", name="Crustless Spinach and Cottage Cheese Quiche",
 servings=4, prep=15, cook=40,
 ing=[("egg_whole",400,"8 large"),("cottage_cheese_2",400,"1.75 cups"),("spinach",250,"8 packed cups"),
      ("mushrooms",200,"~16"),("onion",100,"1 small"),("cheddar",120,"1 cup shredded"),
      ("parmesan",40,"1/3 cup"),("olive_oil",14,"1 tbsp"),("spice_generic",3,"nutmeg, thyme, pepper")],
 steps=["Fry the onion and mushrooms 8 minutes until the water has cooked off completely. Wet vegetables make a watery quiche and there is no fixing it later.",
        "Wilt the spinach in, then squeeze the whole mixture in a sieve.",
        "Blend the eggs with the cottage cheese until smooth, stir in everything else.",
        "Pour into a greased pie dish, bake 40 minutes at 350F until set and puffed. Rest 10 minutes."],
 storage="4 days refrigerated, 2 months frozen in slices. Excellent cold.",
 prep_notes="Crustless dodges the GF pastry problem entirely, and the cottage cheese pushes it to roughly 30 g protein per slice.",
 subs=["Ricotta instead of cottage cheese.","Add potato for a heartier, higher-calorie version."],
 variations=["Feta and roasted red pepper, or broccoli and cheddar."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","LEUCINE PRIORITY","LOW CALORIE"]),

# ============================== LUNCH / DINNER ==============================
dict(id="L-41", cat="Lunch/Dinner", name="Thai Peanut Sauce Tofu and Rice",
 servings=4, prep=12, cook=18,
 ing=[("tofu_extrafirm",900,"3 blocks, pressed and cubed"),("rice_white_cooked",900,"4.5 cups cooked, from 3 cups dry"),
      ("coconut_milk_full",400,"1 can, 13.5 oz"),("peanut_butter",180,"3/4 cup"),("curry_paste",40,"2.5 tbsp massaman or red"),
      ("sugar",25,"2 tbsp white"),("soy_sauce_gf",15,"1 tbsp tamari"),("olive_oil",25,"2 tbsp"),
      ("broccoli_cooked",300,"3 cups"),("bell_pepper",150,"1.25 peppers"),("lemon_juice",20,"4 tsp lime")],
 steps=["Press and cube the tofu, then fry it in oil in batches over medium-high until browned on at least two sides. Crowding the pan is why tofu ends up pale and soft.",
        "In a saucepan, combine the coconut milk and curry paste over medium heat, whisking as it warms.",
        "When it simmers, add the peanut butter, sugar and tamari. Simmer 4 minutes, stirring, until it thickens and goes glossy.",
        "Steam the vegetables. Toss the tofu through the sauce and serve over rice with lime."],
 storage="Sauce keeps 3 weeks refrigerated. Tofu and rice 4 days.",
 prep_notes="Mom's version uses white sugar instead of dark brown and goes lighter on the massaman, and that is the right call. Dark brown sugar makes it cloying. Double the sauce and keep the extra for noodles.",
 subs=["Light coconut milk cuts ~120 kcal per serving but the sauce is noticeably thinner.",
       "Rice noodles instead of rice.",
       "Fish sauce is the traditional ingredient; GF tamari does the job and keeps it vegetarian."],
 variations=["As a dipping sauce for the tofu nuggets in S-50.","Cold peanut noodle salad with cucumber and carrot."],
 manual_tags=["MEAL PREP","HIGH CALORIE","BUDGET FRIENDLY","TWO-MEAL-DAY FRIENDLY"]),

dict(id="L-42", cat="Lunch/Dinner", name="Firecracker Tofu",
 servings=4, prep=20, cook=40,
 ing=[("tofu_extrafirm",900,"3 blocks"),("cornstarch",60,"1/2 cup"),("olive_oil",40,"3 tbsp"),
      ("buffalo_sauce",180,"3/4 cup"),("brown_sugar",120,"generous 1/2 cup, packed"),
      ("acv",10,"2 tsp"),("butter",14,"1 tbsp"),("soy_sauce_gf",5,"1 tsp tamari"),
      ("mustard_yellow",5,"1 tsp"),("rice_white_cooked",600,"3 cups"),("green_onion",30,"3 scallions"),
      ("spice_generic",3,"garlic powder, chili powder, salt")],
 steps=["Oven to 350F. Whisk the buffalo sauce, brown sugar, vinegar, melted butter, tamari, mustard and spices. Set aside.",
        "Press the tofu 15 minutes, cube it, pat completely dry and toss in the cornstarch until every face is coated.",
        "Fry in oil over medium-high until crisp on all sides, about 8 minutes, working in two batches.",
        "Put the tofu in a baking dish, pour the sauce over, bake 30 minutes, turning every 10 minutes. Scatter scallions and serve on rice."],
 storage="4 days. Reheat in the oven so it re-crisps.",
 prep_notes="The original calls for a full cup of brown sugar. Half a cup is plenty and it drops roughly 100 calories a serving. Confirm the buffalo sauce is GF, most are, and use GF tamari rather than soy sauce.",
 subs=["Air fry the coated tofu at 400F for 15 minutes instead of pan-frying, which cuts about 15 g of oil across the batch.",
       "Chicken version is in the M section."],
 variations=["Halve the sauce for a less sweet, more savory version.","Add roasted broccoli to the baking dish."],
 manual_tags=["MEAL PREP","HIGH CALORIE","SAVORY"]),

dict(id="L-43", cat="Lunch/Dinner", name="Spinach and Cottage Cheese Lasagna",
 servings=6, prep=25, cook=45,
 ing=[("gf_lasagna_noodle_dry",300,"~10 oz dry"),("marinara",900,"2 jars, ~3.75 cups"),
      ("cottage_cheese_2",700,"3 cups"),("mozzarella_ps",350,"3 cups shredded"),
      ("spinach",400,"13 packed cups, or 300 g frozen"),("egg_whole",100,"2 large"),
      ("parmesan",60,"1/2 cup"),("garlic",12,"4 cloves"),("spice_generic",4,"oregano, basil, pepper")],
 steps=["Boil the GF noodles 3 minutes short of the box time and lay them flat on oiled parchment. GF lasagna sheets tear and stick worse than wheat ones, so handle them one at a time.",
        "Wilt the spinach, squeeze it bone dry, and mix with the cottage cheese, eggs, parmesan and garlic. The eggs are what set the layer instead of letting it run.",
        "Layer: sauce, noodles, cheese mixture, mozzarella. Repeat three times. Finish with sauce and mozzarella.",
        "Cover with foil, bake 30 minutes at 375F, uncover and bake 15 more. Rest 20 minutes before cutting, which is not optional."],
 storage="4 days refrigerated, 3 months frozen. Freeze in individual portions.",
 prep_notes="The family version uses cottage cheese rather than ricotta. Cheaper and higher protein, so it stays. Roughly 45 g of protein per serving.",
 subs=["No-boil GF sheets exist and save the tearing problem, but add 100 ml more sauce.",
       "Zucchini sheets instead of noodles is L-40."],
 variations=["Add lentils or mushrooms to the sauce for fiber.","Add an Impossible crumble layer."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","LEUCINE PRIORITY","HIGH SATIETY"]),

dict(id="L-44", cat="Lunch/Dinner", name="California Rice Casserole",
 servings=6, prep=15, cook=45,
 ing=[("rice_white_cooked",800,"4 cups cooked"),("cottage_cheese_2",450,"2 cups"),
      ("greek_yogurt_nonfat",240,"1 cup, in place of sour cream"),("cheddar",200,"2 cups grated"),
      ("green_chilies",115,"1 can, 4 oz, diced"),("onion",120,"1 cup minced"),
      ("olive_oil",20,"1.5 tbsp, in place of margarine"),("spice_generic",3,"sweet basil, salt, garlic")],
 steps=["Fry the minced onion in the oil over medium for 6 minutes until soft and translucent.",
        "Combine the onion with the rice, cottage cheese, Greek yogurt, chilies, basil and salt. Hold back a third of the cheddar.",
        "Spread in an oiled 2-quart casserole dish, top with the remaining cheddar.",
        "Bake at 375F for 45 minutes until bubbling and browned at the edges."],
 storage="4 days refrigerated, 2 months frozen.",
 prep_notes="Two changes from the family recipe card: Greek yogurt instead of sour cream, which takes it from 6 g to 25 g of protein per serving for the same volume, and olive oil instead of margarine. Accent is MSG, which is gluten-free and entirely fine to use if you like it.",
 subs=["Sour cream if you want the original texture exactly, at a real protein cost.",
       "Brown rice adds fiber and a slightly firmer set."],
 variations=["Add black beans and corn.","Green chile and egg version for breakfast."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY","FREEZER FRIENDLY","HIGH SATIETY"]),

dict(id="L-45", cat="Lunch/Dinner", name="Tofu Pad Thai",
 servings=2, prep=15, cook=12,
 ing=[("rice_noodles_dry",150,"~5 oz dry"),("tofu_extrafirm",300,"1 block"),("egg_whole",100,"2 large"),
      ("bean_sprouts",150,"2 cups"),("carrot",80,"1.5 medium, shredded"),("green_onion",40,"4 scallions"),
      ("peanuts_roasted",40,"1/3 cup, crushed"),("soy_sauce_gf",30,"2 tbsp tamari"),
      ("lemon_juice",40,"2.5 tbsp lime"),("brown_sugar",30,"2.5 tbsp"),("sriracha",15,"1 tbsp"),
      ("olive_oil",20,"1.5 tbsp")],
 steps=["Soak the rice noodles in hot water 8 minutes until pliable but still firm. They finish in the pan and mushy noodles are the classic failure here.",
        "Whisk tamari, lime, brown sugar and sriracha into a sauce.",
        "Fry the pressed cubed tofu hard in oil, push aside, scramble the eggs in the same pan.",
        "Add drained noodles, sauce, carrot and sprouts. Toss over high heat 2 minutes. Peanuts, scallion and more lime at the table."],
 storage="2 days. Noodles firm up cold, loosen with a splash of water when reheating.",
 prep_notes="Rice noodles are naturally gluten-free, which makes pad thai one of the easier restaurant dishes to make safely at home. Traditional pad thai uses tamarind and fish sauce; lime and tamari get you most of the way there.",
 subs=["Tamarind paste, 2 tbsp, in place of some of the lime for the authentic sour note.",
       "Add extra egg for more protein at low cost."],
 variations=["Chicken or shrimp-free version stays in this section; the chicken version fits the M pattern."],
 manual_tags=["QUICK","SAVORY"]),

dict(id="L-46", cat="Lunch/Dinner", name="Tofu Lettuce Wraps",
 servings=2, prep=12, cook=12,
 ing=[("tofu_extrafirm",400,"1.3 blocks, crumbled"),("romaine",200,"1 head, leaves separated"),
      ("mushrooms",150,"~12, finely diced"),("carrot",100,"2 medium, diced"),
      ("soy_sauce_gf",30,"2 tbsp tamari"),("sriracha",15,"1 tbsp"),("honey",20,"1 tbsp"),
      ("lemon_juice",20,"4 tsp lime"),("garlic",10,"3 cloves"),("green_onion",30,"3 scallions"),
      ("olive_oil",14,"1 tbsp"),("cashews",40,"1/3 cup, chopped"),("rice_white_cooked",200,"1 cup, to serve")],
 steps=["Crumble the tofu and squeeze it in a towel. Dry tofu browns, wet tofu steams.",
        "Fry the tofu and mushrooms hard in oil for 8 minutes without stirring much, until genuinely browned.",
        "Add garlic, carrot, tamari, sriracha and honey. Cook 3 minutes until glossy.",
        "Off the heat add lime, scallion and cashews. Spoon into lettuce cups with rice on the side."],
 storage="Filling keeps 4 days. Keep the lettuce separate.",
 prep_notes="Butter lettuce holds a cup better than romaine if you can find it.",
 subs=["Water chestnuts for crunch if you have them.","Tempeh instead of tofu for more fiber."],
 variations=["Add a spoon of the L-41 peanut sauce."],
 manual_tags=["MEAL PREP","LOW CALORIE","QUICK"]),

dict(id="L-47", cat="Lunch/Dinner", name="Cheese Ravioli with Marinara and White Beans",
 servings=1, prep=3, cook=10,
 ing=[("gf_ravioli_cheese",180,"~6 oz GF cheese ravioli"),("marinara",180,"3/4 cup"),
      ("kidney_beans",150,"3/4 cup white beans"),("spinach",80,"2.5 packed cups"),
      ("parmesan",30,"1/4 cup"),("olive_oil",10,"2 tsp"),("garlic",8,"2 cloves"),
      ("spice_generic",2,"chili flakes, basil")],
 steps=["Boil the ravioli per the package. GF ravioli splits if it boils hard, so keep it at a gentle simmer.",
        "Fry the garlic in oil 30 seconds, add marinara and beans, simmer 5 minutes.",
        "Wilt the spinach in, fold in the drained ravioli, finish with parmesan."],
 storage="Eat fresh.",
 prep_notes="GF ravioli is expensive and low in protein for the calories. The white beans and parmesan are doing the actual protein work here, which is why they are in the recipe rather than optional.",
 subs=["Any GF filled pasta.","Regular GF pasta with ricotta stirred through is a third of the price."],
 variations=["Brown butter and sage instead of marinara."],
 manual_tags=["QUICK"]),

dict(id="L-48", cat="Lunch/Dinner", name="Mung Bean Fettuccine with Avocado Herb Sauce",
 servings=1, prep=10, cook=8,
 ing=[("mung_bean_pasta_dry",85,"~3 oz dry"),("avocado",100,"1/2 large"),("lemon_juice",25,"5 tsp lime"),
      ("olive_oil",14,"1 tbsp"),("garlic",8,"2 cloves"),("cherry_tomatoes",120,"~12"),
      ("cucumber",80,"1/3 cucumber"),("onion",30,"2 tbsp red, diced"),
      ("spice_generic",3,"cilantro, salt, pepper")],
 steps=["Boil the mung bean pasta 6 to 7 minutes. It goes from firm to falling apart quickly, so start tasting at 5.",
        "Rinse it under cold water, which stops the cooking and removes the starchy coating that makes bean pastas gummy.",
        "Blend the avocado, lime, oil, garlic and cilantro with 3 tbsp water into a pourable sauce.",
        "Toss cold with the tomatoes, cucumber and red onion."],
 storage="2 days. The avocado sauce browns, so press cling film onto the surface.",
 prep_notes="Mung bean pasta is genuinely 24 to 25 g of protein per dry serving, which is the one impressive claim in that video that holds up. The 0 g fat claim does not; it is closer to 1 to 2 g, and this dish adds more.",
 subs=["Chickpea or lentil pasta, similar protein, different texture.",
       "Add tofu or edamame for another 15 to 20 g protein."],
 variations=["Warm version with roasted vegetables and no cold rinse."],
 manual_tags=["HIGH FIBER","QUICK","NO-COOK"]),

# ============================== SNACKS ==============================
dict(id="S-61", cat="Snack", name="Cookies and Cream Protein Cheesecake Cup",
 servings=2, prep=8, cook=0,
 ing=[("greek_yogurt_nonfat",225,"1 cup fat-free"),("cream_cheese_whipped",40,"1/4 cup whipped"),
      ("whey_isolate",30,"1 scoop vanilla"),("gf_sandwich_cookie",32,"~4 GF sandwich cookies, crushed"),
      ("sf_pudding_mix",8,"1 tbsp sugar-free cheesecake pudding mix"),("whipped_cream",10,"4 tbsp"),
      ("salt",1,"pinch")],
 steps=["Whip the Greek yogurt, cream cheese, protein powder, pudding mix and salt with a hand mixer for 2 minutes until it is thick and holds a peak.",
        "Crush two-thirds of the cookies to crumbs and fold them through.",
        "Divide into two cups, chill 30 minutes.",
        "Top with whipped cream and the remaining cookies broken into pieces."],
 storage="3 days refrigerated. The cookie pieces soften after day one, which some people prefer.",
 prep_notes="The original uses Oreos and Oreo O's cereal. Both are wheat-based, so neither is safe for me. Glutino, Goodie Girl and K-Toos all make GF chocolate sandwich cookies that crush into an identical crumb. The sugar-free pudding mix is the ingredient doing the cheesecake flavour and most brands are GF, but check the box for wheat starch.",
 subs=["Skip the pudding mix and add 1 tsp vanilla plus 1 tbsp lemon juice.",
       "Cottage cheese blended smooth instead of the cream cheese raises protein by ~6 g per serving."],
 variations=["Peanut butter cup version: cocoa powder in the base, GF peanut butter cups on top."],
 manual_tags=["SWEET","LEUCINE PRIORITY","MEAL PREP"]),

dict(id="S-62", cat="Snack", name="Hot Artichoke Dip",
 servings=6, prep=8, cook=25,
 ing=[("artichoke_hearts",400,"1 large can, drained and chopped"),
      ("greek_yogurt_nonfat",240,"1 cup, in place of mayo and sour cream"),
      ("mayo",60,"1/4 cup"),("mozzarella_ps",180,"1.5 cups shredded"),("parmesan",50,"1/2 cup"),
      ("garlic",8,"2 cloves, or 1 tsp garlic paste"),("spice_generic",2,"black pepper, chili flakes"),
      ("carrot",300,"6 medium, as dippers")],
 steps=["Drain and chop the artichoke hearts, then press them in a sieve. Canned artichokes hold a surprising amount of water.",
        "Mix everything except a handful of the mozzarella.",
        "Spread in a casserole dish, top with the reserved cheese.",
        "Bake at 350F for 20 to 25 minutes until bubbling and browned on top."],
 storage="4 days. Reheat covered so the top does not burn.",
 prep_notes="The card already suggests swapping in Greek yogurt. Doing it for the sour cream and half the mayo takes this from roughly 5 g to 14 g protein per serving and cuts around 130 calories, and the texture holds. Serve with vegetables or GF crackers, not garlic bread.",
 subs=["All Greek yogurt, no mayo, works but tastes noticeably leaner. Keeping a quarter cup of mayo is the sensible compromise.",
       "Add a can of drained spinach for a spinach artichoke version."],
 variations=["Add diced green chilies and pepper jack."],
 manual_tags=["SAVORY","MEAL PREP","HIGH CALCIUM"]),

dict(id="S-63", cat="Snack", name="Flourless Banana Oat Cookies",
 servings=8, prep=10, cook=18,
 ing=[("banana",360,"3 large, very ripe"),("applesauce_unsw",80,"1/3 cup"),
      ("oats_gf_dry",180,"2 cups certified GF"),("almond_milk_unsw",60,"1/4 cup"),
      ("raisins",40,"1/4 cup"),("dark_chocolate_70",120,"~1 cup chunks"),
      ("whey_isolate",30,"1 scoop vanilla"),("vanilla_extract",4,"1 tsp"),("cinnamon",3,"1 tsp")],
 steps=["Oven to 350F. Mash the bananas properly. Underripe bananas will not sweeten these and there is no added sugar to compensate.",
        "Mix everything together and let it stand 5 minutes so the oats absorb the liquid.",
        "Spoon 16 mounds onto a lined tray and flatten them slightly. They do not spread on their own.",
        "Bake 15 to 18 minutes until the edges are set."],
 storage="4 days at room temperature, 3 months frozen.",
 prep_notes="Certified gluten-free oats specifically. Standard rolled oats are cross-contaminated with wheat during harvesting and milling, and this is the most common way a strict gluten-free diet goes wrong without anyone noticing.",
 subs=["Skip the protein powder and it still works, at 3 g less protein per cookie.",
       "Lily's chocolate keeps sugar down; any 70% dark works."],
 variations=["Add 2 tbsp peanut butter to the batter.","Walnuts instead of raisins."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","SWEET","BUDGET FRIENDLY"]),

dict(id="S-64", cat="Snack", name="String Cheese and Fruit Work Pack",
 servings=1, prep=2, cook=0,
 ing=[("string_cheese_light",56,"2 light string cheese"),("apple",180,"1 large"),
      ("almonds",25,"~20"),("rice_cake",22,"2 cakes")],
 steps=["Put it in a bag the night before.","Eat it at work."],
 storage="Keeps a full shift unrefrigerated. Cheese is fine at room temperature for several hours.",
 prep_notes="Beats fruit and two protein bars, which is what I default to otherwise. Costs less, 23 g of protein, and calcium and magnesium the bars do not have. Two of these plus a jar of overnight oats is a work day handled.",
 subs=["Any hard cheese portioned out.","Pumpkin seeds instead of almonds for more zinc."],
 variations=["Add a hard-boiled egg for another 6 g protein."],
 manual_tags=["NO-COOK","QUICK","BUDGET FRIENDLY","HIGH CALCIUM"]),

# ============================== DRINKS ==============================
dict(id="D-41", cat="Drink", name="Zinc Booster Smoothie",
 servings=1, prep=4, cook=0,
 ing=[("spinach",30,"1 cup"),("banana",60,"1/2 medium"),("greek_yogurt_nonfat",120,"1/2 cup"),
      ("almond_milk_unsw",240,"1 cup unsweetened"),("pumpkin_seeds",15,"1 tbsp"),
      ("whey_isolate",30,"1 scoop vanilla"),("hemp_hearts",10,"1 tbsp")],
 steps=["Blend the spinach with the almond milk first until there is no fleck left.",
        "Add everything else and blend 45 seconds. Blend the seeds properly or they stay gritty."],
 storage="Drink fresh.",
 prep_notes="The name is fair. Pumpkin seeds, hemp hearts and dairy together deliver roughly 4 mg of zinc, which is around a third of a day, and zinc is one of the nutrients a vegetarian diet with celiac genuinely runs short on. Adding the protein powder is what makes it a feeding rather than a garnish.",
 subs=["Milk instead of almond milk adds ~70 kcal and 8 g protein.",
       "Cashews instead of pumpkin seeds, less zinc, creamier."],
 variations=["Add cocoa powder, which hides the spinach entirely and adds magnesium."],
 manual_tags=["HIGH MICRONUTRIENT DENSITY","QUICK","LEUCINE PRIORITY"]),

# ============================== SDA MEAT / FISH ==============================
dict(id="M-21", cat="SDA Meat/Fish", name="Firecracker Chicken",
 servings=4, prep=20, cook=45,
 ing=[("chicken_breast",680,"1.5 lb raw"),("cornstarch",90,"3/4 cup"),("egg_whole",150,"3 large, whisked"),
      ("olive_oil",50,"~4 tbsp for frying"),("buffalo_sauce",180,"3/4 cup"),
      ("brown_sugar",120,"generous 1/2 cup, packed"),("acv",10,"2 tsp"),("butter",14,"1 tbsp"),
      ("soy_sauce_gf",5,"1 tsp tamari"),("mustard_yellow",5,"1 tsp"),
      ("rice_white_cooked",600,"3 cups"),("spice_generic",3,"garlic powder, chili powder, salt")],
 steps=["Oven to 350F. Whisk the sauce ingredients together and set aside.",
        "Cut the chicken into 2-inch pieces, pat completely dry, season with salt and pepper.",
        "Whisk the eggs vigorously until uniform in colour, toss the chicken through, then dredge in cornstarch.",
        "Fry in oil until golden, transfer to a baking dish, pour the sauce over and bake 30 minutes, turning every 10."],
 storage="4 days. Reheat in the oven.",
 prep_notes="Cornstarch rather than flour, GF tamari rather than soy sauce, and check the buffalo sauce label. That is the whole gluten-free conversion. Half a cup of brown sugar instead of a full cup. The original is cloying.",
 subs=["Tofu version is L-42.","Thighs instead of breast, juicier, ~90 kcal more per serving."],
 variations=["Halve the sugar and add more vinegar for a sharper sauce."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","HIGH CALORIE","LEUCINE PRIORITY"]),

dict(id="M-22", cat="SDA Meat/Fish", name="Chicken Pad Thai",
 servings=2, prep=15, cook=14,
 ing=[("rice_noodles_dry",150,"~5 oz dry"),("chicken_breast",300,"~10 oz raw"),("egg_whole",100,"2 large"),
      ("bean_sprouts",150,"2 cups"),("carrot",80,"1.5 medium"),("green_onion",40,"4 scallions"),
      ("peanuts_roasted",40,"1/3 cup"),("soy_sauce_gf",30,"2 tbsp tamari"),
      ("lemon_juice",40,"2.5 tbsp lime"),("brown_sugar",30,"2.5 tbsp"),("sriracha",15,"1 tbsp"),
      ("olive_oil",20,"1.5 tbsp")],
 steps=["Soak the rice noodles in hot water 8 minutes until pliable.",
        "Slice the chicken thin against the grain and sear hard in oil, 4 minutes. Remove.",
        "Scramble the eggs in the same pan, then add the drained noodles, sauce, carrot and sprouts.",
        "Return the chicken, toss over high heat 2 minutes. Peanuts, scallion and lime to finish."],
 storage="2 days.", prep_notes="Rice noodles are naturally GF. Check the sriracha and use tamari.",
 subs=["Tofu version is L-45."], variations=["Add tamarind paste for the traditional sour note."],
 manual_tags=["SDA-COMPATIBLE","QUICK","LEUCINE PRIORITY"]),
]
