# -*- coding: utf-8 -*-
"""Recipe library, part 2: Snacks (S), Drinks (D), and the SEPARATE SDA-compatible meat/fish section (M).
The M section is kept entirely separate from the general catalog by design."""

RECIPES_2 = [
# ---------------------------- SNACKS ----------------------------
dict(id="S-01", cat="Snack", name="Cinnamon Protein Mug Cake",
 servings=1, prep=3, cook=1,
 ing=[("gf_oat_flour",25,"1/4 cup"),("whey_isolate",20,"2/3 scoop"),("egg_white",33,"1 large white"),
      ("milk_skim",60,"1/4 cup"),("baking_powder",2,"1/2 tsp"),("cinnamon",2,"1 tsp")],
 steps=["Mix everything in a wide mug with a fork until no dry pockets remain.",
        "Microwave 60 to 75 seconds. Stop the second it stops looking wet on top.",
        "Overcooking by 20 seconds turns any protein mug cake into rubber. This is the whole skill."],
 storage="Eat immediately.",
 prep_notes="", subs=["Casein gives a moister crumb than whey."],
 variations=["Add 10 g chocolate chips pressed into the middle before microwaving."],
 manual_tags=["QUICK"]),

dict(id="S-02", cat="Snack", name="Greek Yogurt with Honey and Almonds",
 servings=1, prep=2, cook=0,
 ing=[("greek_yogurt_nonfat",170,"1 container"),("honey",10,"1.5 tsp"),("almonds",15,"~12 almonds")],
 steps=["Spoon yogurt into a bowl.","Drizzle honey, top with chopped almonds."],
 storage="Assemble fresh.", prep_notes="",
 subs=["Skyr for slightly more protein."], variations=["Add cinnamon and a chopped date."],
 manual_tags=["QUICK","PORTABLE"]),

dict(id="S-03", cat="Snack", name="Cottage Cheese and Pineapple",
 servings=1, prep=2, cook=0,
 ing=[("cottage_cheese_2",150,"2/3 cup"),("pineapple",100,"2/3 cup chunks")],
 steps=["Combine. Black pepper on top is unexpected and good."],
 storage="2 days sealed.", prep_notes="",
 subs=["Canned pineapple in juice, drained, works fine."], variations=["Mango instead of pineapple."],
 manual_tags=["QUICK","PORTABLE"]),

dict(id="S-04", cat="Snack", name="Crispy Roasted Chickpeas",
 servings=2, prep=5, cook=30,
 ing=[("chickpeas",300,"1.5 cups cooked"),("olive_oil",14,"1 tbsp"),("spice_generic",6,"2 tsp seasoning")],
 steps=["Dry the chickpeas completely with a towel. Wet chickpeas steam and never crisp.",
        "Toss with oil and seasoning.",
        "Roast at 400F for 30 minutes, shaking twice, or air-fry 18 minutes at 390F.",
        "Season again after roasting and cool uncovered."],
 storage="Store uncovered or loosely covered at room temperature 3 days. Sealed containers make them soft.",
 prep_notes="", subs=["Canned chickpeas, rinsed and dried."],
 variations=["Ranch, curry, or chili-lime seasoning."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY","HIGH FIBER","VEGAN"]),

dict(id="S-05", cat="Snack", name="Peanut Butter Protein Balls",
 servings=6, prep=12, cook=0,
 ing=[("oats_gf_dry",120,"1.5 cups"),("peanut_butter",96,"6 tbsp"),("whey_isolate",60,"2 scoops"),
      ("honey",60,"3 tbsp"),("choc_chips_mini",30,"3 tbsp")],
 steps=["Mix everything in a bowl. It will look too dry at first; keep working it for a full minute before adding liquid.",
        "If it still will not hold, add water 1 tsp at a time.",
        "Roll into 6 balls, refrigerate 30 minutes to set."],
 storage="1 week refrigerated, 3 months frozen.",
 prep_notes="Best portable snack in the catalog for a job site with no fridge.",
 subs=["Powdered peanut butter plus water cuts fat substantially but they hold together worse."],
 variations=["Add 15 g ground flax for omega-3 ALA and fiber."],
 manual_tags=["MEAL PREP","PORTABLE","FREEZER FRIENDLY"]),

dict(id="S-06", cat="Snack", name="Salted Edamame",
 servings=1, prep=1, cook=5,
 ing=[("edamame_shelled",155,"1 cup shelled"),("salt",1,"1/4 tsp")],
 steps=["Microwave frozen edamame 4 minutes with a splash of water, covered.","Drain, salt, eat hot."],
 storage="3 days refrigerated, good cold.", prep_notes="",
 subs=["In-pod edamame, same weight of edible portion."],
 variations=["Toss with tamari, sesame oil and chili flakes."],
 manual_tags=["QUICK","VEGAN","HIGH FIBER"]),

dict(id="S-07", cat="Snack", name="Brownie Batter Protein Yogurt",
 servings=1, prep=3, cook=0,
 ing=[("greek_yogurt_nonfat",200,"~7 oz"),("cocoa_powder",6,"1 tbsp"),("whey_isolate",15,"1/2 scoop"),("honey",10,"1.5 tsp")],
 steps=["Add 15 ml water to the yogurt first, then whisk in cocoa and protein.",
        "Whisk 45 seconds. It should go from grainy to glossy.",
        "Freeze 15 minutes for a thicker, more dessert-like texture."],
 storage="2 days.", prep_notes="",
 subs=["Casein makes it thicker and more like frosting."],
 variations=["Top with 10 g crushed dark chocolate."],
 manual_tags=["QUICK"]),

dict(id="S-08", cat="Snack", name="Rice Cakes with Peanut Butter and Banana",
 servings=1, prep=3, cook=0,
 ing=[("rice_cake",18,"2 cakes"),("peanut_butter",32,"2 tbsp"),("banana",60,"1/2 medium")],
 steps=["Spread peanut butter, layer banana, dust with cinnamon."],
 storage="Eat fresh.", prep_notes="Fast carbs plus fat. Good 60 to 90 minutes pre-training, not 15.",
 subs=["Powdered peanut butter for a lighter pre-workout version."],
 variations=["Honey drizzle and flaky salt."],
 manual_tags=["QUICK","PRE-WORKOUT FRIENDLY"]),

dict(id="S-09", cat="Snack", name="Hummus and Vegetable Plate",
 servings=1, prep=5, cook=0,
 ing=[("hummus",100,"~1/2 cup"),("carrot",80,"1 carrot"),("bell_pepper",80,"3/4 pepper"),("cucumber",80,"1/3 cucumber")],
 steps=["Cut everything into sticks.","Serve with hummus."],
 storage="Cut vegetables keep 4 days in water in the fridge.", prep_notes="",
 subs=["Make hummus from a can of chickpeas, tahini, lemon and garlic for a third of the price."],
 variations=["Add 100 g cottage cheese on the side for +16 g protein."],
 manual_tags=["HIGH FIBER","VEGAN","MEAL PREP"]),

dict(id="S-10", cat="Snack", name="Cheesy Nutritional Yeast Popcorn",
 servings=1, prep=2, cook=3,
 ing=[("popcorn_popped",30,"~5 cups popped"),("nutritional_yeast",8,"2 tbsp"),("olive_oil",5,"1 tsp")],
 steps=["Air-pop the kernels or use a plain microwave bag.",
        "Toss with oil first, then the nutritional yeast. Oil first is what makes it stick."],
 storage="Eat fresh.", prep_notes="High-volume, high-fiber, low-calorie. Good when I'm hungry but out of calories.",
 subs=[], variations=["Add smoked paprika and garlic powder."],
 manual_tags=["HIGH FIBER","LOW CALORIE","VEGAN"]),

dict(id="S-11", cat="Snack", name="Hard-Boiled Eggs and an Apple",
 servings=1, prep=2, cook=10,
 ing=[("egg_whole",150,"3 large eggs"),("apple",150,"1 medium")],
 steps=["Boil eggs 9 minutes, then plunge into ice water for 5 minutes. The ice bath is what makes them peel cleanly.",
        "Salt and pepper. Eat with the apple."],
 storage="Boiled eggs in shell keep 7 days refrigerated.",
 prep_notes="Boil a dozen Sunday. Zero-effort protein for a truck or a lunchbox.",
 subs=[], variations=["Everything bagel seasoning on the eggs."],
 manual_tags=["MEAL PREP","PORTABLE","BUDGET FRIENDLY"]),

dict(id="S-12", cat="Snack", name="Chocolate Chia Protein Cup",
 servings=1, prep=4, cook=0,
 ing=[("chia",20,"1.5 tbsp"),("milk_2",150,"2/3 cup"),("casein_powder",20,"2/3 scoop"),("cocoa_powder",4,"3/4 tbsp"),("honey",10,"1.5 tsp")],
 steps=["Whisk casein and cocoa into the milk until smooth.","Add chia, whisk, wait 5 minutes, whisk again.","Refrigerate 4 hours."],
 storage="5 days.", prep_notes="Make 4 at a time.",
 subs=["Whey works, sets looser."], variations=["Add 10 g peanut butter."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="S-13", cat="Snack", name="Protein Cookie Dough Bites",
 servings=2, prep=8, cook=0,
 ing=[("pb_powder",24,"4 tbsp"),("gf_oat_flour",30,"1/3 cup"),("whey_isolate",20,"2/3 scoop"),
      ("milk_skim",50,"3 tbsp"),("honey",15,"2 tsp"),("choc_chips_mini",12,"1 tbsp")],
 steps=["Mix the dry ingredients first.","Add milk and honey a little at a time until it forms a stiff dough.",
        "Fold in chips, roll into bites, chill 20 minutes."],
 storage="1 week refrigerated.", prep_notes="",
 subs=["Real peanut butter instead of powdered: richer, adds about 130 kcal per serving."],
 variations=["Roll in cocoa powder."],
 manual_tags=["MEAL PREP","PORTABLE"]),

dict(id="S-14", cat="Snack", name="Portioned Trail Mix",
 servings=1, prep=2, cook=0,
 ing=[("almonds",20,"~16 almonds"),("walnuts",15,"~7 halves"),("pumpkin_seeds",15,"1.5 tbsp"),
      ("raisins",20,"2 tbsp"),("dark_chocolate_70",10,"2 squares")],
 steps=["Portion into a small bag or container. Portion it, do not eat from the bulk bag; this is 400 calories in a handful."],
 storage="1 month at room temperature.",
 prep_notes="Make 7 bags on Sunday. Solves the mid-shift energy crash.",
 subs=["Cashews or sunflower seeds swap 1:1."],
 variations=["Skip the raisins and chocolate for a lower-carb version."],
 manual_tags=["PORTABLE","HIGH CALORIE","MEAL PREP"]),

dict(id="S-15", cat="Snack", name="Savory Cottage Cheese Bowl",
 servings=1, prep=4, cook=0,
 ing=[("cottage_cheese_2",200,"~7/8 cup"),("cherry_tomatoes",80,"8 tomatoes"),("cucumber",60,"1/4 cucumber"),
      ("olive_oil",5,"1 tsp"),("spice_generic",2,"1 tsp everything seasoning")],
 steps=["Spread cottage cheese in a shallow bowl.","Top with halved tomatoes and diced cucumber.",
        "Drizzle oil, hit it with seasoning and cracked pepper."],
 storage="Best fresh.", prep_notes="",
 subs=["Blend the cottage cheese smooth if the curds bother you."],
 variations=["Add 40 g avocado."],
 manual_tags=["QUICK","LOW CALORIE"]),

dict(id="S-16", cat="Snack", name="Mini Egg Muffins",
 servings=2, prep=8, cook=20,
 ing=[("egg_whole",300,"6 large eggs"),("spinach",80,"3 packed cups"),("bell_pepper",80,"3/4 pepper"),("cheddar",60,"2/3 cup shredded")],
 steps=["Grease a 12-cup muffin tin properly. Egg welds itself to bare metal.",
        "Whisk eggs with salt and pepper. Divide chopped vegetables and cheese between the cups, pour egg over.",
        "Bake at 350F for 18 to 20 minutes until they puff and set.",
        "They will deflate as they cool. That is normal."],
 storage="5 days refrigerated, 2 months frozen. Reheat 40 seconds.",
 prep_notes="Six muffins is one batch, three per serving.",
 subs=["Use 4 whole eggs plus 200 g egg whites for a leaner version."],
 variations=["Add crumbled tempeh or leftover roasted vegetables."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","PORTABLE"]),

# ---------------------------- DRINKS ----------------------------
dict(id="D-01", cat="Drink", name="Classic Chocolate Recovery Shake",
 servings=1, prep=2, cook=0,
 ing=[("whey_isolate",30,"1 scoop"),("milk_skim",300,"1.25 cups"),("banana",100,"1 medium"),("cocoa_powder",5,"1 tbsp")],
 steps=["Blend 30 seconds.","Drink within a couple of hours of training if that suits your schedule."],
 storage="Drink fresh.", prep_notes="",
 subs=["Water instead of milk drops about 105 kcal and 10 g protein."],
 variations=["Add 40 g oats to turn it into a meal."],
 manual_tags=["QUICK","POST-WORKOUT FRIENDLY"]),

dict(id="D-02", cat="Drink", name="Strawberry Cheesecake Protein Shake",
 servings=1, prep=3, cook=0,
 ing=[("whey_isolate",30,"1 scoop"),("greek_yogurt_nonfat",100,"~3.5 oz"),("strawberries",120,"1 cup"),("milk_skim",200,"3/4 cup")],
 steps=["Blend everything with 3 or 4 ice cubes.","The yogurt is what gives it the cheesecake tang; do not skip it."],
 storage="Drink fresh.", prep_notes="",
 subs=["Frozen strawberries and no ice."], variations=["Add 10 g crushed GF graham-style cookie on top."],
 manual_tags=["QUICK"]),

dict(id="D-03", cat="Drink", name="Peanut Butter Cup Mass Shake",
 servings=1, prep=3, cook=0,
 ing=[("whey_isolate",30,"1 scoop"),("milk_whole",300,"1.25 cups"),("peanut_butter",32,"2 tbsp"),
      ("oats_gf_dry",40,"1/2 cup"),("banana",100,"1 medium"),("cocoa_powder",5,"1 tbsp")],
 steps=["Blend the oats alone for 15 seconds first so they turn to flour and the shake is not gritty.",
        "Add everything else, blend 45 seconds."],
 storage="Drink fresh.",
 prep_notes="This is the single most efficient tool for closing a calorie gap on a day you barely ate.",
 subs=["Powdered peanut butter drops it by about 130 kcal."],
 variations=["Add 20 g dark chocolate."],
 manual_tags=["HIGH CALORIE","QUICK"]),

dict(id="D-04", cat="Drink", name="Protein Iced Coffee",
 servings=1, prep=2, cook=0,
 ing=[("cold_brew",300,"1.25 cups"),("whey_isolate",30,"1 scoop"),("milk_skim",120,"1/2 cup")],
 steps=["Shake the protein with the milk first in a shaker.",
        "Pour over ice, then top with cold brew.",
        "Never add protein powder to hot coffee. It curdles instantly."],
 storage="24 hours refrigerated.", prep_notes="",
 subs=["Clear whey isolate does not go milky if you prefer that."],
 variations=["Add sugar-free vanilla syrup."],
 manual_tags=["QUICK","LOW CALORIE"]),

dict(id="D-05", cat="Drink", name="Protein Boba Milk Tea",
 servings=1, prep=5, cook=8,
 ing=[("black_tea_brewed",200,"3/4 cup, strong"),("milk_2",150,"2/3 cup"),("whey_isolate",25,"3/4 scoop"),
      ("tapioca_pearls_dry",30,"1/4 cup dry"),("sugar",8,"2 tsp")],
 steps=["Boil the pearls in a lot of water, roughly 5 minutes, then let them sit off the heat 5 more. They should be chewy through the middle, not crunchy.",
        "Rinse in cold water and toss with the sugar while warm so they stay separate and take on sweetness.",
        "Brew the tea double strength and cool it completely.",
        "Shake milk and protein together, pour over the pearls and ice, add tea."],
 storage="Cooked pearls are only good the day they are made. They go hard in the fridge.",
 prep_notes="To cut calories: use half the pearls and unsweetened almond milk. To raise protein: 40 g protein and skip the sugar. Sweetness lives in the pearls and the syrup, not the protein.",
 subs=["Clear whey isolate makes a fruit-tea version that is not milky."],
 variations=["Matcha version: swap black tea for 2 g matcha whisked in hot water and cooled."],
 manual_tags=["QUICK"]),

dict(id="D-06", cat="Drink", name="Matcha Protein Latte",
 servings=1, prep=4, cook=0,
 ing=[("matcha",2,"1 tsp"),("milk_2",250,"1 cup"),("whey_isolate",25,"3/4 scoop"),("honey",8,"1 tsp")],
 steps=["Whisk matcha into 40 ml water just off the boil until no lumps remain, then cool it 2 minutes.",
        "Shake the cold milk with protein.","Combine over ice, sweeten."],
 storage="Drink fresh.", prep_notes="",
 subs=["Unsweetened soy milk for a dairy-free version with similar protein."],
 variations=["Iced or hot, but if hot, let the matcha base cool before adding protein."],
 manual_tags=["QUICK"]),

dict(id="D-07", cat="Drink", name="Protein Hot Chocolate",
 servings=1, prep=4, cook=3,
 ing=[("milk_2",300,"1.25 cups"),("cocoa_powder",8,"1.5 tbsp"),("casein_powder",25,"3/4 scoop"),("sugar",6,"1.5 tsp")],
 steps=["Make a paste with cocoa, sugar and 2 tbsp of the milk.",
        "Heat the rest of the milk to steaming but not boiling.",
        "Whisk casein into the warm, not hot, milk. Casein handles heat better than whey, but boiling will still ruin it."],
 storage="Drink fresh.", prep_notes="Good pre-bed if you like a slow-digesting protein feeding at night.",
 subs=["Whey will separate. Use casein or a casein-dominant blend here."],
 variations=["Add a pinch of cayenne and cinnamon."],
 manual_tags=["QUICK"]),

dict(id="D-08", cat="Drink", name="Green Recovery Smoothie",
 servings=1, prep=3, cook=0,
 ing=[("spinach",60,"2 packed cups"),("banana",100,"1 medium"),("mango_frozen",100,"3/4 cup"),
      ("whey_isolate",30,"1 scoop"),("milk_skim",250,"1 cup")],
 steps=["Blend spinach with the milk alone first until there are no green flecks.","Add everything else and blend 30 seconds."],
 storage="Drink fresh.", prep_notes="You cannot taste 60 g of spinach behind mango. This is the easiest way to add vitamin K, folate and magnesium.",
 subs=["Frozen spinach cubes work and are cheaper."], variations=["Add 1 tbsp ground flax."],
 manual_tags=["QUICK","HIGH MICRONUTRIENT DENSITY"]),

dict(id="D-09", cat="Drink", name="Berry Skyr Smoothie",
 servings=1, prep=3, cook=0,
 ing=[("skyr",150,"~5 oz"),("mixed_berries_frozen",150,"1.25 cups"),("milk_skim",200,"3/4 cup"),("whey_isolate",20,"2/3 scoop")],
 steps=["Blend until thick. Use a spoon if you want it as a bowl."],
 storage="Drink fresh.", prep_notes="", subs=["Greek yogurt swaps 1:1."],
 variations=["Add 10 g chia and let it sit 10 minutes."],
 manual_tags=["QUICK","HIGH SATIETY"]),

dict(id="D-10", cat="Drink", name="Vanilla Oat Gainer",
 servings=1, prep=3, cook=0,
 ing=[("oats_gf_dry",60,"3/4 cup"),("whey_isolate",30,"1 scoop"),("milk_whole",350,"1.5 cups"),
      ("peanut_butter",32,"2 tbsp"),("honey",20,"1 tbsp")],
 steps=["Blend oats to flour first.","Add the rest, blend 45 seconds.","Drink over 20 minutes, not in one go, or it sits heavy."],
 storage="Drink fresh.",
 prep_notes="Roughly 900 kcal in a glass. For days when my appetite is gone and I still need to eat.",
 subs=["2% milk drops it about 90 kcal."], variations=["Add a frozen banana."],
 manual_tags=["HIGH CALORIE","QUICK"]),

dict(id="D-11", cat="Drink", name="Tropical Protein Smoothie",
 servings=1, prep=3, cook=0,
 ing=[("mango_frozen",120,"1 cup"),("pineapple",100,"2/3 cup"),("whey_isolate",30,"1 scoop"),("soy_milk_unsw",250,"1 cup")],
 steps=["Blend 30 seconds with ice."],
 storage="Drink fresh.", prep_notes="", subs=["Coconut water instead of soy milk for a lighter version."],
 variations=["Add 60 g spinach; the mango hides it."],
 manual_tags=["QUICK"]),

dict(id="D-12", cat="Drink", name="Cottage Cheese Vanilla Milkshake",
 servings=1, prep=3, cook=0,
 ing=[("cottage_cheese_2",150,"2/3 cup"),("milk_skim",200,"3/4 cup"),("whey_isolate",20,"2/3 scoop"),("banana",80,"3/4 medium")],
 steps=["Blend 45 seconds, longer than you think. Under-blended cottage cheese is grainy and that is what puts people off it.",
        "Add ice and blend 10 more seconds."],
 storage="Drink fresh.", prep_notes="Cheapest way to hit 45 g of protein in a drink.",
 subs=[], variations=["Add cocoa and a spoon of peanut butter."],
 manual_tags=["QUICK","BUDGET FRIENDLY"]),

dict(id="D-13", cat="Drink", name="Mocha Casein Night Shake",
 servings=1, prep=3, cook=0,
 ing=[("casein_powder",30,"1 scoop"),("milk_2",300,"1.25 cups"),("cold_brew",100,"1/3 cup decaf"),("cocoa_powder",5,"1 tbsp")],
 steps=["Blend or shake hard.","Use decaf if this is a pre-bed feeding. Caffeine within 6 hours of sleep measurably cuts deep sleep even when you fall asleep fine."],
 storage="Drink fresh.", prep_notes="",
 subs=["Greek yogurt blended with milk is a whole-food casein source."],
 variations=["Freeze it 30 minutes for a pudding."],
 manual_tags=["QUICK"]),

dict(id="D-14", cat="Drink", name="Plant Protein Chocolate Shake",
 servings=1, prep=3, cook=0,
 ing=[("plant_protein",35,"1 scoop"),("soy_milk_unsw",300,"1.25 cups"),("banana",100,"1 medium"),("pb_powder",12,"2 tbsp")],
 steps=["Blend 30 seconds.","Soy milk matters here: it is the one plant milk with a complete amino acid profile and real protein."],
 storage="Drink fresh.",
 prep_notes="Pea and rice blends have a lower leucine fraction than whey, so this needs a slightly larger serving to match the same leucine dose.",
 subs=["Soy protein isolate has the best amino acid profile of the plant options."],
 variations=["Add 20 g oats."],
 manual_tags=["VEGAN","QUICK"]),

# ------------- SDA-COMPATIBLE MEAT AND FISH (SEPARATE SECTION) -------------
dict(id="M-01", cat="SDA Meat/Fish", name="Lemon Herb Salmon Bowl",
 servings=1, prep=5, cook=15,
 ing=[("salmon",170,"6 oz fillet"),("quinoa_cooked",180,"~1 cup"),("broccoli_cooked",120,"1 cup"),
      ("olive_oil",7,"1/2 tbsp"),("lemon_juice",10,"2 tsp")],
 steps=["Pat the fillet completely dry and salt it 10 minutes ahead.",
        "Sear skin-side down in the oil over medium-high 4 minutes without moving it, then flip for 2 to 3.",
        "Pull it at 125 to 130F internal. It carries over. Overcooked salmon is the most common mistake here.",
        "Serve over quinoa with broccoli, finish with lemon."],
 storage="3 days refrigerated. Eat cold over salad rather than reheating; reheated salmon is unpleasant.",
 prep_notes="Salmon is the highest-value item in this section: about 2 g of EPA plus DHA per serving, which no plant food supplies directly.",
 subs=["Frozen fillets, thawed overnight in the fridge, are fine and much cheaper."],
 variations=["Bake at 400F for 12 minutes instead."],
 manual_tags=["SDA-COMPATIBLE","OMEGA-3 RICH"]),

dict(id="M-02", cat="SDA Meat/Fish", name="Grilled Chicken Rice Bowl",
 servings=1, prep=5, cook=15,
 ing=[("chicken_breast",170,"6 oz cooked"),("rice_white_cooked",200,"~1.25 cups"),("bell_pepper",80,"3/4 pepper"),
      ("olive_oil",7,"1/2 tbsp"),("salsa",45,"3 tbsp")],
 steps=["Pound the breast to an even thickness. Uneven thickness is why chicken breast comes out dry at one end.",
        "Season, sear 6 minutes per side over medium-high, pull at 160F internal and rest 5 minutes.",
        "Slice against the grain, serve over rice with peppers and salsa."],
 storage="4 days refrigerated.",
 prep_notes="Cook 700 g at once. This is the backbone of most meal prep for anyone eating poultry.",
 subs=["Thighs are more forgiving and harder to dry out, at about 45 more calories per serving."],
 variations=["Shred it and use it in the taco or burrito builds."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP"]),

dict(id="M-03", cat="SDA Meat/Fish", name="Tuna Protein Bowl",
 servings=1, prep=6, cook=0,
 ing=[("canned_tuna",140,"1 large can, drained"),("greek_yogurt_nonfat",60,"1/4 cup"),("cucumber",80,"1/3 cucumber"),
      ("cherry_tomatoes",80,"8 tomatoes"),("olive_oil",5,"1 tsp")],
 steps=["Drain the tuna properly, pressing the lid down hard.",
        "Mix with Greek yogurt instead of mayo, plus lemon, mustard, salt and pepper.",
        "Fold in diced cucumber and tomatoes."],
 storage="2 days refrigerated.",
 prep_notes="Zero cook, 40 g of protein, works out of a cooler on a job site.",
 subs=["Canned salmon has more calcium (from the bones) and much more omega-3."],
 variations=["Serve on rice cakes or in lettuce cups."],
 manual_tags=["SDA-COMPATIBLE","QUICK","PORTABLE"]),

dict(id="M-04", cat="SDA Meat/Fish", name="Turkey Taco Bowl",
 servings=1, prep=5, cook=12,
 ing=[("ground_turkey_93",150,"~5 oz raw"),("black_beans",120,"2/3 cup"),("rice_brown_cooked",150,"3/4 cup"),
      ("salsa",60,"1/4 cup"),("cheddar",20,"2 tbsp shredded")],
 steps=["Brown the turkey hard over high heat, breaking it up. Do not stir constantly; let it crust.",
        "Add cumin, chili powder, garlic powder and 60 ml water, simmer 3 minutes.",
        "Build over rice with beans, salsa and cheese."],
 storage="4 days refrigerated, freezes 2 months.",
 prep_notes="", subs=["Ground chicken swaps directly."],
 variations=["Use it as taco filling with corn tortillas."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","FREEZER FRIENDLY"]),

dict(id="M-05", cat="SDA Meat/Fish", name="Baked Cod with Crispy Potatoes",
 servings=1, prep=8, cook=25,
 ing=[("cod",180,"6.5 oz fillet"),("potato",300,"2 small"),("olive_oil",14,"1 tbsp"),("spice_generic",3,"1 tsp seasoning")],
 steps=["Cube potatoes, toss in half the oil, roast at 425F for 20 minutes.",
        "Push them aside, add the cod, brush with remaining oil and seasoning.",
        "Bake 10 to 12 more minutes until the fish flakes.",
        "Cod is very lean and goes from perfect to chalky in about two minutes. Check it early."],
 storage="2 days.", prep_notes="", subs=["Tilapia or haddock work identically."],
 variations=["Lemon, capers and parsley."],
 manual_tags=["SDA-COMPATIBLE","LOW CALORIE"]),

dict(id="M-06", cat="SDA Meat/Fish", name="Sheet-Pan Chicken and Vegetables",
 servings=2, prep=10, cook=30,
 ing=[("chicken_breast",400,"~14 oz cooked"),("sweet_potato",400,"2 medium"),("broccoli_cooked",300,"2.5 cups"),("olive_oil",24,"5 tsp")],
 steps=["Start the sweet potato alone at 425F for 15 minutes; it needs longer than the rest.",
        "Add chicken and broccoli, oil and season everything, roast 15 more minutes.",
        "Crowding the pan steams instead of roasting. Use two pans if it looks tight."],
 storage="4 days.", prep_notes="One pan, two meals, minimal cleanup.",
 subs=["Thighs if you want it more forgiving."],
 variations=["Swap sweet potato for regular potato and add paprika."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP"]),

dict(id="M-07", cat="SDA Meat/Fish", name="Sardine Toast",
 servings=1, prep=5, cook=3,
 ing=[("sardines",90,"1 tin, drained"),("gf_bread",60,"2 slices"),("lemon_juice",5,"1 tsp"),
      ("olive_oil",5,"1 tsp"),("tomato",60,"1/2 tomato")],
 steps=["Toast the bread well.","Mash the sardines with lemon and olive oil.",
        "Spread over the toast, top with sliced tomato, salt and pepper."],
 storage="Eat fresh.",
 prep_notes="Nutritionally this punches far above its cost: about 1 g EPA plus DHA, 340 mg calcium from the bones, and 8 mcg B12 in one tin.",
 subs=["Canned salmon if sardines are too strong."],
 variations=["Add sliced red onion and chili flakes."],
 manual_tags=["SDA-COMPATIBLE","OMEGA-3 RICH","BUDGET FRIENDLY","HIGH MICRONUTRIENT DENSITY"]),

dict(id="M-08", cat="SDA Meat/Fish", name="Chicken Fried Rice",
 servings=1, prep=6, cook=12,
 ing=[("chicken_breast",150,"~5 oz cooked"),("rice_white_cooked",250,"1.5 cups, day-old"),("egg_whole",100,"2 large eggs"),
      ("peas_frozen",80,"1/2 cup"),("soy_sauce_gf",15,"1 tbsp tamari"),("olive_oil",10,"2 tsp")],
 steps=["Use cold day-old rice.","Scramble the eggs, remove them.",
        "Fry rice, diced chicken and peas over high heat 4 minutes.",
        "Return egg, add tamari, toss."],
 storage="3 days. Reheat until steaming hot.", prep_notes="Uses up leftover rice and leftover chicken at once.",
 subs=[], variations=["Add sriracha and sesame oil."],
 manual_tags=["SDA-COMPATIBLE","QUICK","POST-WORKOUT FRIENDLY"]),

dict(id="M-09", cat="SDA Meat/Fish", name="No-Cook Salmon Rice Bowl",
 servings=1, prep=6, cook=0,
 ing=[("canned_salmon",120,"1 can, drained"),("rice_white_cooked",180,"~1 cup"),("avocado",50,"1/4 large"),
      ("soy_sauce_gf",10,"2 tsp tamari"),("cucumber",60,"1/4 cucumber")],
 steps=["Flake the salmon, mash the small soft bones in; that is where most of the calcium is.",
        "Layer over rice with sliced cucumber and avocado.",
        "Dress with tamari and a little sesame oil or sriracha mayo."],
 storage="2 days.", prep_notes="No stove. Works when you get home at 8 p.m. and will not cook.",
 subs=["Canned tuna is leaner and cheaper but has far less omega-3."],
 variations=["Add nori strips and pickled ginger."],
 manual_tags=["SDA-COMPATIBLE","QUICK","OMEGA-3 RICH"]),

dict(id="M-10", cat="SDA Meat/Fish", name="Tilapia Tacos with Slaw",
 servings=1, prep=8, cook=10,
 ing=[("tilapia",170,"6 oz"),("corn_tortilla",78,"3 small tortillas"),("coleslaw_mix",80,"1.5 cups"),
      ("greek_yogurt_nonfat",40,"3 tbsp"),("salsa_verde",40,"3 tbsp")],
 steps=["Season the fish with chili powder, cumin and salt. Pan-sear 3 minutes per side.",
        "Mix Greek yogurt with salsa verde and lime for the sauce.",
        "Toss the slaw with half the sauce.","Char the tortillas, fill with flaked fish, slaw and remaining sauce."],
 storage="Eat fresh.", prep_notes="", subs=["Cod or any firm white fish."],
 variations=["Air-fry the fish at 400F for 8 minutes."],
 manual_tags=["SDA-COMPATIBLE","QUICK"]),
]
