# -*- coding: utf-8 -*-
"""Recipe library, part 3. Same schema as parts 1 and 2.
All main-catalog recipes are gluten-free and lacto-ovo vegetarian.
M-section items are gluten-free and SDA-compatible."""

RECIPES_3 = [

# ============================== BREAKFAST ==============================
dict(id="B-15", cat="Breakfast", name="Pumpkin Spice Protein Oats",
 servings=1, prep=3, cook=3,
 ing=[("oats_gf_dry",60,"3/4 cup dry"),("milk_2",240,"1 cup"),("whey_isolate",30,"1 scoop vanilla"),
      ("pumpkin_seeds",15,"2 tbsp"),("maple_syrup",15,"1 tbsp"),("cinnamon",3,"1 tsp"),("flax_ground",7,"1 tbsp")],
 steps=["Microwave oats and milk 2 minutes, stirring once at the halfway point.",
        "Let it sit 60 seconds so it stops steaming. Protein powder added to boiling oats goes grainy.",
        "Stir in the protein powder, flax and cinnamon until smooth.",
        "Top with maple syrup and pumpkin seeds."],
 storage="Best fresh. Keeps 2 days cold, loosen with a splash of milk when reheating.",
 prep_notes="The 60-second wait is the whole trick to smooth protein oats.",
 subs=["Canned pumpkin puree, 80 g, makes it genuinely pumpkin at the cost of 30 kcal.",
       "No whey: 30 g casein and 40 ml extra milk."],
 variations=["Swap maple for 1 tbsp honey and pumpkin seeds for chopped walnuts."],
 manual_tags=["QUICK","BUDGET FRIENDLY"]),

dict(id="B-16", cat="Breakfast", name="Egg White and Feta Breakfast Wrap",
 servings=1, prep=4, cook=6,
 ing=[("egg_white",198,"6 large whites"),("egg_whole",50,"1 large egg"),("gf_wrap",60,"1 large GF wrap"),
      ("feta",30,"~2 tbsp crumbled"),("spinach",60,"2 packed cups"),("olive_oil",7,"1/2 tbsp"),("salsa",40,"3 tbsp")],
 steps=["Heat the oil over medium. Wilt the spinach 1 minute and push it to one side.",
        "Pour in the eggs and whites. Scramble slowly, pulling from the edges.",
        "Kill the heat while they are still slightly wet. They finish in the pan.",
        "Warm the wrap 15 seconds, fill with eggs, feta and salsa, roll tight."],
 storage="Eat immediately. Wraps go soggy.",
 prep_notes="Cook a double batch of the egg mixture and reheat 40 seconds the next morning.",
 subs=["Corn tortillas, two of them, are cheaper and naturally GF. GF wraps are the expensive option here.",
       "Cottage cheese instead of feta cuts fat and raises protein."],
 variations=["Add black beans for fiber, or hot sauce and pickled jalapeno."],
 manual_tags=["QUICK","HIGH SATIETY"]),

dict(id="B-17", cat="Breakfast", name="Strawberry Cheesecake Overnight Oats",
 servings=1, prep=6, cook=0,
 ing=[("oats_gf_dry",50,"5/8 cup dry"),("greek_yogurt_nonfat",150,"2/3 cup"),("milk_skim",120,"1/2 cup"),
      ("whey_isolate",25,"3/4 scoop vanilla"),("strawberries",100,"~7 berries"),("chia",10,"scant 1 tbsp"),
      ("honey",10,"1.5 tsp")],
 steps=["Whisk the yogurt, milk, protein powder and honey until completely smooth before the oats go in.",
        "Fold in oats and chia.",
        "Layer half the sliced strawberries through the middle and the rest on top.",
        "Refrigerate 6 hours minimum."],
 storage="4 days airtight. Do not freeze.",
 prep_notes="Make four at once on Sunday. Biggest single upgrade to my work mornings.",
 subs=["Frozen berries work and are cheaper; they release liquid, so drop the milk to 100 ml.",
       "Cottage cheese blended smooth replaces the yogurt and adds protein."],
 variations=["Blueberry lemon: swap the fruit and add 1 tsp lemon juice and zest."],
 manual_tags=["MEAL PREP","TWO-MEAL-DAY FRIENDLY"]),

dict(id="B-18", cat="Breakfast", name="Banana Bread Baked Oats",
 servings=2, prep=8, cook=25,
 ing=[("oats_gf_dry",100,"1.25 cups dry"),("banana",180,"1.5 large, very ripe"),("egg_whole",100,"2 large"),
      ("whey_isolate",30,"1 scoop vanilla"),("milk_2",150,"2/3 cup"),("baking_powder",6,"1.5 tsp"),
      ("walnuts",25,"~1/4 cup chopped"),("cinnamon",3,"1 tsp")],
 steps=["Heat the oven to 350F.",
        "Blend everything except the walnuts until it is a smooth batter. A blender matters here.",
        "Pour into a greased small baking dish, scatter walnuts over the top.",
        "Bake 25 minutes until it springs back in the centre. Cool 5 minutes before cutting."],
 storage="4 days refrigerated, or freeze individual squares up to 2 months.",
 prep_notes="Double it in a 9x9 dish, cut into 4, and you have breakfast handled for four days.",
 subs=["No whey: add 30 g GF oat flour and it still works, just lower protein.",
       "Dairy-free: soy milk keeps the protein closest."],
 variations=["Chocolate chip version: 20 g mini chips instead of walnuts."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY"]),

dict(id="B-19", cat="Breakfast", name="Cottage Cheese Scrambled Eggs on GF Toast",
 servings=1, prep=3, cook=6,
 ing=[("egg_whole",150,"3 large"),("cottage_cheese_2",100,"scant 1/2 cup"),("gf_bread",70,"2 slices"),
      ("butter",7,"1.5 tsp"),("cherry_tomatoes",80,"~8"),("spice_generic",1,"black pepper, chives")],
 steps=["Beat the eggs with the cottage cheese. It looks wrong and it cooks into the creamiest scramble you will make.",
        "Melt the butter over low heat. Low, not medium. This is a slow scramble.",
        "Add the eggs and stir constantly for 4 to 5 minutes until just set.",
        "Toast the bread, pile the eggs on, add halved tomatoes and plenty of pepper."],
 storage="Eat fresh.", prep_notes="",
 subs=["Ricotta works the same way.","Skip the toast and serve over a baked potato for more carbs."],
 variations=["Add 20 g grated cheddar in the last 30 seconds."],
 manual_tags=["QUICK"]),

dict(id="B-20", cat="Breakfast", name="Tofu Breakfast Burrito Bowl",
 servings=1, prep=6, cook=10,
 ing=[("tofu_extrafirm",200,"~2/3 block, crumbled"),("black_beans",120,"1/2 cup"),("rice_brown_cooked",150,"3/4 cup"),
      ("nutritional_yeast",10,"2 tbsp"),("salsa",60,"1/4 cup"),("avocado",50,"1/4 large"),
      ("bell_pepper",70,"1/2 pepper"),("olive_oil",7,"1/2 tbsp"),("spice_generic",2,"cumin, turmeric, paprika")],
 steps=["Crumble the tofu with your hands. Press out excess water in a towel first, it browns instead of steaming.",
        "Fry the pepper in oil 3 minutes, add tofu and spices, cook 6 minutes until edges catch colour.",
        "Stir in nutritional yeast and the beans, heat through.",
        "Serve over rice with salsa and sliced avocado."],
 storage="Tofu mixture keeps 4 days. Add avocado fresh.",
 prep_notes="Quadruple the tofu scramble on Sunday. It reheats better than egg does.",
 subs=["Eggs instead of tofu if you want the higher leucine version.",
       "Corn tortillas instead of rice makes it an actual burrito."],
 variations=["Add chipotle in adobo for heat and smoke."],
 manual_tags=["MEAL PREP","VEGAN OPTION"]),

dict(id="B-21", cat="Breakfast", name="Kefir Muesli with Seeds and Fruit",
 servings=1, prep=5, cook=0,
 ing=[("oats_gf_dry",50,"5/8 cup dry"),("kefir_plain",250,"1 cup"),("skyr",100,"scant 1/2 cup"),
      ("raisins",20,"~2 tbsp"),("almonds",20,"~16"),("sunflower_seeds",10,"1 tbsp"),("apple",100,"1 small, grated")],
 steps=["Combine oats, kefir and skyr in a jar. Stir well.",
        "Grate the apple straight in, skin on, and stir immediately so it does not brown.",
        "Add raisins. Refrigerate at least 2 hours, ideally overnight.",
        "Top with chopped almonds and sunflower seeds when you eat it, so they stay crunchy."],
 storage="3 days. The nuts go soft if added early, keep them separate.",
 prep_notes="Kefir brings live cultures that plain yogurt does not, which is worth something given celiac and gut recovery.",
 subs=["Plain kefir only. Flavoured kefir is a sugar delivery system.",
       "Greek yogurt thinned with milk if kefir is not available."],
 variations=["Winter version: grated pear, cinnamon and walnuts."],
 manual_tags=["MEAL PREP","HIGH FIBER","QUICK"]),

dict(id="B-22", cat="Breakfast", name="Savory Polenta Bowl with Egg and Greens",
 servings=1, prep=4, cook=12,
 ing=[("cornmeal_polenta",60,"1/3 cup dry"),("milk_2",200,"3/4 cup"),("parmesan",25,"1/4 cup grated"),
      ("egg_whole",100,"2 large"),("kale",80,"2 packed cups"),("olive_oil",10,"2 tsp"),("garlic",6,"2 cloves")],
 steps=["Bring the milk and 200 ml water to a simmer, rain in the polenta whisking constantly.",
        "Cook 8 to 10 minutes on low, stirring often, until it pulls away from the pan. Beat in the parmesan.",
        "Meanwhile fry the garlic in oil 30 seconds, add kale and a splash of water, cover 3 minutes.",
        "Fry or poach the eggs. Serve on the polenta with the greens."],
 storage="Polenta sets solid when cold. Slice and pan-fry the leftovers, it is better that way.",
 prep_notes="Corn polenta is naturally gluten-free and one of the cheapest carbs available.",
 subs=["Cheddar or mozzarella instead of parmesan.","Spinach instead of kale, 1 minute instead of 3."],
 variations=["Add mushrooms fried hard in the same pan."],
 manual_tags=["BUDGET FRIENDLY","HIGH SATIETY"]),

# ============================== LUNCH / DINNER ==============================
dict(id="L-15", cat="Lunch/Dinner", name="Personal Tortilla Protein Pizza",
 servings=1, prep=4, cook=8,
 ing=[("corn_tortilla",78,"3 small tortillas"),("marinara",80,"1/3 cup"),("mozzarella_ps",80,"~3/4 cup shredded"),
      ("cottage_cheese_2",100,"scant 1/2 cup"),("bell_pepper",60,"1/2 pepper"),("mushrooms",50,"~4"),
      ("spice_generic",2,"oregano, chili flakes")],
 steps=["Heat the oven to 425F with a baking sheet already inside.",
        "Blend the cottage cheese smooth and mix it into the marinara. This is what makes it a protein pizza rather than a bread-and-cheese pizza.",
        "Stack the tortillas in threes so the base holds, spread sauce, add vegetables and mozzarella.",
        "Bake 7 to 8 minutes on the hot sheet until the cheese blisters."],
 storage="Eat fresh. Crust does not survive.", prep_notes="Under 15 minutes start to finish.",
 subs=["GF pizza base if you want the real thing, at roughly triple the cost.",
       "Ricotta instead of cottage cheese for a milder flavour."],
 variations=["White pizza: skip marinara, use blended cottage cheese with garlic and olive oil."],
 manual_tags=["QUICK","PIZZA"]),

dict(id="L-16", cat="Lunch/Dinner", name="Bulking Pizza with Ricotta and Olive Oil",
 servings=1, prep=6, cook=12,
 ing=[("gf_bread",100,"1 GF flatbread or 3 slices"),("marinara",100,"scant 1/2 cup"),("mozzarella_ps",100,"1 cup shredded"),
      ("ricotta_ps",100,"scant 1/2 cup"),("olive_oil",14,"1 tbsp"),("spinach",50,"1.5 cups"),
      ("parmesan",15,"2 tbsp"),("spice_generic",2,"oregano, garlic")],
 steps=["Oven to 425F.","Spread marinara, then dot the ricotta in spoonfuls across the surface.",
        "Add mozzarella, spinach and parmesan.","Bake 10 to 12 minutes. Finish with the olive oil poured over after it comes out, not before."],
 storage="2 days, reheat in a dry pan not a microwave.",
 prep_notes="Roughly 1,000 calories in one sitting. The meal for a day I'm behind on intake.",
 subs=["Cut the olive oil to halve the fat if you want it leaner."],
 variations=["Add roasted red pepper and chili oil."],
 manual_tags=["PIZZA","HIGH CALORIE","TWO-MEAL-DAY FRIENDLY"]),

dict(id="L-17", cat="Lunch/Dinner", name="Lower-Calorie Veggie Protein Pizza",
 servings=1, prep=8, cook=14,
 ing=[("cauliflower_rice",200,"2 cups"),("egg_whole",50,"1 large"),("mozzarella_ps",60,"1/2 cup shredded"),
      ("marinara",60,"1/4 cup"),("cottage_cheese_2",120,"1/2 cup"),("zucchini",70,"1/2 small"),
      ("cherry_tomatoes",80,"~8"),("spice_generic",2,"oregano, garlic powder")],
 steps=["Microwave the cauliflower rice 4 minutes, then squeeze it dry in a clean towel. Squeeze harder than feels reasonable.",
        "Mix with the egg, half the mozzarella and the seasoning. Press thin on parchment.",
        "Bake 20 minutes at 425F until the base is golden and firm before any topping goes on.",
        "Top with marinara, blended cottage cheese, vegetables and remaining cheese. Back in for 8 minutes."],
 storage="Eat fresh.", prep_notes="The dry-squeeze step is the difference between pizza and a wet mess.",
 subs=["Frozen riced cauliflower is fine and cheaper."],
 variations=["Add pickled jalapeno and chili flakes."],
 manual_tags=["PIZZA","LOW CALORIE","HIGH SATIETY"]),

dict(id="L-18", cat="Lunch/Dinner", name="Shakshuka with Feta and Chickpeas",
 servings=1, prep=6, cook=16,
 ing=[("egg_whole",150,"3 large"),("marinara",200,"3/4 cup"),("chickpeas",150,"3/4 cup"),
      ("feta",40,"~3 tbsp crumbled"),("bell_pepper",80,"1/2 pepper"),("onion",60,"1/2 small"),
      ("olive_oil",10,"2 tsp"),("spice_generic",3,"cumin, paprika, chili"),("gf_bread",35,"1 slice, to mop")],
 steps=["Fry the onion and pepper in oil over medium for 6 minutes until soft.",
        "Add spices, cook 30 seconds, then the marinara and chickpeas. Simmer 5 minutes.",
        "Make three wells with a spoon and crack an egg into each.",
        "Cover and cook 6 to 8 minutes until the whites set and the yolks are still soft. Scatter feta over the top."],
 storage="Sauce base keeps 4 days. Add fresh eggs each time.",
 prep_notes="Make a triple batch of the sauce base. It is the reheatable part.",
 subs=["Any white bean instead of chickpeas.","Skip the bread and serve over rice."],
 variations=["Green shakshuka: spinach and herbs instead of tomato base."],
 manual_tags=["HIGH FIBER","MEAL PREP"]),

dict(id="L-19", cat="Lunch/Dinner", name="Red Lentil Dal with Rice",
 servings=2, prep=5, cook=25,
 ing=[("lentils",300,"1.5 cups cooked from ~150 g dry"),("rice_white_cooked",300,"1.5 cups"),
      ("coconut_milk_light",120,"1/2 cup"),("onion",100,"1 small"),("garlic",10,"3 cloves"),
      ("spinach",100,"3 packed cups"),("olive_oil",14,"1 tbsp"),("spice_generic",5,"cumin, turmeric, garam masala, chili"),
      ("lemon_juice",15,"1 tbsp")],
 steps=["Fry the onion in oil 6 minutes until it takes colour, then garlic and spices for 1 minute.",
        "Add lentils and 300 ml water. Simmer 15 minutes until it thickens and the lentils break down.",
        "Stir in coconut milk and spinach, cook 3 more minutes.",
        "Finish with lemon juice. Acid at the end is what makes dal taste like dal rather than like mush."],
 storage="5 days refrigerated, 3 months frozen. Better on day two.",
 prep_notes="Cheapest high-protein meal in the whole catalog by a wide margin. Make a quadruple batch.",
 subs=["Any lentil works. Red breaks down fastest.",
       "Full-fat coconut milk adds ~120 kcal per serving if you need them."],
 variations=["Add cubed sweet potato with the lentils.","Stir 100 g of Greek yogurt in at the table for extra protein."],
 manual_tags=["BUDGET FRIENDLY","MEAL PREP","FREEZER FRIENDLY","HIGH FIBER"]),

dict(id="L-20", cat="Lunch/Dinner", name="Crispy Tofu Banh Mi Rice Bowl",
 servings=1, prep=10, cook=12,
 ing=[("tofu_extrafirm",200,"~2/3 block"),("rice_white_cooked",200,"1 cup"),("carrot",70,"1 medium, shredded"),
      ("cucumber",80,"1/3 cucumber"),("greek_yogurt_nonfat",60,"1/4 cup"),("sriracha",15,"1 tbsp"),
      ("soy_sauce_gf",15,"1 tbsp tamari"),("olive_oil",10,"2 tsp"),("lemon_juice",15,"1 tbsp lime")],
 steps=["Press the tofu 10 minutes, cube it, toss with tamari and a spoon of cornstarch if you have it.",
        "Pan-fry in oil over medium-high, 3 minutes per side, without moving it. Moving it is why tofu does not get crispy.",
        "Toss the shredded carrot and sliced cucumber with lime juice and a pinch of sugar. Ten minutes is enough to quick-pickle.",
        "Mix yogurt and sriracha for the sauce. Build the bowl and drizzle."],
 storage="Components 4 days separately. Tofu loses crisp but tastes fine.",
 prep_notes="Verify the tamari is certified GF. Regular soy sauce contains wheat.",
 subs=["Air fryer, 400F for 12 minutes, uses less oil.","Tempeh instead of tofu for more fiber."],
 variations=["Add pickled jalapeno and fresh cilantro."],
 manual_tags=["MEAL PREP","HIGH SATIETY"]),

dict(id="L-21", cat="Lunch/Dinner", name="Southwest Quinoa and Black Bean Skillet",
 servings=2, prep=6, cook=14,
 ing=[("quinoa_cooked",400,"2 cups cooked"),("black_beans",250,"1.25 cups"),("sweet_corn",120,"3/4 cup"),
      ("bell_pepper",120,"1 pepper"),("onion",80,"1 small"),("cheddar",60,"1/2 cup shredded"),
      ("salsa",100,"scant 1/2 cup"),("olive_oil",14,"1 tbsp"),("spice_generic",3,"cumin, chili, smoked paprika"),
      ("avocado",60,"1/3 large")],
 steps=["Fry onion and pepper in oil 6 minutes.","Add spices, beans, corn and salsa. Cook 4 minutes.",
        "Fold in the cooked quinoa, heat through 3 minutes.",
        "Kill the heat, scatter cheddar over, cover 2 minutes to melt. Top with avocado."],
 storage="4 days. Reheats well, one of the better lunchbox options here.",
 prep_notes="Quinoa is a carb source, not a protein source, despite the marketing. The beans and cheese are doing the protein work.",
 subs=["Rice instead of quinoa is cheaper and nearly identical nutritionally for this purpose.",
       "Pinto or kidney beans work."],
 variations=["Add a fried egg on top of each portion."],
 manual_tags=["MEAL PREP","HIGH FIBER","BUDGET FRIENDLY"]),

dict(id="L-22", cat="Lunch/Dinner", name="Creamy Tomato White Bean Pasta",
 servings=1, prep=4, cook=12,
 ing=[("chickpea_pasta_dry",85,"~3 oz dry"),("kidney_beans",120,"1/2 cup, or white beans"),
      ("marinara",150,"2/3 cup"),("cottage_cheese_2",120,"1/2 cup"),("parmesan",20,"3 tbsp"),
      ("spinach",80,"2.5 packed cups"),("olive_oil",10,"2 tsp"),("garlic",8,"2 cloves")],
 steps=["Boil the pasta. Chickpea pasta overcooks fast, so pull it a minute early and reserve a cup of the water.",
        "Blend the cottage cheese completely smooth. Lumps here ruin the sauce.",
        "Fry garlic in oil 30 seconds, add marinara and beans, simmer 4 minutes, then stir in the blended cottage cheese off the heat.",
        "Toss with the pasta, spinach and a splash of pasta water. Finish with parmesan."],
 storage="3 days. The sauce thickens, loosen with water.",
 prep_notes="Blended cottage cheese as a cream sauce base is the highest-value technique in the catalog. It replaces cream at a fifth of the calories and adds 14 g of protein.",
 subs=["Regular GF pasta if chickpea pasta is out of budget, at the cost of ~18 g protein and 10 g fiber.",
       "Ricotta instead of cottage cheese, milder and slightly higher fat."],
 variations=["Add chili flakes and lemon zest.","Vodka-sauce style: add a spoon of tomato paste and more parmesan."],
 manual_tags=["HIGH FIBER","QUICK"]),

# ============================== SNACKS ==============================
dict(id="S-17", cat="Snack", name="Single-Serve Protein Brownie",
 servings=1, prep=3, cook=1,
 ing=[("gf_oat_flour",20,"3 tbsp"),("cocoa_powder",10,"2 tbsp"),("whey_isolate",20,"2/3 scoop chocolate"),
      ("milk_skim",70,"1/3 cup"),("maple_syrup",12,"2 tsp"),("choc_chips_mini",10,"1 tbsp")],
 steps=["Mix the dry ingredients in a mug first so the cocoa does not clump.",
        "Stir in milk and syrup until it is a thick batter.",
        "Fold in the chips. Microwave 50 to 60 seconds.",
        "Stop while the centre still looks slightly underdone. Overcooked protein cake is rubber."],
 storage="Eat immediately.", prep_notes="",
 subs=["Casein makes it fudgier, whey makes it cakier.","Sugar-free syrup drops ~40 kcal."],
 variations=["Add 10 g peanut butter to the centre before microwaving."],
 manual_tags=["QUICK","SWEET"]),

dict(id="S-18", cat="Snack", name="Frozen Yogurt Bark Bites",
 servings=4, prep=10, cook=0,
 ing=[("greek_yogurt_nonfat",500,"2 cups"),("whey_isolate",30,"1 scoop vanilla"),("mixed_berries_frozen",200,"1.5 cups"),
      ("honey",30,"1.5 tbsp"),("almonds",40,"~32, chopped")],
 steps=["Whisk yogurt, protein powder and honey until smooth.",
        "Spread 1 cm thick on a parchment-lined tray.",
        "Press berries and chopped almonds into the surface.",
        "Freeze 4 hours, then break into pieces and store in a bag."],
 storage="2 months frozen. Eat straight from the freezer, it softens fast.",
 prep_notes="One tray covers snacks for most of a week.",
 subs=["Any frozen fruit.","Skyr for a firmer set."],
 variations=["Chocolate: 15 g cocoa powder into the yogurt base."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","SWEET"]),

dict(id="S-19", cat="Snack", name="Smashed Chickpea Salad on Rice Cakes",
 servings=1, prep=6, cook=0,
 ing=[("chickpeas",160,"3/4 cup"),("greek_yogurt_nonfat",50,"3 tbsp"),("rice_cake",22,"2 cakes"),
      ("lemon_juice",10,"2 tsp"),("onion",25,"2 tbsp diced"),("spice_generic",2,"celery salt, pepper, dill")],
 steps=["Smash the chickpeas with a fork until roughly half are broken. Texture matters, do not puree.",
        "Fold in yogurt, lemon, onion and seasoning.",
        "Pile onto rice cakes."],
 storage="Salad keeps 3 days. Assemble at the last minute or the cakes go soft.",
 prep_notes="Tastes remarkably like tuna salad and costs a fraction of it.",
 subs=["White beans work.","GF bread instead of rice cakes for more calories."],
 variations=["Add curry powder and raisins for a coronation version."],
 manual_tags=["QUICK","BUDGET FRIENDLY","HIGH FIBER"]),

dict(id="S-20", cat="Snack", name="Whipped Cottage Cheese with Berries and Honey",
 servings=1, prep=3, cook=0,
 ing=[("cottage_cheese_2",200,"scant 1 cup"),("mixed_berries_frozen",100,"3/4 cup"),("honey",12,"2 tsp"),
      ("pumpkin_seeds",12,"1.5 tbsp")],
 steps=["Blend or food-process the cottage cheese for 30 seconds until it becomes a smooth cream.",
        "Thaw the berries 40 seconds in the microwave so they release syrup.",
        "Spoon the berries over, drizzle honey, top with seeds."],
 storage="Whipped cottage cheese keeps 3 days. Whip a whole tub at once.",
 prep_notes="If the curd texture is the barrier, this removes it entirely.",
 subs=["Any fruit.","Skyr if cottage cheese is out."],
 variations=["Savory: skip fruit and honey, use olive oil, tomato, black pepper and chili flakes."],
 manual_tags=["QUICK","HIGH SATIETY"]),

dict(id="S-21", cat="Snack", name="Dark Chocolate Almond Clusters",
 servings=6, prep=8, cook=2,
 ing=[("dark_chocolate_70",100,"~3.5 oz"),("almonds",120,"~1 cup"),("pumpkin_seeds",40,"1/3 cup"),
      ("salt",1,"flaky, to finish")],
 steps=["Toast the almonds and seeds in a dry pan 4 minutes until they smell nutty.",
        "Melt the chocolate in 20-second microwave bursts, stirring between each.",
        "Stir the nuts through, spoon 6 mounds onto parchment, sprinkle salt.",
        "Set in the fridge 20 minutes."],
 storage="2 weeks in an airtight container, refrigerated.",
 prep_notes="Portion them the day you make them. This is not a food you should eat from the container.",
 subs=["Walnuts or cashews.","85% chocolate for less sugar."],
 variations=["Add 30 g raisins for a fruit-and-nut version."],
 manual_tags=["MEAL PREP","HIGH CALORIE","SWEET"]),

dict(id="S-22", cat="Snack", name="No-Bake Peanut Butter Oat Bars",
 servings=8, prep=12, cook=0,
 ing=[("oats_gf_dry",160,"2 cups dry"),("peanut_butter",160,"2/3 cup"),("honey",100,"1/3 cup"),
      ("whey_isolate",60,"2 scoops vanilla"),("flax_ground",30,"4 tbsp"),("choc_chips_mini",40,"1/4 cup"),
      ("milk_skim",60,"1/4 cup")],
 steps=["Warm the peanut butter and honey together 40 seconds so they pour.",
        "Mix everything in a bowl. It will be stiff. Add the milk a splash at a time until it just holds together.",
        "Press hard into a lined 8x8 pan. Press harder than you think, that is what stops them crumbling.",
        "Chill 2 hours, cut into 8 bars."],
 storage="1 week refrigerated, 3 months frozen. Wrap individually.",
 prep_notes="Replaces the protein bars you buy at work at roughly a quarter of the cost, with double the calories.",
 subs=["Almond butter or sunflower butter.","Dates blended in instead of honey."],
 variations=["Add 20 g cocoa powder plus 30 ml extra milk for a chocolate version."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","BUDGET FRIENDLY","HIGH CALORIE"]),

dict(id="S-23", cat="Snack", name="Chili Lime Roasted Edamame",
 servings=2, prep=3, cook=20,
 ing=[("edamame_shelled",300,"2 cups"),("olive_oil",10,"2 tsp"),("lemon_juice",15,"1 tbsp lime"),
      ("spice_generic",3,"chili powder, garlic powder, salt")],
 steps=["Pat the edamame completely dry. Wet beans steam instead of roasting.",
        "Toss with oil and spices, spread on a tray.",
        "Roast at 400F for 18 to 20 minutes, shaking once, until they start to split.",
        "Hit with lime juice out of the oven."],
 storage="3 days at room temperature in an open container. Sealed, they go soft.",
 prep_notes="", subs=["Air fryer, 380F, 12 minutes.","Chickpeas work identically."],
 variations=["Everything-bagel seasoning, checking it is GF."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="S-24", cat="Snack", name="Greek Yogurt Ranch with Raw Vegetables",
 servings=1, prep=5, cook=0,
 ing=[("greek_yogurt_nonfat",170,"3/4 cup"),("carrot",100,"2 medium"),("cucumber",100,"1/3 cucumber"),
      ("bell_pepper",100,"1 pepper"),("olive_oil",7,"1/2 tbsp"),("lemon_juice",10,"2 tsp"),
      ("spice_generic",3,"dill, garlic powder, onion powder, salt")],
 steps=["Whisk yogurt, oil, lemon and seasoning. Let it sit 10 minutes for the dried herbs to hydrate.",
        "Cut the vegetables into sticks.","Dip."],
 storage="Dressing keeps 5 days. Cut vegetables keep 4 days in water.",
 prep_notes="Cut a week of vegetable sticks on Sunday and store them submerged in water in a jar. They stay crisp.",
 subs=["Kefir makes it pourable as a salad dressing."],
 variations=["Add sriracha or chipotle for a spicy version."],
 manual_tags=["LOW CALORIE","HIGH SATIETY","QUICK"]),

dict(id="S-25", cat="Snack", name="Apple with Almond Butter and Cinnamon",
 servings=1, prep=2, cook=0,
 ing=[("apple",200,"1 large"),("almond_butter",32,"2 tbsp"),("cinnamon",2,"1/2 tsp"),("hemp_hearts",10,"1 tbsp")],
 steps=["Slice the apple into rounds.","Spread almond butter, dust with cinnamon, scatter hemp hearts."],
 storage="Eat fresh.", prep_notes="Portable, no refrigeration for a few hours.",
 subs=["Peanut butter is half the price and nutritionally close."],
 variations=["Pear instead of apple."],
 manual_tags=["QUICK","NO-COOK"]),

dict(id="S-26", cat="Snack", name="Protein Frozen Yogurt",
 servings=1, prep=5, cook=0,
 ing=[("greek_yogurt_nonfat",250,"1 cup"),("whey_isolate",25,"3/4 scoop"),("mixed_berries_frozen",150,"1 cup"),
      ("honey",10,"1.5 tsp")],
 steps=["Blend everything on high. It will be thick and will need scraping down twice.",
        "Eat immediately for soft-serve texture, or freeze 30 minutes for a firmer scoop.",
        "If it freezes solid, let it sit 10 minutes before eating."],
 storage="Best fresh. Freezes hard.", prep_notes="",
 subs=["Frozen banana instead of berries makes it creamier and sweeter."],
 variations=["Chocolate: cocoa powder and a splash of milk."],
 manual_tags=["QUICK","SWEET","HIGH SATIETY"]),

dict(id="S-27", cat="Snack", name="Cottage Cheese Queso with Tortilla Chips",
 servings=1, prep=4, cook=3,
 ing=[("cottage_cheese_2",180,"3/4 cup"),("cheddar",40,"1/3 cup shredded"),("salsa",60,"1/4 cup"),
      ("corn_tortilla",52,"2 tortillas, cut and baked"),("pickled_jalapeno",20,"2 tbsp"),
      ("spice_generic",2,"cumin, chili")],
 steps=["Cut the tortillas into wedges, spray with oil, bake at 400F for 8 minutes until crisp.",
        "Blend cottage cheese completely smooth.","Microwave with cheddar in 30-second bursts, stirring, until melted.",
        "Stir in salsa, spices and jalapeno."],
 storage="Queso keeps 3 days. Reheat gently, it splits on high heat.",
 prep_notes="", subs=["Store-bought corn chips, checking the bag says gluten-free."],
 variations=["Add black beans to make it a meal."],
 manual_tags=["QUICK","SAVORY"]),

dict(id="S-28", cat="Snack", name="Chocolate Peanut Butter Protein Pudding",
 servings=1, prep=4, cook=0,
 ing=[("greek_yogurt_nonfat",200,"3/4 cup"),("casein_powder",25,"3/4 scoop chocolate"),("pb_powder",15,"2.5 tbsp"),
      ("cocoa_powder",5,"1 tbsp"),("milk_skim",50,"3 tbsp"),("choc_chips_mini",8,"2 tsp")],
 steps=["Whisk the powders into the milk first to make a paste with no lumps.",
        "Fold that into the yogurt.",
        "Rest 10 minutes in the fridge. Casein thickens over time and this is the difference between pudding and yogurt.",
        "Top with chips."],
 storage="3 days. Thickens further.", prep_notes="Good pre-sleep feeding: slow protein, high leucine.",
 subs=["Whey works but stays thin. Casein is the point here."],
 variations=["Add 15 g real peanut butter for calories and texture."],
 manual_tags=["LEUCINE PRIORITY","SWEET","PRE-SLEEP"]),

dict(id="S-29", cat="Snack", name="Pumpkin Seed and Cheese Plate",
 servings=1, prep=3, cook=0,
 ing=[("cheddar",50,"~1.75 oz"),("pumpkin_seeds",30,"1/4 cup"),("apple",120,"1 small"),
      ("rice_cake",22,"2 cakes")],
 steps=["Slice the cheese and apple.","Assemble with the seeds and rice cakes."],
 storage="Portable for a work shift without refrigeration for a few hours.",
 prep_notes="Zinc, magnesium and calcium in one snack, three of the ones I run short on.",
 subs=["Any hard cheese.","Almonds instead of pumpkin seeds, though seeds are better for zinc."],
 variations=["Add 30 g dark chocolate."],
 manual_tags=["NO-COOK","QUICK","HIGH CALORIE"]),

dict(id="S-30", cat="Snack", name="Banana Protein Soft Serve",
 servings=1, prep=4, cook=0,
 ing=[("banana",240,"2 large, frozen in chunks"),("whey_isolate",25,"3/4 scoop"),("milk_skim",50,"3 tbsp"),
      ("peanut_butter",16,"1 tbsp")],
 steps=["Freeze sliced ripe bananas at least 4 hours ahead. This does not work with fresh banana.",
        "Blend the frozen banana with the milk, stopping to scrape down. It goes through a crumbly stage before it turns creamy. Keep going.",
        "Add protein powder and peanut butter, blend 20 more seconds."],
 storage="Eat immediately.",
 prep_notes="Keep a bag of frozen banana chunks permanently. It is also the base for half the shakes in the D section.",
 subs=["Frozen mango works, slightly less creamy."],
 variations=["Add cocoa powder for chocolate."],
 manual_tags=["SWEET","QUICK","POST-WORKOUT FRIENDLY"]),

dict(id="S-31", cat="Snack", name="Coconut Chia Pudding Cup",
 servings=1, prep=5, cook=0,
 ing=[("chia",30,"3 tbsp"),("coconut_milk_light",120,"1/2 cup"),("milk_skim",120,"1/2 cup"),
      ("whey_isolate",20,"2/3 scoop vanilla"),("maple_syrup",12,"2 tsp"),("mango_frozen",80,"1/2 cup")],
 steps=["Whisk everything except the mango. Whisk again after 5 minutes, which stops the chia clumping at the bottom.",
        "Refrigerate 4 hours or overnight.",
        "Top with thawed mango."],
 storage="4 days.", prep_notes="Make four jars at once.",
 subs=["All skim milk if coconut milk is not on hand, at ~60 fewer calories."],
 variations=["Chocolate: 8 g cocoa powder and skip the mango."],
 manual_tags=["MEAL PREP","HIGH FIBER","OMEGA-3 RICH"]),

dict(id="S-32", cat="Snack", name="Sriracha Roasted Chickpea Snack Mix",
 servings=3, prep=5, cook=35,
 ing=[("chickpeas",400,"2 cups, drained and dried"),("sriracha",25,"1.5 tbsp"),("olive_oil",14,"1 tbsp"),
      ("pumpkin_seeds",45,"1/3 cup"),("popcorn_popped",20,"2 cups popped"),("spice_generic",3,"garlic powder, smoked paprika")],
 steps=["Dry the chickpeas thoroughly and remove any loose skins. This is the crispness step.",
        "Toss with oil, sriracha and spices. Roast at 400F for 30 to 35 minutes, shaking twice.",
        "Add the pumpkin seeds for the last 6 minutes only.",
        "Cool completely, then mix with popcorn. Popcorn added warm goes chewy."],
 storage="4 days in a paper bag or open container. Airtight makes them soft.",
 prep_notes="", subs=["Any bean.","Skip the popcorn to concentrate the protein."],
 variations=["Sweet version: cinnamon, maple syrup, no sriracha."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY","HIGH FIBER"]),

dict(id="S-33", cat="Snack", name="Egg Salad Cups",
 servings=1, prep=8, cook=10,
 ing=[("egg_whole",200,"4 large, hard-boiled"),("greek_yogurt_nonfat",60,"1/4 cup"),("cucumber",100,"1/3 cucumber"),
      ("spice_generic",2,"mustard powder, paprika, salt, chives"),("rice_cake",11,"1 cake")],
 steps=["Boil eggs 9 minutes, then straight into ice water for 5. That is what makes them peel.",
        "Chop and fold with yogurt and seasoning.",
        "Serve in cucumber boats or on the rice cake."],
 storage="Egg salad 3 days.", prep_notes="Boil a dozen eggs at the start of the week.",
 subs=["Two whole eggs plus four whites cuts fat and raises protein density."],
 variations=["Curried: add curry powder and a little raisin."],
 manual_tags=["MEAL PREP","LOW CALORIE","SAVORY"]),

dict(id="S-34", cat="Snack", name="Ricotta Toast with Honey and Walnuts",
 servings=1, prep=3, cook=2,
 ing=[("gf_bread",70,"2 slices"),("ricotta_ps",120,"1/2 cup"),("honey",15,"2 tsp"),
      ("walnuts",20,"~10 halves"),("cinnamon",1,"pinch")],
 steps=["Toast the bread well. GF bread needs a harder toast than wheat bread to hold a topping.",
        "Spread ricotta thickly.","Drizzle honey, add chopped walnuts and cinnamon."],
 storage="Eat fresh.", prep_notes="",
 subs=["Cottage cheese blended smooth is cheaper and higher protein.",
       "Savory: skip honey, add tomato, olive oil, black pepper."],
 variations=["Add sliced strawberries or fig."],
 manual_tags=["QUICK","SWEET"]),

dict(id="S-35", cat="Snack", name="Zucchini Feta Fritters",
 servings=2, prep=12, cook=10,
 ing=[("zucchini",300,"2 medium, grated"),("egg_whole",100,"2 large"),("feta",60,"~1/2 cup crumbled"),
      ("gf_oat_flour",50,"1/2 cup"),("olive_oil",14,"1 tbsp"),("spice_generic",2,"dill, black pepper"),
      ("greek_yogurt_nonfat",80,"1/3 cup, to serve")],
 steps=["Grate the zucchini, salt it, leave 10 minutes, then squeeze out the water in a towel. Skip this and the fritters fall apart.",
        "Mix with eggs, feta, oat flour and seasoning.",
        "Fry spoonfuls in oil over medium, 3 minutes per side.",
        "Serve with yogurt."],
 storage="3 days. Reheat in a pan, not a microwave.",
 prep_notes="", subs=["Any GF flour.","Cottage cheese instead of feta for more protein and less salt."],
 variations=["Add grated carrot and scallion."],
 manual_tags=["MEAL PREP","SAVORY","LOW CALORIE"]),

dict(id="S-36", cat="Snack", name="Date and Oat Energy Bites",
 servings=6, prep=12, cook=0,
 ing=[("dates_medjool",180,"~8 dates, pitted"),("oats_gf_dry",100,"1.25 cups"),("almonds",80,"2/3 cup"),
      ("whey_isolate",30,"1 scoop"),("cocoa_powder",10,"2 tbsp"),("salt",1,"pinch")],
 steps=["Soak the dates in hot water 10 minutes if they are dry, then drain.",
        "Blitz the almonds and oats in a food processor until they are a coarse meal.",
        "Add dates, protein powder, cocoa and salt. Process until it clumps around the blade.",
        "Roll into 12 balls, two per serving."],
 storage="2 weeks refrigerated, 3 months frozen.",
 prep_notes="Fast carbohydrate plus a little protein. Good 30 minutes before training.",
 subs=["Raisins instead of dates, less sticky."],
 variations=["Coconut version: roll in desiccated coconut."],
 manual_tags=["MEAL PREP","PRE-WORKOUT FRIENDLY","FREEZER FRIENDLY"]),

dict(id="S-37", cat="Snack", name="Cucumber Hummus Boats with Hemp",
 servings=1, prep=5, cook=0,
 ing=[("cucumber",200,"2/3 cucumber"),("hummus",100,"scant 1/2 cup"),("hemp_hearts",20,"2 tbsp"),
      ("cherry_tomatoes",80,"~8"),("lemon_juice",8,"1.5 tsp"),("spice_generic",1,"sumac or paprika")],
 steps=["Halve the cucumber lengthwise and scoop out the seeds with a spoon.",
        "Fill the channel with hummus.",
        "Top with halved tomatoes, hemp hearts, lemon and spice. Cut into lengths."],
 storage="Eat fresh.", prep_notes="Hemp hearts are the best protein-per-gram topping you can keep in a cupboard.",
 subs=["Bell pepper halves instead of cucumber."],
 variations=["Add feta and olives."],
 manual_tags=["NO-COOK","QUICK","LOW CALORIE"]),

dict(id="S-38", cat="Snack", name="Microwave Protein Cheesecake Cup",
 servings=1, prep=4, cook=2,
 ing=[("cottage_cheese_2",150,"2/3 cup"),("egg_whole",50,"1 large"),("whey_isolate",20,"2/3 scoop vanilla"),
      ("gf_oat_flour",15,"2 tbsp"),("honey",12,"2 tsp"),("strawberries",80,"~5 berries"),
      ("vanilla_extract",2,"1/2 tsp")],
 steps=["Blend the cottage cheese, egg, protein powder, oat flour, honey and vanilla until completely smooth.",
        "Pour into a mug or ramekin.","Microwave 90 seconds to 2 minutes. It puffs and then settles.",
        "Chill 20 minutes if you can wait. Top with sliced strawberries."],
 storage="3 days refrigerated. Better cold.", prep_notes="",
 subs=["Ricotta instead of cottage cheese."],
 variations=["Lemon: 2 tsp lemon juice and zest, skip the strawberries."],
 manual_tags=["SWEET","LEUCINE PRIORITY","QUICK"]),

dict(id="S-39", cat="Snack", name="Salted Chocolate Protein Fudge",
 servings=8, prep=10, cook=0,
 ing=[("peanut_butter",160,"2/3 cup"),("casein_powder",60,"2 scoops chocolate"),("cocoa_powder",20,"1/4 cup"),
      ("maple_syrup",60,"3 tbsp"),("coconut_oil",30,"2 tbsp"),("milk_skim",60,"1/4 cup"),("salt",2,"flaky")],
 steps=["Melt the coconut oil and peanut butter together, 40 seconds.",
        "Stir in cocoa, casein, syrup and milk. It will seize into a thick paste. Keep working it.",
        "Press into a lined loaf tin, sprinkle salt.",
        "Freeze 1 hour, cut into 8 squares."],
 storage="Keep frozen or refrigerated, it softens at room temperature. 2 months frozen.",
 prep_notes="Casein specifically, because whey makes this grainy.",
 subs=["Almond butter.","Sugar-free syrup drops ~25 kcal per square."],
 variations=["Press chopped almonds into the top before freezing."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","HIGH CALORIE","PRE-SLEEP"]),

dict(id="S-40", cat="Snack", name="Loaded Sweet Potato Skins",
 servings=1, prep=5, cook=45,
 ing=[("sweet_potato",300,"1 large"),("cottage_cheese_2",150,"2/3 cup"),("black_beans",100,"1/2 cup"),
      ("cheddar",30,"1/4 cup"),("salsa",50,"3 tbsp"),("spice_generic",2,"cumin, chili")],
 steps=["Bake the sweet potato at 400F for 45 minutes, or microwave 8 minutes if you are short on time.",
        "Split it, fluff the flesh with a fork.",
        "Blend the cottage cheese smooth, mix with the spices, and spoon it in.",
        "Top with beans, cheddar and salsa. Back under the broiler 3 minutes."],
 storage="Bake potatoes in batches, they keep 4 days.",
 prep_notes="One of the better vitamin A sources in the whole catalog.",
 subs=["Regular potato.","Greek yogurt instead of cottage cheese."],
 variations=["Add a fried egg."],
 manual_tags=["HIGH FIBER","HIGH SATIETY","MEAL PREP"]),

dict(id="S-41", cat="Snack", name="Savory Yogurt Bowl with Chickpeas and Tahini",
 servings=1, prep=5, cook=0,
 ing=[("greek_yogurt_nonfat",200,"3/4 cup"),("chickpeas",120,"1/2 cup"),("tahini",15,"1 tbsp"),
      ("lemon_juice",10,"2 tsp"),("cucumber",80,"1/3 cucumber"),("olive_oil",7,"1/2 tbsp"),
      ("spice_generic",2,"za'atar or cumin, salt")],
 steps=["Whisk the tahini and lemon into the yogurt with a splash of water until pourable.",
        "Spread in a shallow bowl.","Top with chickpeas, diced cucumber, olive oil and spice."],
 storage="Eat fresh.", prep_notes="A savory yogurt bowl is a much easier way to eat 200 g of yogurt than a sweet one, if sweet snacks are getting old.",
 subs=["Hummus instead of tahini."],
 variations=["Add harissa or chili crisp."],
 manual_tags=["NO-COOK","QUICK","HIGH SATIETY"]),

dict(id="S-42", cat="Snack", name="Protein Popcorn with Parmesan and Yeast",
 servings=1, prep=2, cook=3,
 ing=[("popcorn_popped",30,"3 cups popped"),("parmesan",25,"1/4 cup grated"),("nutritional_yeast",10,"2 tbsp"),
      ("olive_oil",10,"2 tsp"),("spice_generic",2,"garlic powder, black pepper")],
 steps=["Pop the corn on the stove in a covered pot, or air-pop it.",
        "Toss immediately with the oil while hot so the powders stick.",
        "Add parmesan, yeast and seasoning, tossing constantly."],
 storage="Eat fresh.", prep_notes="Nutritional yeast is a genuine B12 source, which matters on a vegetarian diet.",
 subs=["Skip the parmesan for a vegan version, double the yeast."],
 variations=["Chili lime, or cinnamon and a little sugar."],
 manual_tags=["QUICK","LOW CALORIE","SAVORY"]),

# ============================== DRINKS ==============================
dict(id="D-15", cat="Drink", name="Salted Caramel Cold Brew Protein",
 servings=1, prep=3, cook=0,
 ing=[("cold_brew",240,"1 cup"),("milk_skim",120,"1/2 cup"),("whey_isolate",30,"1 scoop vanilla"),
      ("maple_syrup",12,"2 tsp"),("salt",1,"pinch")],
 steps=["Shake the protein powder with the milk first. Adding powder to cold brew directly gives you clumps.",
        "Pour over ice, add cold brew, syrup and salt.","Stir."],
 storage="Drink fresh.", prep_notes="Caffeine is real. If you train in the evening this is a morning drink only.",
 subs=["Sugar-free syrup drops 40 kcal."], variations=["Blend with ice for a frappe."],
 manual_tags=["QUICK","LOW CALORIE","PRE-WORKOUT FRIENDLY"]),

dict(id="D-16", cat="Drink", name="Taro-Style Protein Boba",
 servings=1, prep=5, cook=8,
 ing=[("tapioca_pearls_dry",30,"1/4 cup dry"),("milk_2",250,"1 cup"),("whey_isolate",30,"1 scoop vanilla"),
      ("sweet_potato",80,"purple if available, cooked"),("brown_sugar",10,"2 tsp"),("vanilla_extract",2,"1/2 tsp")],
 steps=["Boil the pearls 5 minutes, rest covered 5 minutes off the heat, drain and toss with the brown sugar.",
        "Blend the cooked sweet potato with the milk until completely smooth.",
        "Shake in the protein powder and vanilla.","Pour over the pearls and ice."],
 storage="Pearls must be eaten the day they are cooked. They turn to cement in the fridge.",
 prep_notes="To modify: pearls are pure carbohydrate, roughly 110 kcal per 30 g dry, so cut them for a lower-carb version. Sweetness comes from the brown sugar, cut it to zero and the drink still works. Protein scales with the scoop. Use skim milk for lower calories, whole for higher.",
 subs=["Skip the sweet potato for a plain vanilla milk tea version with black tea instead."],
 variations=["Brown sugar version: skip the sweet potato, double the brown sugar, add a shot of espresso."],
 manual_tags=["SWEET","POST-WORKOUT FRIENDLY"]),

dict(id="D-17", cat="Drink", name="Banana Bread Protein Shake",
 servings=1, prep=3, cook=0,
 ing=[("banana",120,"1 large"),("oats_gf_dry",30,"1/3 cup"),("milk_2",300,"1.25 cups"),
      ("whey_isolate",30,"1 scoop vanilla"),("walnuts",15,"~7 halves"),("cinnamon",2,"1/2 tsp")],
 steps=["Blend the oats alone for 15 seconds first to break them down.",
        "Add everything else and blend 45 seconds."],
 storage="Drink fresh. Separates within an hour.", prep_notes="",
 subs=["Frozen banana makes it thicker and colder."],
 variations=["Add 15 g cocoa for chocolate banana bread."],
 manual_tags=["HIGH CALORIE","POST-WORKOUT FRIENDLY"]),

dict(id="D-18", cat="Drink", name="Blueberry Muffin Protein Shake",
 servings=1, prep=3, cook=0,
 ing=[("blueberries",120,"3/4 cup, frozen"),("greek_yogurt_nonfat",120,"1/2 cup"),("milk_skim",250,"1 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("oats_gf_dry",25,"1/4 cup"),("cinnamon",2,"1/2 tsp")],
 steps=["Blend the oats dry for 15 seconds.","Add the rest and blend until smooth."],
 storage="Drink fresh.", prep_notes="", subs=["Any berry."],
 variations=["Add lemon zest, which makes it taste far more like a muffin than it should."],
 manual_tags=["HIGH SATIETY","POST-WORKOUT FRIENDLY"]),

dict(id="D-19", cat="Drink", name="Orange Creamsicle Protein Shake",
 servings=1, prep=3, cook=0,
 ing=[("orange",200,"2 medium, peeled"),("greek_yogurt_nonfat",120,"1/2 cup"),("milk_skim",200,"3/4 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("vanilla_extract",3,"3/4 tsp")],
 steps=["Blend everything with 4 or 5 ice cubes for 45 seconds."],
 storage="Drink fresh.", prep_notes="Vitamin C plus a high-protein base. Good alongside an iron-containing meal.",
 subs=["Orange juice instead of whole oranges, at the cost of the fiber."],
 variations=["Add frozen mango."],
 manual_tags=["LOW CALORIE","QUICK"]),

dict(id="D-20", cat="Drink", name="Mango Lassi Protein Drink",
 servings=1, prep=3, cook=0,
 ing=[("mango_frozen",180,"1.25 cups"),("greek_yogurt_nonfat",200,"3/4 cup"),("milk_2",200,"3/4 cup"),
      ("whey_isolate",25,"3/4 scoop vanilla"),("honey",12,"2 tsp"),("spice_generic",1,"cardamom, pinch")],
 steps=["Blend everything until completely smooth, about 60 seconds for frozen mango."],
 storage="Drink fresh.", prep_notes="",
 subs=["Kefir instead of milk adds live cultures."],
 variations=["Rose water instead of cardamom."],
 manual_tags=["HIGH SATIETY","SWEET"]),

dict(id="D-21", cat="Drink", name="Cookies and Cream Casein Thickshake",
 servings=1, prep=3, cook=0,
 ing=[("casein_powder",35,"1 scoop vanilla"),("milk_2",300,"1.25 cups"),("greek_yogurt_nonfat",100,"scant 1/2 cup"),
      ("cocoa_powder",6,"1 tbsp"),("choc_chips_mini",15,"1.5 tbsp"),("vanilla_extract",2,"1/2 tsp")],
 steps=["Blend the casein, milk, yogurt and vanilla until thick. Casein thickens as it hydrates, so give it 30 seconds.",
        "Pulse in the cocoa and chips so the chips stay in pieces."],
 storage="Drink fresh or refrigerate up to 12 hours, it thickens further.",
 prep_notes="Casein before bed raises overnight muscle protein synthesis. This is the palatable version of that.",
 subs=["Whey works but you lose the thickness and the slow release."],
 variations=["Blend with ice for a frozen version."],
 manual_tags=["LEUCINE PRIORITY","PRE-SLEEP","SWEET"]),

dict(id="D-22", cat="Drink", name="Espresso Protein Frappe",
 servings=1, prep=4, cook=0,
 ing=[("cold_brew",180,"3/4 cup"),("milk_2",180,"3/4 cup"),("whey_isolate",30,"1 scoop"),
      ("cocoa_powder",5,"1 tbsp"),("sugar_free_syrup",20,"1.5 tbsp")],
 steps=["Blend everything with a full cup of ice for 45 seconds until it is slushy."],
 storage="Drink immediately, it separates.", prep_notes="",
 subs=["Regular syrup or honey adds ~50 kcal."], variations=["Add a banana for a thicker, higher-calorie version."],
 manual_tags=["LOW CALORIE","PRE-WORKOUT FRIENDLY","QUICK"]),

dict(id="D-23", cat="Drink", name="Mint Chocolate Protein Shake",
 servings=1, prep=3, cook=0,
 ing=[("whey_isolate",30,"1 scoop chocolate"),("milk_2",300,"1.25 cups"),("spinach",40,"1.5 packed cups"),
      ("cocoa_powder",8,"1.5 tbsp"),("vanilla_extract",2,"1/2 tsp, or peppermint extract"),
      ("choc_chips_mini",12,"1 tbsp")],
 steps=["Blend the spinach with the milk first until there is no visible green fleck.",
        "Add everything else and blend 30 seconds. The spinach is invisible against the cocoa and you will not taste it."],
 storage="Drink fresh.", prep_notes="Easiest way to get a serving of greens into someone who does not eat greens.",
 subs=["Peppermint extract is the authentic version, a quarter teaspoon, no more."],
 variations=["Add avocado for a thicker, higher-fat version."],
 manual_tags=["QUICK","HIGH MICRONUTRIENT DENSITY"]),

dict(id="D-24", cat="Drink", name="Pineapple Coconut Protein Cooler",
 servings=1, prep=3, cook=0,
 ing=[("pineapple",200,"1.25 cups"),("coconut_milk_light",100,"scant 1/2 cup"),("whey_isolate",30,"1 scoop vanilla"),
      ("lemon_juice",10,"2 tsp lime"),("milk_skim",120,"1/2 cup")],
 steps=["Blend with ice until smooth."],
 storage="Drink fresh.", prep_notes="",
 subs=["Frozen pineapple, then skip the ice."],
 variations=["Add mint and cucumber for a lighter version."],
 manual_tags=["QUICK","POST-WORKOUT FRIENDLY"]),

dict(id="D-25", cat="Drink", name="Protein Chai Latte",
 servings=1, prep=4, cook=3,
 ing=[("black_tea_brewed",150,"2/3 cup, brewed strong"),("milk_2",250,"1 cup"),("whey_isolate",30,"1 scoop vanilla"),
      ("honey",12,"2 tsp"),("cinnamon",2,"1/2 tsp"),("spice_generic",2,"cardamom, ginger, clove")],
 steps=["Simmer the milk with the spices 3 minutes, do not boil.",
        "Brew the tea strong and combine.",
        "Cool it to drinkable temperature before the protein powder goes in. Hot liquid denatures and clumps whey.",
        "Whisk in the protein and honey."],
 storage="Drink fresh.", prep_notes="The cooling step is not optional if you want it smooth.",
 subs=["Iced version avoids the problem entirely."],
 variations=["Dirty chai: add a shot of espresso."],
 manual_tags=["QUICK"]),

dict(id="D-26", cat="Drink", name="Tart Berry Recovery Shake",
 servings=1, prep=3, cook=0,
 ing=[("mixed_berries_frozen",200,"1.5 cups"),("raspberries",60,"1/2 cup"),("whey_isolate",30,"1 scoop"),
      ("milk_skim",250,"1 cup"),("honey",10,"1.5 tsp"),("flax_ground",10,"1.5 tbsp")],
 steps=["Blend everything for 60 seconds."],
 storage="Drink fresh.", prep_notes="Tart cherry and berry polyphenols have modest evidence for reducing perceived soreness. Modest, not dramatic.",
 subs=["Any frozen fruit blend."], variations=["Add beetroot for a nitrate boost before training."],
 manual_tags=["POST-WORKOUT FRIENDLY","HIGH FIBER"]),

dict(id="D-27", cat="Drink", name="Almond Butter Date Shake",
 servings=1, prep=3, cook=0,
 ing=[("dates_medjool",60,"3 dates, pitted"),("almond_butter",32,"2 tbsp"),("milk_whole",300,"1.25 cups"),
      ("whey_isolate",30,"1 scoop vanilla"),("cinnamon",2,"1/2 tsp"),("salt",1,"pinch")],
 steps=["Soak the dates in hot water 5 minutes if they are firm.",
        "Blend everything for 60 seconds until no date fragments remain."],
 storage="Drink fresh.", prep_notes="Roughly 700 calories in a glass. This is the tool for a day you cannot eat enough.",
 subs=["Peanut butter, and skim milk to cut ~150 kcal."],
 variations=["Add a banana and 30 g oats to push it past 900."],
 manual_tags=["HIGH CALORIE","TWO-MEAL-DAY FRIENDLY"]),

dict(id="D-28", cat="Drink", name="Vanilla Cinnamon Casein Night Shake",
 servings=1, prep=2, cook=0,
 ing=[("casein_powder",35,"1 scoop vanilla"),("milk_2",300,"1.25 cups"),("cinnamon",3,"3/4 tsp"),
      ("peanut_butter",16,"1 tbsp"),("vanilla_extract",2,"1/2 tsp")],
 steps=["Shake or blend everything.","Drink 30 to 60 minutes before sleep."],
 storage="Drink fresh.", prep_notes="Roughly 40 g of slow-digesting protein with over 3 g leucine, which is the dose that matters overnight.",
 subs=["Greek yogurt blended with milk if you do not own casein."],
 variations=["Add cocoa."],
 manual_tags=["LEUCINE PRIORITY","PRE-SLEEP","QUICK"]),

dict(id="D-29", cat="Drink", name="Kefir Berry Probiotic Smoothie",
 servings=1, prep=3, cook=0,
 ing=[("kefir_plain",300,"1.25 cups"),("mixed_berries_frozen",150,"1 cup"),("whey_isolate",25,"3/4 scoop"),
      ("honey",12,"2 tsp"),("chia",10,"scant 1 tbsp")],
 steps=["Blend for 45 seconds. Let it stand 5 minutes so the chia hydrates."],
 storage="Drink fresh.", prep_notes="Live cultures are worth prioritizing given celiac and ongoing gut repair.",
 subs=["Plain kefir only. Flavoured kefir is sugar water with cultures in it."],
 variations=["Add spinach."],
 manual_tags=["HIGH FIBER","QUICK"]),

dict(id="D-30", cat="Drink", name="The 1000 Gainer",
 servings=1, prep=4, cook=0,
 ing=[("oats_gf_dry",60,"3/4 cup"),("banana",120,"1 large"),("peanut_butter",48,"3 tbsp"),
      ("whey_isolate",40,"1.3 scoops"),("milk_whole",400,"1.7 cups"),("honey",20,"1 tbsp"),
      ("cocoa_powder",8,"1.5 tbsp")],
 steps=["Blend the oats dry for 20 seconds.",
        "Add everything else and blend 60 seconds. It will be thick. Add milk to thin it if you cannot drink it.",
        "Sip it over 20 minutes rather than forcing it down in one go."],
 storage="Drink fresh.", prep_notes="Roughly a third of a day's calories in one glass. Use it on days when work runs long, not as a daily habit, because liquid calories displace whole food and the micronutrients that come with it.",
 subs=["Skim milk cuts ~140 kcal.","Half the peanut butter cuts ~180."],
 variations=["Add 30 g of dates for another 80 kcal of fast carbs."],
 manual_tags=["HIGH CALORIE","TWO-MEAL-DAY FRIENDLY","POST-WORKOUT FRIENDLY"]),

dict(id="D-31", cat="Drink", name="Clear Protein Refresher",
 servings=1, prep=2, cook=0,
 ing=[("whey_isolate",30,"1 scoop unflavoured or fruit"),("lemon_juice",20,"4 tsp"),
      ("sugar_free_syrup",15,"1 tbsp"),("raspberries",40,"1/3 cup, muddled")],
 steps=["Muddle the raspberries in the bottom of a shaker.",
        "Add 400 ml cold water, the lemon juice and syrup.",
        "Add the protein powder last and shake hard for 20 seconds. It will foam; let it settle a minute."],
 storage="Drink fresh.", prep_notes="Roughly 25 g of protein for under 160 calories. Useful in a deficit or when you are already full.",
 subs=["Clear whey isolate products mix better for this but cost more."],
 variations=["Add mint and cucumber."],
 manual_tags=["LOW CALORIE","LEUCINE PRIORITY","QUICK"]),

dict(id="D-32", cat="Drink", name="Green Apple Spinach Protein Smoothie",
 servings=1, prep=4, cook=0,
 ing=[("apple",180,"1 large, green"),("spinach",80,"2.5 packed cups"),("kale",30,"1 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("milk_skim",250,"1 cup"),("lemon_juice",15,"1 tbsp"),
      ("hemp_hearts",15,"1.5 tbsp")],
 steps=["Blend the greens with the milk and lemon first until smooth.","Add everything else and blend again."],
 storage="Drink fresh.", prep_notes="Vitamin K, folate and vitamin C in a form you will actually finish.",
 subs=["Frozen spinach cubes work and are cheaper."],
 variations=["Add ginger and half a frozen banana."],
 manual_tags=["HIGH MICRONUTRIENT DENSITY","HIGH FIBER"]),

dict(id="D-33", cat="Drink", name="Strawberry Banana Classic",
 servings=1, prep=3, cook=0,
 ing=[("strawberries",150,"~10 berries, frozen"),("banana",100,"1 medium"),("whey_isolate",30,"1 scoop vanilla"),
      ("milk_skim",250,"1 cup"),("greek_yogurt_nonfat",100,"scant 1/2 cup")],
 steps=["Blend everything for 45 seconds."],
 storage="Drink fresh.", prep_notes="The default. Keep frozen strawberries and banana chunks in the freezer permanently.",
 subs=["Any berry."], variations=["Add 20 g oats for more calories and staying power."],
 manual_tags=["QUICK","POST-WORKOUT FRIENDLY","BUDGET FRIENDLY"]),

dict(id="D-34", cat="Drink", name="Protein Horchata",
 servings=1, prep=4, cook=0,
 ing=[("rice_white_cooked",120,"generous 1/2 cup, cooked"),("milk_2",300,"1.25 cups"),
      ("whey_isolate",30,"1 scoop vanilla"),("cinnamon",3,"3/4 tsp"),("brown_sugar",12,"2 tsp"),
      ("vanilla_extract",3,"3/4 tsp")],
 steps=["Blend the cooked rice with the milk on high for a full minute until no grain texture remains.",
        "Strain through a fine sieve if you want it silky, or skip that and keep the fiber.",
        "Whisk in protein powder, cinnamon, sugar and vanilla. Serve over ice."],
 storage="2 days refrigerated. Shake before drinking.",
 prep_notes="Uses up leftover rice, which is otherwise the most-wasted meal-prep component.",
 subs=["Cooked oats instead of rice for a creamier texture."],
 variations=["Coffee horchata: add cold brew."],
 manual_tags=["BUDGET FRIENDLY","POST-WORKOUT FRIENDLY"]),

dict(id="D-35", cat="Drink", name="Blended Coffee Cottage Cheese Shake",
 servings=1, prep=4, cook=0,
 ing=[("cottage_cheese_2",200,"scant 1 cup"),("cold_brew",200,"3/4 cup"),("milk_skim",100,"scant 1/2 cup"),
      ("whey_isolate",20,"2/3 scoop"),("maple_syrup",15,"1 tbsp"),("cocoa_powder",5,"1 tbsp")],
 steps=["Blend the cottage cheese with the milk alone for 45 seconds until it is completely smooth cream.",
        "Add everything else and blend 20 seconds more. Serve over ice."],
 storage="Drink fresh.", prep_notes="Cottage cheese is the cheapest way to get 25 g of protein into a drink and it disappears entirely once blended.",
 subs=["Greek yogurt if you cannot get past the idea."],
 variations=["Skip the coffee, add banana and cinnamon."],
 manual_tags=["BUDGET FRIENDLY","LEUCINE PRIORITY"]),

dict(id="D-36", cat="Drink", name="Post-Training Carb and Protein Sipper",
 servings=1, prep=2, cook=0,
 ing=[("whey_isolate",35,"1.2 scoops"),("maple_syrup",40,"2.5 tbsp"),("banana",100,"1 medium"),
      ("salt",1,"1/4 tsp"),("lemon_juice",10,"2 tsp")],
 steps=["Blend the banana with 400 ml water, the syrup, salt and lemon.",
        "Shake in the protein powder last.",
        "Sip during and after training rather than drinking it all at once."],
 storage="Drink within a few hours.",
 prep_notes="For the specific case where you train and then go straight to a work shift, or train twice in a day. On a normal day, food beats this.",
 subs=["Honey instead of maple.","Dextrose powder if you want it faster-absorbing."],
 variations=["Add electrolyte powder on heavy sweat days."],
 manual_tags=["POST-WORKOUT FRIENDLY","LEUCINE PRIORITY","QUICK"]),

dict(id="D-37", cat="Drink", name="Chocolate Almond Butter Shake",
 servings=1, prep=3, cook=0,
 ing=[("almond_butter",32,"2 tbsp"),("cocoa_powder",10,"2 tbsp"),("whey_isolate",30,"1 scoop chocolate"),
      ("milk_2",350,"1.5 cups"),("dates_medjool",40,"2 dates")],
 steps=["Soak the dates 5 minutes in hot water.","Blend everything for 60 seconds."],
 storage="Drink fresh.", prep_notes="",
 subs=["Peanut butter is cheaper and close.","Maple syrup instead of dates."],
 variations=["Add a frozen banana."],
 manual_tags=["HIGH CALORIE","SWEET"]),

dict(id="D-38", cat="Drink", name="Golden Turmeric Protein Milk",
 servings=1, prep=3, cook=4,
 ing=[("milk_2",300,"1.25 cups"),("whey_isolate",30,"1 scoop vanilla"),("honey",15,"2 tsp"),
      ("spice_generic",4,"turmeric, ginger, black pepper, cinnamon"),("coconut_oil",5,"1 tsp")],
 steps=["Warm the milk with the spices and coconut oil for 4 minutes on low. Black pepper is not optional; it is what makes curcumin absorbable at all.",
        "Cool to drinkable temperature.","Whisk in the protein powder and honey."],
 storage="Drink fresh.",
 prep_notes="Curcumin has modest anti-inflammatory evidence at doses far higher than a teaspoon of turmeric provides. Drink it because it tastes good, not because it will do much for CRMO.",
 subs=["Iced version, no heating needed."],
 variations=["Add cardamom."],
 manual_tags=["QUICK"]),

dict(id="D-39", cat="Drink", name="Matcha Coconut Protein Cooler",
 servings=1, prep=4, cook=0,
 ing=[("matcha",4,"2 tsp"),("coconut_milk_light",120,"1/2 cup"),("milk_skim",200,"3/4 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("honey",12,"2 tsp")],
 steps=["Whisk the matcha into 50 ml of warm water until there are no lumps. Sieve it first if it is clumpy.",
        "Shake with the milks, protein powder and honey.","Pour over ice."],
 storage="Drink fresh.", prep_notes="Matcha carries roughly 60-70 mg caffeine per 2 tsp, less than coffee and slower.",
 subs=["All skim milk cuts ~85 kcal."], variations=["Add mint."],
 manual_tags=["QUICK","PRE-WORKOUT FRIENDLY"]),

dict(id="D-40", cat="Drink", name="Thick Berry Smoothie Bowl",
 servings=1, prep=6, cook=0,
 ing=[("mixed_berries_frozen",250,"2 cups"),("greek_yogurt_nonfat",150,"2/3 cup"),("whey_isolate",30,"1 scoop"),
      ("milk_skim",80,"1/3 cup"),("oats_gf_dry",20,"1/4 cup"),("almonds",15,"~12"),("chia",10,"scant 1 tbsp")],
 steps=["Blend the frozen berries, yogurt, protein powder and just enough milk to move the blades. Use as little liquid as you can. That is what makes it a bowl rather than a shake.",
        "Scrape into a bowl.","Top with oats, chopped almonds and chia."],
 storage="Eat immediately.", prep_notes="Eating it with a spoon rather than drinking it makes a real difference to how full it leaves you.",
 subs=["Frozen banana for a creamier base."],
 variations=["Tropical: frozen mango and pineapple, top with coconut."],
 manual_tags=["HIGH SATIETY","HIGH FIBER","POST-WORKOUT FRIENDLY"]),

# ============================== SDA MEAT / FISH ==============================
dict(id="M-11", cat="SDA Meat/Fish", name="Honey Garlic Chicken and Broccoli",
 servings=1, prep=8, cook=14,
 ing=[("chicken_breast",180,"~6 oz raw"),("broccoli_cooked",200,"2 cups"),("rice_white_cooked",250,"1.25 cups"),
      ("honey",20,"1 tbsp"),("soy_sauce_gf",20,"4 tsp tamari"),("garlic",10,"3 cloves"),
      ("olive_oil",10,"2 tsp"),("sriracha",8,"1.5 tsp")],
 steps=["Cut the chicken into strips. Sear in oil over high heat 3 minutes per side, then remove.",
        "Add garlic to the pan for 30 seconds, then honey, tamari and sriracha. Let it bubble and thicken 1 minute.",
        "Return the chicken and toss to coat. Steam the broccoli separately.",
        "Serve over rice."],
 storage="4 days. One of the better reheating meals here.",
 prep_notes="Verify the tamari is certified GF. Standard soy sauce is a wheat product and a celiac hazard.",
 subs=["Chicken thigh adds ~80 kcal and more flavour.","Tofu if you want the vegetarian version."],
 variations=["Add cashews and scallion."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","LEUCINE PRIORITY"]),

dict(id="M-12", cat="SDA Meat/Fish", name="Sheet-Pan Salmon and Sweet Potato",
 servings=1, prep=8, cook=25,
 ing=[("salmon",170,"6 oz fillet"),("sweet_potato",250,"1 large, cubed"),("broccoli_cooked",150,"1.5 cups"),
      ("olive_oil",14,"1 tbsp"),("lemon_juice",15,"1 tbsp"),("garlic",8,"2 cloves"),
      ("spice_generic",3,"paprika, oregano, salt, pepper")],
 steps=["Oven to 425F. Toss the sweet potato in half the oil and spices, roast 15 minutes alone.",
        "Add the broccoli and the salmon, skin side down, to the same tray. Oil and season them.",
        "Roast 10 to 12 more minutes until the salmon flakes at the thickest point.",
        "Lemon over everything at the table."],
 storage="Salmon 2 days, vegetables 4.",
 prep_notes="Roughly 2 g of EPA and DHA in one fillet. Twice a week covers omega-3 without a supplement, which matters more than average with CRMO.",
 subs=["Frozen salmon portions are much cheaper and nutritionally identical. Thaw overnight.",
       "Cod for a leaner, cheaper version, but far less omega-3."],
 variations=["Miso glaze, checking the miso is GF, or maple mustard."],
 manual_tags=["SDA-COMPATIBLE","OMEGA-3 RICH","MEAL PREP","HIGH MICRONUTRIENT DENSITY"]),

dict(id="M-13", cat="SDA Meat/Fish", name="Turkey and Bean Chili",
 servings=3, prep=10, cook=35,
 ing=[("ground_turkey_93",400,"~14 oz raw"),("kidney_beans",300,"1.5 cups"),("black_beans",250,"1.25 cups"),
      ("marinara",300,"1.25 cups"),("onion",120,"1 medium"),("bell_pepper",120,"1 pepper"),
      ("sweet_corn",120,"3/4 cup"),("olive_oil",14,"1 tbsp"),("spice_generic",6,"chili powder, cumin, oregano, smoked paprika"),
      ("cheddar",60,"1/2 cup, to serve")],
 steps=["Brown the turkey hard in the oil, breaking it up. Let it actually brown rather than steam, that is where the flavour is.",
        "Add onion and pepper, cook 6 minutes.",
        "Add spices for 1 minute, then beans, corn, marinara and 250 ml water.",
        "Simmer 25 minutes uncovered until it thickens. Top each bowl with cheddar."],
 storage="5 days refrigerated, 3 months frozen. Genuinely better on day two.",
 prep_notes="Best batch-cook in the catalog. Triple it and freeze in single portions.",
 subs=["Lentils instead of turkey makes it vegetarian at roughly the same protein.",
       "Chicken breast, diced, is leaner."],
 variations=["Add chipotle in adobo, or cocoa powder for depth."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","FREEZER FRIENDLY","HIGH FIBER","HIGH SATIETY"]),

dict(id="M-14", cat="SDA Meat/Fish", name="Greek Chicken Quinoa Bowl",
 servings=1, prep=10, cook=12,
 ing=[("chicken_breast",170,"~6 oz raw"),("quinoa_cooked",250,"1.25 cups"),("cucumber",100,"1/3 cucumber"),
      ("cherry_tomatoes",120,"~12"),("feta",40,"~3 tbsp"),("greek_yogurt_nonfat",80,"1/3 cup"),
      ("olive_oil",14,"1 tbsp"),("lemon_juice",20,"4 tsp"),("spice_generic",3,"oregano, garlic, salt")],
 steps=["Marinate the chicken in half the oil, lemon, oregano and garlic for at least 15 minutes.",
        "Grill or pan-sear 5 to 6 minutes per side, then rest 5 minutes before slicing. Resting is not optional if you want it juicy.",
        "Mix the yogurt with the remaining lemon and a little water for the sauce.",
        "Build over quinoa with cucumber, tomato and feta."],
 storage="4 days. Keep the sauce separate.",
 prep_notes="", subs=["Chickpeas instead of chicken for the vegetarian version.","Rice instead of quinoa, cheaper and nearly identical."],
 variations=["Add olives, red onion and pickled pepper."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","HIGH SATIETY"]),

dict(id="M-15", cat="SDA Meat/Fish", name="Tuna Melt on GF Toast",
 servings=1, prep=6, cook=5,
 ing=[("canned_tuna",140,"1 large can, drained"),("greek_yogurt_nonfat",60,"1/4 cup"),("gf_bread",70,"2 slices"),
      ("cheddar",40,"1/3 cup shredded"),("onion",30,"2 tbsp diced"),("cucumber",40,"pickle, chopped"),
      ("spice_generic",2,"black pepper, dill, mustard powder")],
 steps=["Mix the tuna with yogurt, onion, pickle and seasoning.",
        "Pile onto the bread, top with cheddar.",
        "Broil 4 to 5 minutes until the cheese bubbles and browns at the edges."],
 storage="Tuna mix keeps 2 days.",
 prep_notes="Cheapest complete protein in the store. Light tuna rather than albacore for lower mercury if you eat it often.",
 subs=["Canned salmon has far more omega-3 and calcium if you eat the bones."],
 variations=["Add tomato slices under the cheese."],
 manual_tags=["SDA-COMPATIBLE","QUICK","BUDGET FRIENDLY","LEUCINE PRIORITY"]),

dict(id="M-16", cat="SDA Meat/Fish", name="Sardine and White Bean Salad",
 servings=1, prep=8, cook=0,
 ing=[("sardines",120,"1 tin, drained"),("kidney_beans",200,"1 cup, or cannellini"),("cherry_tomatoes",120,"~12"),
      ("onion",30,"2 tbsp, red, thinly sliced"),("olive_oil",14,"1 tbsp"),("lemon_juice",20,"4 tsp"),
      ("spinach",60,"2 packed cups"),("spice_generic",2,"parsley, black pepper, chili flakes")],
 steps=["Soak the sliced onion in the lemon juice for 5 minutes. It takes the harshness out.",
        "Toss the beans, tomatoes, spinach, oil and lemon together.",
        "Lay the sardines on top whole rather than mixing them in, so they do not disintegrate."],
 storage="Eat fresh. 1 day maximum.",
 prep_notes="Sardines with the bones in are one of the best non-dairy calcium sources available, plus vitamin D and roughly 1.5 g of EPA and DHA. With CRMO and celiac, this is a high-value tin.",
 subs=["Canned salmon if sardines are a step too far texturally.","Any white bean."],
 variations=["Add capers and a boiled egg."],
 manual_tags=["SDA-COMPATIBLE","NO-COOK","OMEGA-3 RICH","HIGH MICRONUTRIENT DENSITY","QUICK"]),
]
