# -*- coding: utf-8 -*-
"""Recipe library, part 6. The fun half.

Cheat meals, healthy desserts, real desserts, five-minute food, and drinks.
Everything here is gluten-free. Everything in the main catalog is vegetarian.
"""

RECIPES_6 = [

# ============================== CHEAT MEALS AND COMFORT FOOD ==============================
dict(id="L-49", cat="Lunch/Dinner", name="Loaded Smash Burger",
 servings=1, prep=6, cook=8,
 ing=[("gf_burger_bun",85,"1 GF bun"),("impossible_patty",226,"2 patties"),("cheddar",50,"2 slices"),
      ("mayo",15,"1 tbsp"),("ketchup",15,"1 tbsp"),("mustard_yellow",8,"1.5 tsp"),
      ("cucumber",30,"pickle slices"),("onion",30,"2 tbsp diced"),("romaine",30,"2 leaves"),
      ("tomato",40,"2 slices")],
 steps=["Get the pan properly hot. Smash burgers need heat you'd normally think is too much.",
        "Ball the patties loosely, drop them in, then smash flat with a spatula and leave them alone for 2 minutes. That crust is the whole point.",
        "Flip, cheese on immediately, 90 seconds more.",
        "Toast the bun cut-side down in the fat. Sauce on both halves, stack, eat over the sink."],
 storage="Eat it hot. There is no version of this that survives a fridge.",
 prep_notes="Roughly 55 g of protein, which is more than most people's actual dinner. If you're going to have a cheat meal, this is a good one to have, because the protein and the calories both land somewhere useful.",
 subs=["Two corn tortillas instead of the bun turns it into smash tacos and saves about $2 a serving.",
       "One patty instead of two drops it to ~620 kcal."],
 variations=["Add a fried egg. Add jalapenos. Add the artichoke dip from S-62, which sounds wrong and is not."],
 manual_tags=["CHEAT MEAL","HIGH CALORIE","HIGH SATIETY","SAVORY"]),

dict(id="L-50", cat="Lunch/Dinner", name="Buffalo Mac and Cheese",
 servings=2, prep=6, cook=16,
 ing=[("chickpea_pasta_dry",170,"~6 oz dry"),("cottage_cheese_2",300,"1.25 cups"),
      ("cheddar",120,"1 cup shredded"),("buffalo_sauce",80,"1/3 cup"),("milk_2",120,"1/2 cup"),
      ("tofu_extrafirm",200,"~2/3 block, shredded"),("green_onion",30,"3 scallions"),
      ("olive_oil",10,"2 tsp"),("spice_generic",3,"garlic powder, paprika, pepper")],
 steps=["Shred the tofu on a box grater, fry it hard in oil for 8 minutes until it looks like pulled chicken. This is the trick that makes buffalo anything work without meat.",
        "Boil the pasta a minute short. Reserve some water.",
        "Blend the cottage cheese with the milk until it's completely smooth, then melt the cheddar into it over low heat.",
        "Stir in the buffalo sauce, fold in the pasta and tofu, loosen with pasta water. Scallions on top."],
 storage="3 days. Add a splash of milk when you reheat it.",
 prep_notes="This is the one where people don't believe you about the cottage cheese. Blend it properly, no lumps, and it makes a sauce that's indistinguishable from a roux at a third of the calories and four times the protein.",
 subs=["Regular GF pasta if chickpea pasta is out of budget. You lose about 18 g protein per serving.",
       "Chicken instead of tofu, same method."],
 variations=["Bake it with GF breadcrumbs on top for 15 minutes at 400F."],
 manual_tags=["CHEAT MEAL","MEAL PREP","HIGH SATIETY","LEUCINE PRIORITY"]),

dict(id="L-51", cat="Lunch/Dinner", name="Philly Cheese Mushroom Bowl",
 servings=1, prep=8, cook=14,
 ing=[("mushrooms",250,"~20, sliced thick"),("bell_pepper",120,"1 pepper"),("onion",100,"1 small"),
      ("mozzarella_ps",80,"3/4 cup"),("rice_white_cooked",200,"1 cup"),
      ("olive_oil",14,"1 tbsp"),("soy_sauce_gf",10,"2 tsp tamari"),
      ("spice_generic",3,"garlic powder, oregano, pepper")],
 steps=["Slice the mushrooms thick, not thin. Thin ones vanish.",
        "Fry them in a hot dry pan first until they release water and it cooks off, about 6 minutes. Then add oil, peppers and onions.",
        "Cook 6 more minutes until everything is browned at the edges. Tamari at the end for depth.",
        "Pile the cheese on, cover for 90 seconds to melt, serve over rice."],
 storage="3 days.",
 prep_notes="Mushrooms cooked properly have a genuinely meaty texture. Cooked badly they're grey and wet, and the difference is entirely whether you drove the water off first.",
 subs=["Sliced seitan is what most vegetarian cheesesteak recipes use. You cannot have it. Mushrooms and tofu are the substitute.",
       "A GF hoagie roll if you want the sandwich version."],
 variations=["Add jalapenos and a swipe of the cottage cheese queso from S-27."],
 manual_tags=["CHEAT MEAL","QUICK","LOW CALORIE"]),

dict(id="L-52", cat="Lunch/Dinner", name="Crispy Tofu Sandwich",
 servings=1, prep=12, cook=12,
 ing=[("tofu_extrafirm",200,"~2/3 block, one thick slab"),("gf_breadcrumbs",50,"1/2 cup"),
      ("egg_whole",50,"1 large"),("cornstarch",20,"2.5 tbsp"),("gf_burger_bun",85,"1 GF bun"),
      ("greek_yogurt_nonfat",40,"3 tbsp"),("sriracha",12,"2.5 tsp"),("coleslaw_mix",80,"1.5 cups"),
      ("cucumber",30,"pickle slices"),("olive_oil",20,"1.5 tbsp"),
      ("spice_generic",3,"paprika, garlic powder, cayenne")],
 steps=["Press the tofu 15 minutes and cut one thick slab, not cubes. You want sandwich-shaped.",
        "Cornstarch, then egg, then seasoned breadcrumbs. Press the crumbs on hard.",
        "Shallow-fry 4 minutes a side until deep golden. Rest it on a rack so the underside stays crisp.",
        "Mix yogurt and sriracha, dress the slaw with half, sauce the bun with the rest."],
 storage="Eat fresh. Crispy things don't reheat.",
 prep_notes="Verify the breadcrumbs are GF. Regular panko is wheat, and it's the single most likely thing to sneak into a fried sandwich.",
 subs=["Air fryer at 400F for 14 minutes, sprayed with oil. Less crisp, ~120 fewer calories.",
       "Crushed GF corn flakes make a better crust than breadcrumbs if you have them."],
 variations=["Nashville hot: toss it in cayenne, paprika and a spoon of the frying oil straight out of the pan."],
 manual_tags=["CHEAT MEAL","HIGH SATIETY","SAVORY"]),

dict(id="L-53", cat="Lunch/Dinner", name="Loaded Chili Cheese Fries",
 servings=1, prep=5, cook=25,
 ing=[("frozen_fries",250,"~half a bag"),("pinto_beans",180,"scant 1 cup"),("cheddar",70,"2/3 cup"),
      ("greek_yogurt_nonfat",60,"1/4 cup"),("salsa",60,"1/4 cup"),("pickled_jalapeno",25,"2.5 tbsp"),
      ("green_onion",25,"2 scallions"),("spice_generic",3,"cumin, chili powder, smoked paprika")],
 steps=["Bake the fries at 425F, 5 minutes longer than the bag says, on a rack if you have one.",
        "Mash half the beans with the spices and a splash of water into a quick chili. Warm it through.",
        "Fries into an ovenproof dish, chili over, cheese over that, back in for 5 minutes.",
        "Yogurt, salsa, jalapenos, scallions."],
 storage="Eat immediately. Obviously.",
 prep_notes="Check the fries bag. Some frozen potato products get a wheat flour coating for crispness, which is exactly the kind of thing that gets a celiac six months of unexplained symptoms.",
 subs=["Cut your own potatoes, toss in oil and cornstarch, bake at 425F for 35 minutes.",
       "Sweet potato fries for more vitamin A."],
 variations=["Add the turkey chili from M-13 instead of the quick bean version."],
 manual_tags=["CHEAT MEAL","HIGH CALORIE","HIGH FIBER"]),

dict(id="L-54", cat="Lunch/Dinner", name="Deep Dish Skillet Pizza",
 servings=2, prep=12, cook=25,
 ing=[("gf_oat_flour",150,"1.5 cups"),("egg_whole",100,"2 large"),("greek_yogurt_nonfat",200,"3/4 cup"),
      ("baking_powder",8,"2 tsp"),("marinara",250,"1 cup"),("mozzarella_ps",200,"1.75 cups"),
      ("ricotta_ps",120,"1/2 cup"),("mushrooms",100,"~8"),("bell_pepper",80,"1/2 pepper"),
      ("olive_oil",14,"1 tbsp"),("parmesan",30,"1/4 cup"),("spice_generic",3,"oregano, garlic, chili flakes")],
 steps=["Mix the oat flour, yogurt, eggs and baking powder into a soft dough. It's sticky. Wet your hands.",
        "Press it into an oiled cast iron skillet and up the sides. Bake 10 minutes at 425F alone.",
        "Deep dish order: cheese first, then toppings, then sauce on top. That's what stops it going soggy.",
        "Back in for 15 minutes. Parmesan out of the oven. Rest 5 minutes before cutting."],
 storage="2 days. Reheat in the skillet.",
 prep_notes="Two-ingredient yogurt dough with oat flour instead of wheat flour. It won't fool a Chicagoan but it's genuinely good, and it's roughly 50 g protein per half.",
 subs=["Store-bought GF pizza dough saves 12 minutes and costs about $6."],
 variations=["Meat version with the turkey from M-19.","White pizza with blended cottage cheese and garlic."],
 manual_tags=["CHEAT MEAL","PIZZA","HIGH SATIETY","LEUCINE PRIORITY"]),

dict(id="L-55", cat="Lunch/Dinner", name="General Tso's Tofu",
 servings=2, prep=15, cook=15,
 ing=[("tofu_extrafirm",450,"1.5 blocks"),("cornstarch",50,"1/3 cup"),("olive_oil",30,"2 tbsp"),
      ("soy_sauce_gf",40,"2.5 tbsp tamari"),("brown_sugar",40,"3 tbsp"),("acv",20,"4 tsp"),
      ("garlic",12,"4 cloves"),("sriracha",15,"1 tbsp"),("broccoli_cooked",250,"2.5 cups"),
      ("rice_white_cooked",400,"2 cups"),("green_onion",30,"3 scallions")],
 steps=["Press, cube, dry and cornstarch the tofu. Fry in oil until crisp on several sides, then set aside.",
        "Whisk tamari, sugar, vinegar, sriracha and 60 ml water. Fry the garlic 30 seconds, add the sauce.",
        "Let it bubble 2 minutes until it coats a spoon. If it's thin, a teaspoon of cornstarch slurry fixes it.",
        "Toss the tofu through off the heat so it stays crisp. Broccoli and rice alongside."],
 storage="3 days. It softens, which is fine.",
 prep_notes="Takeout Chinese is almost never safe for me. Soy sauce is wheat, the batter is wheat, and shared woks make cross-contamination near certain. Making it myself is the only version I actually get to eat.",
 subs=["Chicken instead of tofu, same method.","Half the sugar for a less sweet, more savory sauce."],
 variations=["Orange version: swap half the tamari for orange juice and add zest."],
 manual_tags=["CHEAT MEAL","MEAL PREP","SAVORY"]),

dict(id="L-56", cat="Lunch/Dinner", name="Birria-Style Bean Tacos",
 servings=2, prep=12, cook=30,
 ing=[("pinto_beans",400,"2 cups"),("corn_tortilla",156,"6 tortillas"),("mozzarella_ps",150,"1.25 cups"),
      ("marinara",200,"3/4 cup"),("onion",100,"1 small"),("garlic",12,"4 cloves"),
      ("olive_oil",20,"1.5 tbsp"),("lemon_juice",20,"4 tsp lime"),
      ("spice_generic",6,"cumin, oregano, cinnamon, smoked paprika, chipotle, bay")],
 steps=["Fry the onion and garlic 8 minutes, add all the spices for a minute, then the beans, marinara and 300 ml water.",
        "Simmer 20 minutes until it's a thick stew. Mash about a third of it. Ladle off some of the red liquid into a bowl, that's your consome for dipping.",
        "Dip each tortilla in the red liquid, then straight into a hot pan.",
        "Fill with beans and cheese, fold, fry 2 minutes a side until crisp. Serve with the consome and lime."],
 storage="Filling keeps 4 days and improves. Fry the tacos fresh.",
 prep_notes="Corn tortillas being naturally gluten-free is lucky. Mexican is one of the few cuisines where I'm barely restricted at all.",
 subs=["Jackfruit or mushrooms for a shreddier texture.","Beef version if you go that direction, same spices."],
 variations=["Quesabirria: double the cheese and skip the beans in half of them."],
 manual_tags=["CHEAT MEAL","MEAL PREP","BUDGET FRIENDLY","HIGH FIBER"]),

dict(id="L-57", cat="Lunch/Dinner", name="Creamy Cajun Pasta",
 servings=2, prep=8, cook=16,
 ing=[("chickpea_pasta_dry",170,"~6 oz dry"),("cottage_cheese_2",300,"1.25 cups"),
      ("milk_2",150,"2/3 cup"),("parmesan",50,"1/2 cup"),("bell_pepper",150,"1.25 peppers"),
      ("onion",80,"1 small"),("tofu_extrafirm",250,"~5/6 block, cubed"),("olive_oil",18,"1.5 tbsp"),
      ("spice_generic",6,"paprika, cayenne, garlic powder, onion powder, thyme, oregano")],
 steps=["Toss the tofu in half the cajun spice and fry it hard in oil until browned. Set aside.",
        "Peppers and onion in the same pan, 6 minutes.",
        "Blend the cottage cheese with the milk until silky. Add it off the heat with the parmesan and the rest of the spice.",
        "Fold in the drained pasta and tofu. Loosen with pasta water if it tightens."],
 storage="3 days.",
 prep_notes="Roughly 55 g protein a serving. Cajun seasoning blends sometimes contain wheat flour as an anti-caking agent, so either check the jar or mix your own from the six spices listed.",
 subs=["Chicken or shrimp-free sausage alternatives.","Regular GF pasta, lower protein, cheaper."],
 variations=["Add sun-dried tomatoes and spinach."],
 manual_tags=["CHEAT MEAL","MEAL PREP","LEUCINE PRIORITY","QUICK"]),

dict(id="L-58", cat="Lunch/Dinner", name="Nachos Supreme",
 servings=2, prep=8, cook=12,
 ing=[("corn_tortilla",130,"5 tortillas, cut into wedges"),("black_beans",300,"1.5 cups"),
      ("cheddar",120,"1 cup"),("cottage_cheese_2",200,"scant 1 cup"),("salsa",120,"1/2 cup"),
      ("avocado",100,"1/2 large"),("greek_yogurt_nonfat",100,"scant 1/2 cup"),
      ("pickled_jalapeno",40,"1/4 cup"),("green_onion",30,"3 scallions"),
      ("olive_oil",14,"1 tbsp"),("spice_generic",3,"cumin, chili")],
 steps=["Toss the tortilla wedges in oil and bake at 400F for 10 minutes until they snap.",
        "Blend the cottage cheese smooth and melt it with half the cheddar into a queso.",
        "Layer chips, beans, queso, remaining cheddar. Back in for 4 minutes.",
        "Everything cold goes on last: salsa, yogurt, avocado, jalapenos, scallions."],
 storage="Eat immediately.",
 prep_notes="The cottage cheese queso is what keeps this from being 1,400 calories of chips. You get roughly 40 g protein a serving out of what is functionally a plate of nachos.",
 subs=["Bagged corn chips, checking the bag says gluten-free."],
 variations=["Add the turkey chili from M-13 or the birria beans from L-56."],
 manual_tags=["CHEAT MEAL","HIGH FIBER","HIGH SATIETY"]),

dict(id="L-59", cat="Lunch/Dinner", name="Five-Minute Cheesy Rice and Egg Bowl",
 servings=1, prep=2, cook=5,
 ing=[("rice_white_cooked",250,"1.25 cups, leftover"),("egg_whole",150,"3 large"),
      ("cheddar",50,"scant 1/2 cup"),("soy_sauce_gf",12,"2.5 tsp tamari"),
      ("sriracha",12,"2.5 tsp"),("green_onion",25,"2 scallions"),("butter",10,"2 tsp"),
      ("spice_generic",1,"black pepper")],
 steps=["Butter in a hot pan, rice in, press it flat and leave it alone for 2 minutes so the bottom crisps.",
        "Push it aside, scramble the eggs in the same pan.",
        "Cheese, tamari, sriracha, scallions. Stir once and eat."],
 storage="Eat fresh.",
 prep_notes="For getting home at eight too tired to cook, when the real alternative is not eating. 40 g of protein, five minutes, one pan. Keep cooked rice in the fridge and it is always there.",
 subs=["Any leftover grain.","Add whatever vegetable is dying in the drawer."],
 variations=["Kimchi if you can find a GF brand. Most are."],
 manual_tags=["QUICK","BUDGET FRIENDLY","LEUCINE PRIORITY","NO-COOK"]),

dict(id="L-60", cat="Lunch/Dinner", name="Beans on Toast, Upgraded",
 servings=1, prep=3, cook=8,
 ing=[("gf_bread",70,"2 slices"),("kidney_beans",250,"1.25 cups, white beans"),
      ("marinara",120,"1/2 cup"),("cheddar",50,"scant 1/2 cup"),("egg_whole",50,"1 large"),
      ("olive_oil",10,"2 tsp"),("garlic",8,"2 cloves"),("spice_generic",3,"smoked paprika, chili, pepper")],
 steps=["Garlic in oil for 30 seconds. Beans, marinara, spices, a splash of water.",
        "Simmer 6 minutes, mashing a third of the beans so it thickens.",
        "Toast the bread hard, cheese over the hot beans, fried egg on top."],
 storage="Beans keep 4 days.",
 prep_notes="About 40 g protein and 15 g fiber for around two dollars. This is the cheapest genuinely good meal in the catalog.",
 subs=["Canned baked beans if you check the label. Many contain wheat starch.",
       "Skip the bread and put it over a baked potato."],
 variations=["Add chorizo-style seasoning, or a spoon of pesto."],
 manual_tags=["QUICK","BUDGET FRIENDLY","HIGH FIBER","HIGH SATIETY"]),

# ============================== BREAKFAST ==============================
dict(id="B-35", cat="Breakfast", name="Protein French Toast Sticks",
 servings=1, prep=5, cook=8,
 ing=[("gf_bread",105,"3 slices, cut into strips"),("egg_whole",100,"2 large"),
      ("milk_2",80,"1/3 cup"),("whey_isolate",25,"3/4 scoop vanilla"),("cinnamon",3,"3/4 tsp"),
      ("vanilla_extract",3,"3/4 tsp"),("butter",10,"2 tsp"),("greek_yogurt_nonfat",100,"scant 1/2 cup"),
      ("maple_syrup",20,"1 tbsp")],
 steps=["Whisk the eggs, milk, protein powder, cinnamon and vanilla until there are no lumps at all.",
        "Cut the bread into strips. Stale bread works better, it absorbs without falling apart.",
        "Soak each strip briefly, then fry in butter 2 minutes a side.",
        "Dip in the yogurt thinned with the syrup, which is a better sauce than syrup alone and adds 10 g protein."],
 storage="Freeze cooked sticks and toast them from frozen. They're genuinely good that way.",
 prep_notes="Make a triple batch on Sunday and freeze them. Three minutes in a toaster on a work morning.",
 subs=["Egg whites only for a leaner version."],
 variations=["Roll them in cinnamon sugar out of the pan for the churro version."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","SWEET","QUICK"]),

dict(id="B-36", cat="Breakfast", name="Loaded Breakfast Skillet",
 servings=1, prep=8, cook=16,
 ing=[("potato",300,"2 medium, diced small"),("egg_whole",150,"3 large"),("black_beans",120,"1/2 cup"),
      ("cheddar",50,"scant 1/2 cup"),("bell_pepper",80,"1/2 pepper"),("onion",60,"1/2 small"),
      ("olive_oil",18,"1.5 tbsp"),("salsa",60,"1/4 cup"),("avocado",50,"1/4 large"),
      ("cholula",8,"1.5 tsp"),("spice_generic",3,"smoked paprika, cumin, pepper")],
 steps=["Dice the potato small, about 1 cm, and get it in the hot oil first. It needs 10 minutes before anything else joins it.",
        "Don't stir for the first 4 minutes. That's how you get crust instead of steam.",
        "Peppers and onions in, 4 more minutes. Beans and spices, 2 more.",
        "Make three wells, crack the eggs in, cover 4 minutes. Cheese, salsa, avocado, Cholula."],
 storage="3 days without the eggs. Add fresh eggs each time.",
 prep_notes="One pan, covers a third of a day's calories. Good on a day off with twenty minutes to spare.",
 subs=["Frozen diced potatoes save 8 minutes. Check the bag for wheat coatings.",
       "Sweet potato for more vitamin A."],
 variations=["Add an Impossible patty crumbled in with the peppers."],
 manual_tags=["HIGH CALORIE","HIGH SATIETY","SAVORY"]),

dict(id="B-37", cat="Breakfast", name="Breakfast Quesadilla",
 servings=1, prep=4, cook=7,
 ing=[("corn_tortilla",78,"3 tortillas"),("egg_whole",150,"3 large"),("cheddar",60,"1/2 cup"),
      ("black_beans",120,"1/2 cup"),("spinach",50,"1.5 cups"),("salsa",50,"3 tbsp"),
      ("olive_oil",10,"2 tsp"),("greek_yogurt_nonfat",50,"3 tbsp")],
 steps=["Scramble the eggs soft with the spinach. Pull them a bit underdone, they finish in the quesadilla.",
        "Cheese on the tortilla first so it glues everything together, then eggs and beans, then more cheese.",
        "Dry-fry with a little oil, 3 minutes a side, pressing down.",
        "Cut into wedges, dip in salsa and yogurt."],
 storage="2 days. Reheat in a pan.",
 prep_notes="Faster than a burrito, cheaper than a GF wrap, and corn tortillas are naturally safe.",
 subs=["One GF wrap instead of three corn tortillas."],
 variations=["Add potato, or leftover taco filling from anything in the L section."],
 manual_tags=["QUICK","BUDGET FRIENDLY","LEUCINE PRIORITY"]),

dict(id="B-38", cat="Breakfast", name="Savory Oats with Egg and Cheese",
 servings=1, prep=3, cook=8,
 ing=[("oats_gf_dry",60,"3/4 cup dry"),("egg_whole",100,"2 large"),("cheddar",40,"1/3 cup"),
      ("spinach",60,"2 packed cups"),("nutritional_yeast",10,"2 tbsp"),
      ("olive_oil",10,"2 tsp"),("cholula",8,"1.5 tsp"),("spice_generic",2,"garlic powder, pepper")],
 steps=["Cook the oats in water with a good pinch of salt, 5 minutes, until they're creamy. Water, not milk, for savory.",
        "Stir in the nutritional yeast, cheese and wilted spinach. It becomes something close to a risotto.",
        "Fry the eggs, put them on top, Cholula over."],
 storage="Eat fresh.",
 prep_notes="If sweet breakfasts are getting old after two weeks of overnight oats, this is the fix. Same cheap ingredient, completely different meal.",
 subs=["Parmesan instead of cheddar and nutritional yeast."],
 variations=["Add mushrooms fried hard, or a spoon of marinara."],
 manual_tags=["QUICK","BUDGET FRIENDLY","SAVORY","HIGH FIBER"]),

# ============================== HEALTHY DESSERTS ==============================
dict(id="S-65", cat="Snack", name="Protein Tiramisu Cups",
 servings=2, prep=12, cook=0,
 ing=[("greek_yogurt_nonfat",300,"1.25 cups"),("cream_cheese_whipped",50,"1/3 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("cold_brew",120,"1/2 cup, strong"),
      ("gf_sandwich_cookie",40,"~5 GF cookies, or GF ladyfingers"),("cocoa_powder",6,"1 tbsp"),
      ("maple_syrup",20,"1 tbsp"),("vanilla_extract",3,"3/4 tsp")],
 steps=["Whip the yogurt, cream cheese, protein powder, syrup and vanilla until it holds a peak.",
        "Dip the cookies in the cold brew for one second each. One second. They turn to sludge at three.",
        "Layer cookies, cream, cookies, cream in two glasses.",
        "Chill at least 2 hours. Dust with cocoa right before eating, not before chilling."],
 storage="3 days, and it's better on day two.",
 prep_notes="GF ladyfingers exist but they're hard to find and expensive. GF chocolate sandwich cookies work and honestly taste better here.",
 subs=["Decaf if you're making it in the evening."],
 variations=["Add a splash of almond extract."],
 manual_tags=["HEALTHY DESSERT","SWEET","LEUCINE PRIORITY","MEAL PREP"]),

dict(id="S-66", cat="Snack", name="Chocolate Avocado Mousse",
 servings=2, prep=8, cook=0,
 ing=[("avocado",200,"1 large, very ripe"),("cocoa_powder",25,"1/3 cup"),
      ("maple_syrup",50,"2.5 tbsp"),("milk_skim",100,"scant 1/2 cup"),
      ("whey_isolate",25,"3/4 scoop chocolate"),("vanilla_extract",3,"3/4 tsp"),("salt",1,"pinch")],
 steps=["The avocado has to be properly ripe. Underripe avocado tastes like avocado in this, which is not the goal.",
        "Blend everything for a full 90 seconds, scraping down twice. It goes from grainy to silk if you're patient.",
        "Chill 30 minutes."],
 storage="2 days with cling film pressed to the surface.",
 prep_notes="You genuinely cannot taste the avocado. It's doing the job cream does, at a fraction of the saturated fat and with potassium and fiber attached.",
 subs=["Silken tofu instead of avocado, lower fat, higher protein, slightly less rich."],
 variations=["Add espresso powder, orange zest, or a pinch of cayenne."],
 manual_tags=["HEALTHY DESSERT","SWEET","HIGH HEALTHY FAT","HIGH FIBER"]),

dict(id="S-67", cat="Snack", name="Peanut Butter Protein Fluff",
 servings=1, prep=6, cook=0,
 ing=[("casein_powder",30,"1 scoop vanilla"),("pb_powder",20,"3 tbsp"),
      ("milk_skim",200,"3/4 cup"),("greek_yogurt_nonfat",100,"scant 1/2 cup"),
      ("choc_chips_mini",10,"1 tbsp")],
 steps=["Put everything except the chips in a bowl and beat it with a hand mixer for a full 4 minutes.",
        "It roughly triples in volume. Casein is the only powder that does this properly; whey stays soup.",
        "Chips on top. Eat with a spoon, slowly, because it's a huge bowl for the calories."],
 storage="Eat immediately. It deflates.",
 prep_notes="Roughly 40 g of protein for under 350 calories, and the volume is the point. When you're hungry at nine at night and don't want to spend 700 calories on it, this is the answer.",
 subs=["Real peanut butter instead of powder is better tasting and adds ~120 kcal."],
 variations=["Chocolate, strawberry, cookies and cream. Any casein flavour works."],
 manual_tags=["HEALTHY DESSERT","LOW CALORIE","LEUCINE PRIORITY","PRE-SLEEP","HIGH SATIETY"]),

dict(id="S-68", cat="Snack", name="Baked Apple Crumble Cup",
 servings=1, prep=6, cook=18,
 ing=[("apple",250,"1.5 large, diced"),("oats_gf_dry",40,"1/2 cup"),("almonds",20,"~16, chopped"),
      ("butter",12,"2.5 tsp"),("maple_syrup",15,"1 tbsp"),("cinnamon",3,"3/4 tsp"),
      ("greek_yogurt_nonfat",150,"2/3 cup"),("whey_isolate",15,"1/2 scoop vanilla")],
 steps=["Toss the diced apple with half the cinnamon and a splash of water in a ramekin.",
        "Rub the butter into the oats, almonds, syrup and remaining cinnamon until it clumps.",
        "Scatter over, bake 18 minutes at 375F until the top is brown and the fruit is bubbling.",
        "Stir the protein powder into the yogurt and spoon it over the hot crumble."],
 storage="Assemble and refrigerate unbaked for up to 2 days, then bake fresh.",
 prep_notes="Hot fruit and cold protein yogurt is a better combination than crumble and cream, and it's the difference between a dessert and a 30 g protein feeding.",
 subs=["Frozen berries instead of apple, no dicing needed."],
 variations=["Pear and ginger. Peach in summer."],
 manual_tags=["HEALTHY DESSERT","SWEET","HIGH FIBER"]),

dict(id="S-69", cat="Snack", name="Protein Churro Bites",
 servings=2, prep=10, cook=12,
 ing=[("gf_oat_flour",100,"1 cup"),("greek_yogurt_nonfat",180,"3/4 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("baking_powder",6,"1.5 tsp"),
      ("egg_whole",50,"1 large"),("sugar",25,"2 tbsp"),("cinnamon",6,"2 tsp"),
      ("butter",15,"1 tbsp"),("cocoa_powder",8,"1.5 tbsp"),("milk_skim",60,"1/4 cup")],
 steps=["Mix the oat flour, yogurt, protein powder, baking powder and egg into a thick dough.",
        "Roll into 20 small balls, bake 12 minutes at 400F.",
        "Brush with melted butter while hot and roll in the cinnamon sugar. Hot is the only time the sugar sticks.",
        "Whisk the cocoa with the milk and a little sugar for dipping."],
 storage="3 days. Re-crisp in a hot oven for 4 minutes.",
 prep_notes="",
 subs=["Air fryer at 380F for 10 minutes."],
 variations=["Fill them with a chocolate chip before baking."],
 manual_tags=["HEALTHY DESSERT","SWEET","MEAL PREP"]),

dict(id="S-70", cat="Snack", name="Frozen Strawberry Cheesecake Bites",
 servings=4, prep=15, cook=0,
 ing=[("greek_yogurt_nonfat",400,"1.75 cups"),("cream_cheese_whipped",80,"1/2 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("strawberries",200,"~14 berries"),
      ("honey",40,"2 tbsp"),("oats_gf_dry",60,"3/4 cup"),("almonds",40,"1/3 cup"),
      ("butter",20,"1.5 tbsp")],
 steps=["Blitz the oats, almonds and melted butter for the base. Press a teaspoon of it into each cup of a lined muffin tin.",
        "Blend the yogurt, cream cheese, protein powder, honey and half the strawberries until smooth.",
        "Pour over the bases, press a slice of strawberry into each.",
        "Freeze 4 hours. Let them sit 5 minutes before eating."],
 storage="2 months frozen.",
 prep_notes="Twelve bites, three per serving. Portioning them in a muffin tin is the whole reason this works as a habit rather than a binge.",
 subs=["Any berry.","Skip the base for a lower-calorie version."],
 variations=["Lemon, or chocolate with cocoa in the filling."],
 manual_tags=["HEALTHY DESSERT","FREEZER FRIENDLY","MEAL PREP","SWEET"]),

dict(id="S-71", cat="Snack", name="Pumpkin Protein Pie Cups",
 servings=2, prep=8, cook=0,
 ing=[("pumpkin_puree",240,"1 cup"),("greek_yogurt_nonfat",200,"3/4 cup"),
      ("casein_powder",30,"1 scoop vanilla"),("maple_syrup",30,"1.5 tbsp"),
      ("cinnamon",4,"1.25 tsp"),("spice_generic",2,"nutmeg, ginger, clove"),
      ("walnuts",25,"~12 halves"),("whipped_cream",10,"4 tbsp")],
 steps=["Whisk the pumpkin, yogurt, casein, syrup and spices until completely smooth.",
        "Rest 20 minutes in the fridge so the casein sets it. It goes from loose to sliceable.",
        "Top with toasted walnuts and whipped cream."],
 storage="4 days.",
 prep_notes="Canned pumpkin is one of the most underrated foods in a grocery store. Two dollars, almost no calories, a full day of vitamin A, and it makes anything taste like dessert.",
 subs=["Sweet potato puree.","Whey instead of casein, but it stays runnier."],
 variations=["Layer with the crumble topping from S-68."],
 manual_tags=["HEALTHY DESSERT","LOW CALORIE","HIGH MICRONUTRIENT DENSITY","PRE-SLEEP"]),

dict(id="S-72", cat="Snack", name="Snickers-Style Frozen Banana Bites",
 servings=3, prep=12, cook=0,
 ing=[("banana",300,"2.5 large"),("peanut_butter",60,"1/4 cup"),("dark_chocolate_70",80,"~3 oz"),
      ("peanuts_roasted",30,"1/4 cup, crushed"),("coconut_oil",8,"1.5 tsp"),("salt",1,"flaky")],
 steps=["Slice the bananas into thick coins. Sandwich peanut butter between pairs.",
        "Freeze the sandwiches solid, at least an hour. Skip this and the chocolate slides off.",
        "Melt the chocolate with the coconut oil, dip each one, roll in crushed peanuts.",
        "Back in the freezer 15 minutes. Salt on top."],
 storage="2 months frozen.",
 prep_notes="Tastes closer to the actual candy bar than it has any right to.",
 subs=["Almond butter.","Sugar-free chocolate if you want to keep sugar down."],
 variations=["Roll in coconut, or crushed GF pretzels."],
 manual_tags=["HEALTHY DESSERT","FREEZER FRIENDLY","SWEET","PRE-WORKOUT FRIENDLY"]),

dict(id="S-73", cat="Snack", name="Cottage Cheese Ice Cream",
 servings=1, prep=5, cook=0,
 ing=[("cottage_cheese_2",300,"1.25 cups"),("honey",25,"1.25 tbsp"),
      ("whey_isolate",20,"2/3 scoop vanilla"),("vanilla_extract",3,"3/4 tsp"),
      ("choc_chips_mini",15,"1.5 tbsp"),("salt",1,"pinch")],
 steps=["Blend the cottage cheese, honey, protein powder, vanilla and salt for a full 90 seconds. It must be completely smooth or the texture is grainy.",
        "Fold in the chips, freeze 2 to 3 hours.",
        "Take it out 10 minutes before eating. Frozen solid it's a brick."],
 storage="2 weeks frozen, but the texture is best in the first few days.",
 prep_notes="This is the internet's cottage cheese ice cream and it deserves the attention. 45 g of protein in a bowl of what is functionally ice cream. Use 2% rather than nonfat, the fat matters for texture here.",
 subs=["Frozen banana blended in makes it creamier and adds 100 kcal."],
 variations=["Cookies and cream with GF cookies. Peanut butter cup. Strawberry with real berries blended in."],
 manual_tags=["HEALTHY DESSERT","LEUCINE PRIORITY","SWEET","HIGH SATIETY"]),

dict(id="S-74", cat="Snack", name="No-Bake Protein Cheesecake Bars",
 servings=8, prep=20, cook=0,
 ing=[("oats_gf_dry",120,"1.5 cups"),("almonds",80,"2/3 cup"),("dates_medjool",100,"~4 dates"),
      ("cottage_cheese_2",500,"2 cups"),("greek_yogurt_nonfat",250,"1 cup"),
      ("whey_isolate",60,"2 scoops vanilla"),("honey",60,"3 tbsp"),
      ("lemon_juice",30,"2 tbsp"),("dark_chocolate_70",50,"~1.75 oz, melted")],
 steps=["Process the oats, almonds and dates until it clumps. Press hard into a lined 8x8 pan.",
        "Blend the cottage cheese, yogurt, protein powder, honey and lemon for two full minutes. Any graininess left now will still be there tomorrow.",
        "Pour over the base, chill 4 hours minimum.",
        "Drizzle melted chocolate over, cut into 8."],
 storage="5 days refrigerated, 2 months frozen.",
 prep_notes="Roughly 25 g protein per bar. Wrap them individually and they replace whatever bar you'd otherwise buy at a gas station.",
 subs=["Ricotta for a milder flavour.","Skip the chocolate to save 30 kcal a bar."],
 variations=["Berry swirl. Lemon. Peanut butter with cocoa in the base."],
 manual_tags=["HEALTHY DESSERT","MEAL PREP","FREEZER FRIENDLY","BUDGET FRIENDLY"]),

# ============================== REAL DESSERTS, PORTIONED ==============================
dict(id="S-75", cat="Snack", name="Skillet Chocolate Chip Cookie",
 servings=4, prep=10, cook=18,
 ing=[("gf_oat_flour",150,"1.5 cups"),("butter",80,"5.5 tbsp, softened"),("brown_sugar",90,"1/2 cup"),
      ("egg_whole",50,"1 large"),("choc_chips_mini",100,"2/3 cup"),("vanilla_extract",5,"1.25 tsp"),
      ("baking_powder",4,"1 tsp"),("salt",2,"1/2 tsp"),("vanilla_ice_cream",120,"4 small scoops")],
 steps=["Beat the butter and sugar for 3 minutes until pale. This is the step everyone skips and it's why their cookies are flat.",
        "Beat in the egg and vanilla, then fold in the flour, baking powder, salt and chips.",
        "Press into a small cast iron skillet, bake 16 to 18 minutes at 350F.",
        "Pull it while the middle still looks underdone. Ice cream on top while it's hot."],
 storage="3 days covered.",
 prep_notes="This is a real dessert, not a protein dessert, and it's in here on purpose. Roughly 520 calories a quarter. Once a week does nothing. Believing I can't have it is what causes the problem.",
 subs=["GF flour blend instead of oat flour for a more conventional texture."],
 variations=["Brown the butter first. It's a genuine upgrade and takes four minutes."],
 manual_tags=["CHEAT DESSERT","SWEET","HIGH CALORIE"]),

dict(id="S-76", cat="Snack", name="Brownie Sundae",
 servings=4, prep=12, cook=25,
 ing=[("gf_oat_flour",100,"1 cup"),("cocoa_powder",50,"2/3 cup"),("butter",90,"6 tbsp, melted"),
      ("sugar",140,"3/4 cup"),("egg_whole",100,"2 large"),("dark_chocolate_70",60,"~2 oz, chopped"),
      ("vanilla_extract",5,"1.25 tsp"),("salt",2,"1/2 tsp"),
      ("vanilla_ice_cream",160,"4 scoops"),("peanut_butter",40,"2.5 tbsp, warmed")],
 steps=["Whisk the melted butter and sugar hard for 2 minutes. That's what gives brownies the shiny crackly top.",
        "Beat in the eggs and vanilla, then fold in the cocoa, oat flour and salt. Do not overmix.",
        "Stir through the chopped chocolate, bake 22 to 25 minutes at 350F in a lined 8x8.",
        "Underbake slightly. Cool 20 minutes, cut, top with ice cream and warm peanut butter."],
 storage="4 days, or freeze the brownies for 3 months.",
 prep_notes="About 640 calories a serving with the ice cream. Have it, enjoy it, don't build a story around it. The four-week average is what matters and one sundae is about 2% of a week.",
 subs=["Skip the ice cream and it's a 450 kcal brownie."],
 variations=["Salted caramel. Raspberry. Espresso in the batter."],
 manual_tags=["CHEAT DESSERT","SWEET","HIGH CALORIE"]),

dict(id="S-77", cat="Snack", name="Cinnamon Roll in a Mug",
 servings=1, prep=5, cook=2,
 ing=[("gf_oat_flour",40,"1/3 cup"),("greek_yogurt_nonfat",60,"1/4 cup"),
      ("milk_2",40,"2.5 tbsp"),("baking_powder",3,"3/4 tsp"),("brown_sugar",25,"2 tbsp"),
      ("cinnamon",5,"1.5 tsp"),("butter",10,"2 tsp"),("cream_cheese_whipped",30,"2 tbsp"),
      ("sugar",10,"2.5 tsp"),("vanilla_extract",2,"1/2 tsp")],
 steps=["Mix the oat flour, yogurt, milk and baking powder in a mug into a thick batter.",
        "Stir the brown sugar, cinnamon and melted butter into a paste and swirl it through with a knife. Don't mix it in, swirl it.",
        "Microwave 80 to 90 seconds.",
        "Beat the cream cheese with the sugar and vanilla and spread it on while hot."],
 storage="Eat immediately.",
 prep_notes="Five minutes, one mug, and it scratches the specific itch that nothing else does.",
 subs=["Add a scoop of vanilla protein powder and 2 tbsp more milk for ~25 g protein."],
 variations=["Apple cinnamon: fold diced apple into the batter."],
 manual_tags=["CHEAT DESSERT","QUICK","SWEET"]),

dict(id="S-78", cat="Snack", name="Greek Yogurt Chocolate Bark",
 servings=4, prep=10, cook=0,
 ing=[("greek_yogurt_nonfat",400,"1.75 cups"),("whey_isolate",30,"1 scoop chocolate"),
      ("cocoa_powder",10,"2 tbsp"),("honey",40,"2 tbsp"),("peanut_butter",40,"2.5 tbsp"),
      ("strawberries",100,"~7 berries"),("almonds",30,"~24, chopped")],
 steps=["Whisk the yogurt, protein powder, cocoa and honey until smooth.",
        "Spread 1 cm thick on parchment.",
        "Warm the peanut butter and drizzle it over, then drag a knife through for the swirl.",
        "Press in the berries and almonds. Freeze 4 hours, break into shards."],
 storage="2 months frozen.",
 prep_notes="One tray is a week of after-dinner dessert at about 180 calories a serving.",
 subs=["Any fruit, any nut."],
 variations=["Mint chocolate. Cookies and cream with GF cookies crushed in."],
 manual_tags=["HEALTHY DESSERT","FREEZER FRIENDLY","MEAL PREP","LOW CALORIE"]),

dict(id="S-79", cat="Snack", name="Cookie Dough Protein Dip",
 servings=2, prep=8, cook=0,
 ing=[("chickpeas",240,"1.25 cups, rinsed well"),("peanut_butter",50,"3 tbsp"),
      ("whey_isolate",25,"3/4 scoop vanilla"),("maple_syrup",35,"2 tbsp"),
      ("oats_gf_dry",20,"1/4 cup"),("vanilla_extract",5,"1.25 tsp"),
      ("choc_chips_mini",30,"3 tbsp"),("salt",2,"1/2 tsp"),("apple",150,"1 medium, for dipping")],
 steps=["Rinse the chickpeas until the water runs clear and rub the skins off. Both steps matter; skins are why bean desserts taste like beans.",
        "Blend everything except the chips for two minutes until it's completely smooth.",
        "Fold in the chips. Dip apple slices, or eat it with a spoon."],
 storage="4 days.",
 prep_notes="Nobody guesses chickpeas. About 20 g protein and 9 g fiber a serving in something that tastes like cookie dough.",
 subs=["White beans work identically."],
 variations=["Add cocoa for a brownie batter version."],
 manual_tags=["HEALTHY DESSERT","HIGH FIBER","BUDGET FRIENDLY","SWEET"]),

dict(id="S-80", cat="Snack", name="Everything-Seasoned Cottage Cheese Toast",
 servings=1, prep=3, cook=2,
 ing=[("gf_bread",70,"2 slices"),("cottage_cheese_2",200,"scant 1 cup"),
      ("cucumber",80,"1/3 cucumber"),("hemp_hearts",15,"1.5 tbsp"),
      ("olive_oil",8,"1.5 tsp"),("spice_generic",3,"everything seasoning, chili flakes")],
 steps=["Toast hard.","Cottage cheese straight from the tub, thick.",
        "Cucumber, hemp hearts, oil, seasoning."],
 storage="Eat fresh.",
 prep_notes="Three minutes, 30 g protein. Check the everything seasoning; most are GF but some blends use wheat-based anti-caking agents.",
 subs=["Ricotta, or blended cottage cheese if curds bother you."],
 variations=["Tomato and basil. Avocado and chili."],
 manual_tags=["QUICK","SAVORY","HIGH SATIETY","NO-COOK"]),

# ============================== DRINKS ==============================
dict(id="D-42", cat="Drink", name="Chocolate Malt Cheat Shake",
 servings=1, prep=4, cook=0,
 ing=[("vanilla_ice_cream",150,"3 scoops"),("milk_whole",200,"3/4 cup"),
      ("whey_isolate",30,"1 scoop chocolate"),("cocoa_powder",8,"1.5 tbsp"),
      ("peanut_butter",20,"1.25 tbsp"),("whipped_cream",15,"6 tbsp")],
 steps=["Blend the ice cream, milk, protein powder, cocoa and peanut butter for 20 seconds. No longer, or it goes thin.",
        "Whipped cream on top. Drink it with a spoon."],
 storage="Drink immediately.",
 prep_notes="Roughly 800 calories and 45 g protein. This is a diner milkshake with a scoop in it, and on a day you're 800 calories behind at nine at night, it's the most efficient fix available.",
 subs=["Frozen banana instead of ice cream cuts ~250 kcal and makes it a normal shake."],
 variations=["Cookies and cream with GF cookies blended in."],
 manual_tags=["CHEAT DESSERT","HIGH CALORIE","TWO-MEAL-DAY FRIENDLY"]),

dict(id="D-43", cat="Drink", name="Strawberry Lemonade Protein Refresher",
 servings=1, prep=4, cook=0,
 ing=[("strawberries",150,"~10 berries"),("lemon_juice",40,"2.5 tbsp"),
      ("whey_isolate",30,"1 scoop, unflavoured or fruit"),("honey",15,"2 tsp"),
      ("spice_generic",1,"fresh mint")],
 steps=["Muddle the strawberries with the lemon and honey in the bottom of a shaker.",
        "Add 400 ml cold water and plenty of ice.",
        "Protein powder last, shake hard 20 seconds, let the foam settle."],
 storage="Drink fresh.",
 prep_notes="About 190 calories for 26 g protein. Useful on a hot day on site when a milky shake sounds unbearable.",
 subs=["Clear whey isolate mixes better here but costs more."],
 variations=["Watermelon. Peach. Raspberry lime."],
 manual_tags=["LOW CALORIE","LEUCINE PRIORITY","QUICK"]),

dict(id="D-44", cat="Drink", name="Peanut Butter Banana Malt",
 servings=1, prep=3, cook=0,
 ing=[("banana",180,"1.5 large, frozen"),("peanut_butter",48,"3 tbsp"),
      ("milk_whole",350,"1.5 cups"),("whey_isolate",35,"1.2 scoops vanilla"),
      ("honey",20,"1 tbsp"),("salt",1,"pinch")],
 steps=["Blend for 60 seconds. Frozen banana is what makes it thick without ice watering it down."],
 storage="Drink fresh.",
 prep_notes="Roughly 850 calories. Same purpose as D-30 but it tastes more like a treat and less like a chore.",
 subs=["Skim milk cuts ~120 kcal.","Half the peanut butter cuts ~180."],
 variations=["Add cocoa, or 30 g oats for another 110 kcal."],
 manual_tags=["HIGH CALORIE","TWO-MEAL-DAY FRIENDLY","POST-WORKOUT FRIENDLY"]),

dict(id="D-45", cat="Drink", name="Lime Electrolyte Cooler",
 servings=1, prep=3, cook=0,
 ing=[("lemon_juice",40,"2.5 tbsp lime"),("honey",20,"1 tbsp"),("salt",2,"1/2 tsp"),
      ("orange",100,"1 medium, juiced"),("spice_generic",1,"mint, optional")],
 steps=["Dissolve the salt and honey in a little warm water first. Salt does not dissolve in cold.",
        "Add 600 ml cold water, the lime and orange juice, and ice."],
 storage="2 days refrigerated.",
 prep_notes="Roughly 800 mg sodium and 400 mg potassium. In dry Colorado air I lose more sodium than it feels like, and the flat, hollow afternoon feeling is usually this rather than dehydration in general.",
 subs=["A commercial electrolyte packet does the same thing for more money. Check it's GF."],
 variations=["Add a scoop of unflavoured whey to make it a recovery drink."],
 manual_tags=["LOW CALORIE","QUICK","HEALTH DRINK"]),

dict(id="D-46", cat="Drink", name="Ginger Turmeric Tonic",
 servings=1, prep=5, cook=5,
 ing=[("lemon_juice",30,"2 tbsp"),("honey",20,"1 tbsp"),
      ("spice_generic",5,"fresh ginger, turmeric, black pepper, cayenne"),
      ("orange",100,"1 medium, juiced")],
 steps=["Simmer the grated ginger and turmeric in 400 ml water for 5 minutes.",
        "Strain, add the lemon, orange juice, honey, black pepper and a pinch of cayenne.",
        "Black pepper is not optional. Without piperine, curcumin absorption is close to nothing."],
 storage="3 days refrigerated. Good cold too.",
 prep_notes="Worth being honest: the anti-inflammatory doses used in curcumin research are far above what you get from a teaspoon of turmeric. Drink this because it's good and warming, not because it will do much for CRMO. Fish, sleep and calories will do more.",
 subs=["Powdered ginger and turmeric work, use half the amount."],
 variations=["Add green tea, or a cinnamon stick."],
 manual_tags=["HEALTH DRINK","LOW CALORIE"]),

dict(id="D-47", cat="Drink", name="Morning Cider Vinegar Tonic",
 servings=1, prep=2, cook=0,
 ing=[("acv",20,"4 tsp"),("lemon_juice",20,"4 tsp"),("honey",12,"2 tsp"),
      ("cinnamon",2,"1/2 tsp")],
 steps=["Stir everything into 400 ml of water. Cold or warm, not hot.",
        "Drink it through a straw and rinse your mouth after. Vinegar is hard on enamel, and whiter teeth are on the list."],
 storage="Make fresh.",
 prep_notes="The honest read: apple cider vinegar has modest evidence for blunting post-meal blood glucose. It does not burn fat, boost metabolism, or detox anything. It's a pleasant low-calorie drink with a small real effect, and that's the whole claim.",
 subs=["Any vinegar works. Apple cider just tastes best."],
 variations=["Add ginger, or sparkling water."],
 manual_tags=["HEALTH DRINK","LOW CALORIE","QUICK"]),

dict(id="D-48", cat="Drink", name="Green Tea Citrus Cooler",
 servings=1, prep=4, cook=0,
 ing=[("black_tea_brewed",300,"1.25 cups green tea, brewed and chilled"),
      ("orange",120,"1 large, juiced"),("lemon_juice",20,"4 tsp"),
      ("honey",12,"2 tsp"),("spice_generic",1,"mint")],
 steps=["Brew the green tea at about 175F, not boiling, for 3 minutes. Boiling water makes it bitter.",
        "Chill it, then add the citrus, honey and mint over ice."],
 storage="3 days refrigerated.",
 prep_notes="Around 30 mg of caffeine, a fraction of coffee. With a resting heart rate sitting around 94, a gentler caffeine source is worth having in the rotation.",
 subs=["Decaf green tea keeps the polyphenols without the caffeine."],
 variations=["Add frozen berries as ice cubes."],
 manual_tags=["HEALTH DRINK","LOW CALORIE","QUICK"]),

# ============================== SDA MEAT / FISH ==============================
dict(id="M-23", cat="SDA Meat/Fish", name="Honey Mustard Chicken Wrap",
 servings=1, prep=8, cook=10,
 ing=[("chicken_breast",170,"~6 oz raw"),("gf_wrap",70,"1 large"),
      ("greek_yogurt_nonfat",60,"1/4 cup"),("mustard_yellow",15,"1 tbsp"),("honey",15,"2 tsp"),
      ("romaine",60,"2 leaves"),("tomato",60,"1/2 medium"),("cheddar",30,"1/4 cup"),
      ("olive_oil",10,"2 tsp"),("spice_generic",2,"paprika, garlic powder")],
 steps=["Slice the chicken thin, season, sear 3 minutes a side in oil.",
        "Whisk the yogurt, mustard and honey into a sauce.",
        "Warm the wrap, build it in a line rather than spread out, roll tight, and sear the seam side down."],
 storage="Components 4 days. Roll fresh.",
 prep_notes="Honey mustard normally means mayo. Greek yogurt gets you the same sauce with 10 g of protein instead of 20 g of fat.",
 subs=["Two corn tortillas instead of the GF wrap.","Chickpeas for the vegetarian version."],
 variations=["Buffalo version with the sauce from L-50."],
 manual_tags=["SDA-COMPATIBLE","QUICK","LEUCINE PRIORITY"]),

dict(id="M-24", cat="SDA Meat/Fish", name="Teriyaki Salmon Rice Bowl",
 servings=1, prep=8, cook=12,
 ing=[("salmon",170,"6 oz fillet"),("rice_white_cooked",250,"1.25 cups"),
      ("soy_sauce_gf",25,"5 tsp tamari"),("honey",20,"1 tbsp"),("acv",8,"1.5 tsp"),
      ("garlic",8,"2 cloves"),("broccoli_cooked",150,"1.5 cups"),("edamame_shelled",80,"1/2 cup"),
      ("green_onion",25,"2 scallions"),("olive_oil",10,"2 tsp")],
 steps=["Whisk the tamari, honey, vinegar and garlic.",
        "Sear the salmon skin side down in oil for 4 minutes without moving it, flip, 3 minutes more.",
        "Pour the sauce in for the last minute and spoon it over as it thickens.",
        "Serve on rice with the broccoli and edamame. Scallions on top."],
 storage="2 days.",
 prep_notes="Store-bought teriyaki is almost always wheat-based. Four ingredients and 30 seconds makes a better one that you can actually eat.",
 subs=["Cod or tilapia, far less omega-3.","Tofu for the vegetarian version."],
 variations=["Add sesame seeds and a little chili oil."],
 manual_tags=["SDA-COMPATIBLE","OMEGA-3 RICH","QUICK","LEUCINE PRIORITY"]),

dict(id="M-25", cat="SDA Meat/Fish", name="Buffalo Chicken Dip",
 servings=6, prep=10, cook=25,
 ing=[("chicken_breast",450,"~1 lb, cooked and shredded"),
      ("greek_yogurt_nonfat",300,"1.25 cups"),("cream_cheese_whipped",120,"3/4 cup"),
      ("buffalo_sauce",150,"2/3 cup"),("cheddar",150,"1.25 cups"),
      ("green_onion",30,"3 scallions"),("carrot",300,"6 medium, as dippers")],
 steps=["Shred the cooked chicken with two forks, or a stand mixer if you have one, which takes 20 seconds.",
        "Mix with the yogurt, cream cheese, buffalo sauce and half the cheddar.",
        "Spread in a dish, remaining cheese on top, bake 25 minutes at 350F until bubbling.",
        "Scallions over. Serve with carrots, celery or GF chips."],
 storage="4 days. Reheat covered.",
 prep_notes="Swapping most of the cream cheese and all of the ranch for Greek yogurt takes this from a 400 kcal per serving indulgence to roughly 230 with 28 g protein. It's a party food that happens to be a good macro fit.",
 subs=["Shredded tofu or jackfruit for the vegetarian version, same method.",
       "Check the buffalo sauce for wheat-based thickeners."],
 variations=["Add blue cheese crumbles if you like it sharper."],
 manual_tags=["SDA-COMPATIBLE","CHEAT MEAL","MEAL PREP","LEUCINE PRIORITY"]),
]
