# -*- coding: utf-8 -*-
"""Recipe library, part 4. Completes the category minimums."""

RECIPES_4 = [

# ============================== BREAKFAST ==============================
dict(id="B-23", cat="Breakfast", name="Cinnamon Roll Protein Baked Oats",
 servings=2, prep=8, cook=25,
 ing=[("oats_gf_dry",100,"1.25 cups dry"),("egg_whole",100,"2 large"),("whey_isolate",30,"1 scoop vanilla"),
      ("milk_2",200,"3/4 cup"),("baking_powder",6,"1.5 tsp"),("cinnamon",6,"2 tsp"),
      ("brown_sugar",20,"1.5 tbsp"),("greek_yogurt_nonfat",100,"scant 1/2 cup, for the glaze"),("maple_syrup",15,"1 tbsp")],
 steps=["Oven to 350F. Blend oats, eggs, protein powder, milk, baking powder and half the cinnamon into a batter.",
        "Pour into a greased dish. Swirl the brown sugar and remaining cinnamon through the top with a knife.",
        "Bake 25 minutes. Mix the yogurt with maple syrup and spread it over while warm as the glaze."],
 storage="4 days refrigerated, 2 months frozen in portions.",
 prep_notes="The yogurt glaze is doing real protein work, not just decoration.",
 subs=["Casein instead of whey makes it denser and moister."],
 variations=["Add raisins and chopped walnuts to the swirl."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","SWEET"]),

dict(id="B-24", cat="Breakfast", name="Spinach and Feta Egg White Frittata",
 servings=2, prep=8, cook=22,
 ing=[("egg_white",330,"10 large whites"),("egg_whole",100,"2 large"),("spinach",150,"5 packed cups"),
      ("feta",70,"~1/2 cup crumbled"),("onion",70,"1/2 medium"),("cherry_tomatoes",120,"~12"),
      ("olive_oil",14,"1 tbsp"),("spice_generic",2,"oregano, black pepper")],
 steps=["Fry the onion in oil in an ovenproof pan 5 minutes, add spinach and wilt.",
        "Pour over the beaten eggs and whites, scatter feta and halved tomatoes.",
        "Cook 3 minutes on the hob, then 15 minutes at 375F until set in the middle."],
 storage="4 days. Eats well cold, which makes it a work lunch.",
 prep_notes="Roughly 50 g of protein for 500 calories across the whole pan.",
 subs=["All whole eggs if you want the fat and choline instead of the protein density."],
 variations=["Add roasted red pepper and olives."],
 manual_tags=["MEAL PREP","LOW CALORIE","HIGH SATIETY"]),

dict(id="B-25", cat="Breakfast", name="Coconut Mango Overnight Oats",
 servings=1, prep=5, cook=0,
 ing=[("oats_gf_dry",55,"2/3 cup dry"),("coconut_milk_light",120,"1/2 cup"),("milk_skim",100,"scant 1/2 cup"),
      ("whey_isolate",30,"1 scoop vanilla"),("mango_frozen",120,"3/4 cup"),("chia",12,"1 tbsp"),
      ("hemp_hearts",12,"1.5 tbsp")],
 steps=["Whisk the liquids with the protein powder until smooth, then stir in oats and chia.",
        "Layer the mango on top and refrigerate overnight.",
        "Add hemp hearts in the morning."],
 storage="4 days.", prep_notes="",
 subs=["All skim milk cuts ~80 kcal and most of the coconut flavour."],
 variations=["Pineapple instead of mango."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="B-26", cat="Breakfast", name="Silken Tofu Chocolate Breakfast Pudding",
 servings=1, prep=5, cook=0,
 ing=[("tofu_silken",250,"~1 cup"),("cocoa_powder",15,"3 tbsp"),("whey_isolate",30,"1 scoop chocolate"),
      ("banana",100,"1 medium"),("maple_syrup",20,"1 tbsp"),("almond_butter",16,"1 tbsp"),("milk_skim",60,"1/4 cup")],
 steps=["Blend everything on high for a full minute. Silken tofu needs longer than you expect to go completely smooth.",
        "Chill 30 minutes if you have time, it firms up.",
        "Top with anything crunchy."],
 storage="3 days.", prep_notes="Silken tofu is the cheapest way to make something taste like dessert while carrying real protein.",
 subs=["Greek yogurt instead of tofu, higher leucine, different texture."],
 variations=["Add espresso powder for a mocha version."],
 manual_tags=["QUICK","SWEET","VEGAN OPTION"]),

dict(id="B-27", cat="Breakfast", name="Protein Oat Muffins",
 servings=6, prep=12, cook=22,
 ing=[("gf_oat_flour",180,"1.75 cups"),("whey_isolate",60,"2 scoops vanilla"),("egg_whole",150,"3 large"),
      ("greek_yogurt_nonfat",200,"3/4 cup"),("banana",180,"1.5 large, mashed"),("baking_powder",8,"2 tsp"),
      ("honey",50,"2.5 tbsp"),("choc_chips_mini",40,"1/4 cup"),("cinnamon",3,"1 tsp")],
 steps=["Oven to 350F, line a 6-cup muffin tin.",
        "Mix wet, mix dry, combine, do not overmix. Overmixed protein batter goes tough.",
        "Divide, top with chips, bake 20 to 22 minutes until a skewer comes out clean."],
 storage="4 days at room temperature, 3 months frozen. Microwave 30 seconds from frozen.",
 prep_notes="A batch replaces the bars you buy at work.",
 subs=["Blend GF rolled oats to make your own oat flour for a third of the price."],
 variations=["Blueberry lemon, or pumpkin spice with 150 g pumpkin puree."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","BUDGET FRIENDLY"]),

dict(id="B-28", cat="Breakfast", name="Avocado Egg Toast with Hemp",
 servings=1, prep=4, cook=6,
 ing=[("gf_bread",70,"2 slices"),("avocado",80,"1/2 large"),("egg_whole",150,"3 large"),
      ("hemp_hearts",15,"1.5 tbsp"),("lemon_juice",8,"1.5 tsp"),("spice_generic",2,"chili flakes, salt, pepper")],
 steps=["Toast the bread hard.",
        "Mash the avocado with lemon, salt and chili directly onto the toast.",
        "Fry or poach the eggs and lay them over. Scatter hemp hearts."],
 storage="Eat fresh.", prep_notes="Hemp hearts add 5 g of protein and a meaningful ALA dose for almost no effort.",
 subs=["Two whole eggs plus three whites raises protein and cuts fat."],
 variations=["Add feta and tomato."],
 manual_tags=["QUICK","HIGH HEALTHY FAT"]),

dict(id="B-29", cat="Breakfast", name="Warm Quinoa Breakfast Porridge",
 servings=1, prep=4, cook=8,
 ing=[("quinoa_cooked",250,"1.25 cups cooked"),("milk_2",200,"3/4 cup"),("whey_isolate",25,"3/4 scoop vanilla"),
      ("blueberries",100,"2/3 cup"),("almonds",20,"~16"),("maple_syrup",15,"1 tbsp"),("cinnamon",2,"1/2 tsp")],
 steps=["Simmer the cooked quinoa in the milk for 6 minutes until it thickens and goes creamy.",
        "Off the heat, cool for a minute, then stir in the protein powder.",
        "Top with berries, almonds, syrup and cinnamon."],
 storage="3 days.", prep_notes="Uses leftover quinoa from a dinner. Quinoa is a carb here, not the protein.",
 subs=["Rice works the same way."], variations=["Savory: skip the sweet elements, add egg and greens."],
 manual_tags=["QUICK","BUDGET FRIENDLY"]),

dict(id="B-30", cat="Breakfast", name="Freezer Breakfast Burritos",
 servings=6, prep=20, cook=15,
 ing=[("egg_whole",400,"8 large"),("egg_white",264,"8 whites"),("gf_wrap",360,"6 large GF wraps"),
      ("black_beans",400,"2 cups"),("cheddar",180,"1.5 cups shredded"),("bell_pepper",150,"1.25 peppers"),
      ("onion",100,"1 small"),("salsa",180,"3/4 cup"),("olive_oil",20,"1.5 tbsp"),
      ("spice_generic",4,"cumin, chili, paprika")],
 steps=["Fry the peppers and onion 6 minutes, add spices, then scramble the eggs and whites in with them. Pull them slightly underdone, they finish when reheated.",
        "Cool completely. Warm eggs make soggy burritos.",
        "Fill each wrap with egg, beans, cheese and salsa. Roll tight, wrap in foil, freeze."],
 storage="3 months frozen. Reheat from frozen: 2 minutes in the microwave wrapped in a damp paper towel, or 20 minutes at 350F in the foil.",
 prep_notes="Twenty minutes of work on a Sunday covers six work mornings. Highest-return prep item here for the way my week runs.",
 subs=["Corn tortillas are cheaper and naturally GF but do not roll as well. Make them into folded pockets instead."],
 variations=["Add potato for more calories, or tofu instead of some of the egg."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","TWO-MEAL-DAY FRIENDLY"]),

# ============================== LUNCH / DINNER ==============================
dict(id="L-23", cat="Lunch/Dinner", name="Crispy Tofu Katsu Rice Bowl",
 servings=1, prep=12, cook=14,
 ing=[("tofu_extrafirm",200,"~2/3 block"),("gf_oat_flour",40,"1/3 cup"),("egg_whole",50,"1 large"),
      ("rice_white_cooked",250,"1.25 cups"),("coleslaw_mix",100,"2 cups"),("ketchup",30,"2 tbsp"),
      ("soy_sauce_gf",10,"2 tsp"),("olive_oil",18,"1.5 tbsp"),("greek_yogurt_nonfat",40,"3 tbsp")],
 steps=["Press the tofu 10 minutes, slice into two flat slabs.",
        "Dredge in oat flour, then beaten egg, then oat flour again. The double coat is what gives you crust.",
        "Shallow-fry in oil 4 minutes per side until deep golden. Rest on a rack, not paper, so the bottom stays crisp.",
        "Mix ketchup and tamari for a quick katsu sauce. Dress the slaw with the yogurt."],
 storage="2 days. Reheat in a hot oven, never a microwave.",
 prep_notes="", subs=["Crushed GF cornflakes make a better crust if you have them.","Air fryer at 400F, 14 minutes."],
 variations=["Chicken cutlet version in the M section style."],
 manual_tags=["HIGH SATIETY"]),

dict(id="L-24", cat="Lunch/Dinner", name="Lentil Bolognese with GF Pasta",
 servings=2, prep=8, cook=30,
 ing=[("lentils",350,"1.75 cups cooked"),("gf_pasta_dry",160,"~5.5 oz dry"),("marinara",350,"1.5 cups"),
      ("onion",100,"1 small"),("carrot",100,"2 medium"),("mushrooms",150,"~12"),("garlic",10,"3 cloves"),
      ("olive_oil",18,"1.5 tbsp"),("parmesan",40,"1/3 cup"),("spice_generic",3,"oregano, bay, chili")],
 steps=["Finely dice onion, carrot and mushroom. Fry in oil for 10 minutes until they collapse and start to brown. This step is the whole flavour of the dish, do not rush it.",
        "Add garlic and herbs for 1 minute, then lentils and marinara plus 150 ml water.",
        "Simmer 20 minutes uncovered. Boil the pasta and combine. Parmesan at the table."],
 storage="Sauce 5 days refrigerated, 3 months frozen. Cook pasta fresh.",
 prep_notes="Make a quadruple batch of sauce and freeze it flat in bags.",
 subs=["Lentil or chickpea pasta pushes protein up by ~18 g per serving."],
 variations=["Add a spoon of ricotta at the table."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","BUDGET FRIENDLY","HIGH FIBER"]),

dict(id="L-25", cat="Lunch/Dinner", name="Black Bean Enchilada Skillet",
 servings=2, prep=8, cook=18,
 ing=[("black_beans",400,"2 cups"),("corn_tortilla",156,"6 small, torn"),("salsa_verde",200,"3/4 cup"),
      ("cheddar",100,"3/4 cup shredded"),("cottage_cheese_2",200,"scant 1 cup"),("sweet_corn",120,"3/4 cup"),
      ("onion",80,"1 small"),("olive_oil",10,"2 tsp"),("spice_generic",4,"cumin, chili, oregano")],
 steps=["Fry the onion in oil 5 minutes, add spices, beans, corn and salsa verde. Simmer 5 minutes.",
        "Blend the cottage cheese smooth and stir half of it through.",
        "Fold in the torn tortillas, top with the rest of the cottage cheese and the cheddar.",
        "Broil 5 minutes until bubbling."],
 storage="4 days.", prep_notes="Corn tortillas are naturally gluten-free, cheap, and higher in leucine than most grains.",
 subs=["Red enchilada sauce.","Add tofu or turkey for more protein."],
 variations=["Top with avocado and pickled jalapeno."],
 manual_tags=["MEAL PREP","HIGH FIBER","BUDGET FRIENDLY"]),

dict(id="L-26", cat="Lunch/Dinner", name="Sesame Ginger Edamame Noodle Bowl",
 servings=1, prep=8, cook=10,
 ing=[("gf_pasta_dry",85,"~3 oz dry, or rice noodles"),("edamame_shelled",180,"1.25 cups"),
      ("carrot",80,"1.5 medium, shredded"),("bell_pepper",80,"1/2 pepper"),("tahini",20,"1 tbsp"),
      ("soy_sauce_gf",20,"4 tsp tamari"),("lemon_juice",15,"1 tbsp lime"),("sriracha",10,"2 tsp"),
      ("honey",10,"1.5 tsp"),("cucumber",80,"1/3 cucumber")],
 steps=["Cook the noodles, rinse under cold water so they do not clump.",
        "Whisk tahini, tamari, lime, sriracha and honey with 2 tbsp water into a pourable dressing.",
        "Toss everything together cold."],
 storage="3 days. Better cold, which makes it a genuine packed lunch.",
 prep_notes="Verify tamari is certified GF.",
 subs=["Peanut butter instead of tahini.","Add tofu for another 20 g protein."],
 variations=["Add cabbage and fresh herbs."],
 manual_tags=["MEAL PREP","NO-COOK","HIGH FIBER"]),

dict(id="L-27", cat="Lunch/Dinner", name="Loaded Burrito with GF Wrap",
 servings=1, prep=8, cook=6,
 ing=[("gf_wrap",70,"1 large"),("rice_brown_cooked",180,"scant 1 cup"),("black_beans",150,"3/4 cup"),
      ("tofu_extrafirm",150,"1/2 block"),("cheddar",40,"1/3 cup"),("salsa",60,"1/4 cup"),
      ("greek_yogurt_nonfat",60,"1/4 cup"),("avocado",50,"1/4 large"),("olive_oil",7,"1/2 tbsp"),
      ("spice_generic",3,"cumin, chili, paprika")],
 steps=["Crumble and fry the tofu with the spices in oil for 6 minutes until the edges catch.",
        "Warm the wrap 15 seconds so it folds without cracking.",
        "Layer rice, beans, tofu, cheese, salsa, yogurt and avocado in a line, not spread out. Fold the ends in, then roll tight.",
        "Sear the seam side down in a dry pan 1 minute to seal it."],
 storage="Eat fresh, or wrap in foil and refrigerate 2 days.",
 prep_notes="Greek yogurt does the job of sour cream at four times the protein.",
 subs=["Two corn tortillas instead of the GF wrap, cheaper and naturally GF."],
 variations=["Add pickled jalapeno and hot sauce."],
 manual_tags=["HIGH CALORIE","HIGH SATIETY"]),

dict(id="L-28", cat="Lunch/Dinner", name="Maple Mustard Tempeh Sheet Pan",
 servings=1, prep=8, cook=25,
 ing=[("tempeh",150,"~5 oz"),("sweet_potato",250,"1 large, cubed"),("broccoli_cooked",150,"1.5 cups"),
      ("mustard_yellow",20,"4 tsp"),("maple_syrup",20,"1 tbsp"),("olive_oil",14,"1 tbsp"),
      ("soy_sauce_gf",10,"2 tsp"),("spice_generic",2,"smoked paprika, pepper")],
 steps=["Steam the tempeh 8 minutes first. This removes the bitterness people blame tempeh for.",
        "Whisk mustard, maple, tamari, oil and paprika. Toss the sliced tempeh and sweet potato in it.",
        "Roast at 425F for 18 minutes, add the broccoli, roast 8 more."],
 storage="4 days.", prep_notes="Tempeh is fermented, higher in fiber and protein than tofu, and easier on digestion.",
 subs=["Extra-firm tofu, no steaming needed."],
 variations=["Add pecans or a grain to bulk it out."],
 manual_tags=["MEAL PREP","HIGH FIBER"]),

dict(id="L-29", cat="Lunch/Dinner", name="Baked Ziti with Ricotta",
 servings=3, prep=12, cook=30,
 ing=[("gf_pasta_dry",240,"~8 oz dry"),("marinara",500,"2 cups"),("ricotta_ps",350,"1.5 cups"),
      ("mozzarella_ps",180,"1.5 cups shredded"),("parmesan",50,"1/2 cup"),("spinach",150,"5 packed cups"),
      ("egg_whole",50,"1 large"),("garlic",10,"3 cloves"),("spice_generic",3,"oregano, chili flakes")],
 steps=["Boil the pasta 2 minutes short of the box time. GF pasta turns to paste if you fully cook it before baking.",
        "Mix ricotta with the egg, parmesan, wilted spinach and garlic. The egg is what stops the ricotta going watery.",
        "Layer pasta, sauce, ricotta mixture, repeat. Mozzarella on top.",
        "Bake at 375F for 30 minutes, rest 10 before cutting."],
 storage="4 days refrigerated, 2 months frozen.",
 prep_notes="Roughly 45 g protein per serving from dairy alone.",
 subs=["Blended cottage cheese instead of ricotta, higher protein, slightly looser."],
 variations=["Add lentils to the sauce for fiber and another 8 g of protein."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","HIGH CALORIE"]),

dict(id="L-30", cat="Lunch/Dinner", name="Thai Red Curry Tofu",
 servings=2, prep=10, cook=18,
 ing=[("tofu_extrafirm",300,"1 block"),("coconut_milk_light",300,"1.25 cups"),("curry_paste",40,"2.5 tbsp"),
      ("rice_white_cooked",400,"2 cups"),("bell_pepper",150,"1.25 peppers"),("zucchini",150,"1 medium"),
      ("peas_frozen",100,"2/3 cup"),("olive_oil",14,"1 tbsp"),("lemon_juice",15,"1 tbsp lime"),
      ("soy_sauce_gf",15,"1 tbsp tamari")],
 steps=["Press and cube the tofu, fry hard in oil until golden on at least two sides. Remove.",
        "Fry the curry paste 1 minute until it smells strong, then add coconut milk and simmer 5 minutes.",
        "Add vegetables, cook 6 minutes, return the tofu, finish with lime and tamari. Serve over rice."],
 storage="4 days. Improves overnight.",
 prep_notes="Check the curry paste for wheat and shrimp paste. Many contain both. Thai Kitchen brand is commonly GF and vegetarian, but read your jar.",
 subs=["Full-fat coconut milk adds ~150 kcal per serving if you need them."],
 variations=["Green curry, or add sweet potato."],
 manual_tags=["MEAL PREP","HIGH CALORIE"]),

dict(id="L-31", cat="Lunch/Dinner", name="Mediterranean Chickpea Tahini Bowl",
 servings=1, prep=10, cook=0,
 ing=[("chickpeas",250,"1.25 cups"),("quinoa_cooked",200,"1 cup"),("cucumber",100,"1/3 cucumber"),
      ("cherry_tomatoes",120,"~12"),("feta",50,"~1/3 cup"),("tahini",25,"1.5 tbsp"),
      ("lemon_juice",25,"5 tsp"),("olive_oil",10,"2 tsp"),("spinach",60,"2 packed cups"),
      ("spice_generic",2,"za'atar, sumac, pepper")],
 steps=["Whisk tahini, lemon and 3 tbsp water until it goes from seized to smooth. It will look broken first; keep whisking.",
        "Build the bowl cold with everything else.",
        "Pour the dressing over at the end."],
 storage="3 days, dressing separate.", prep_notes="Entirely no-cook if you have cooked quinoa on hand.",
 subs=["Rice instead of quinoa.","Hummus instead of tahini dressing."],
 variations=["Add olives, roasted red pepper and red onion."],
 manual_tags=["NO-COOK","MEAL PREP","HIGH FIBER"]),

dict(id="L-32", cat="Lunch/Dinner", name="Egg Curry with Rice",
 servings=2, prep=8, cook=20,
 ing=[("egg_whole",300,"6 large, hard-boiled"),("marinara",300,"1.25 cups"),("onion",100,"1 small"),
      ("garlic",10,"3 cloves"),("coconut_milk_light",150,"2/3 cup"),("rice_white_cooked",400,"2 cups"),
      ("spinach",100,"3 packed cups"),("olive_oil",14,"1 tbsp"),("spice_generic",5,"garam masala, cumin, turmeric, chili")],
 steps=["Boil the eggs 9 minutes, cool in ice water, peel and halve.",
        "Fry onion 8 minutes until browned, add garlic and spices for 1 minute.",
        "Add marinara and coconut milk, simmer 8 minutes, stir in spinach.",
        "Lay the eggs in yolk-side up and spoon sauce over. Serve on rice."],
 storage="3 days. Keep the eggs whole in the sauce.",
 prep_notes="Six eggs is roughly 38 g of protein with high leucine and a full day of choline.",
 subs=["Add paneer or tofu for more protein."],
 variations=["Add potato and peas."],
 manual_tags=["LEUCINE PRIORITY","BUDGET FRIENDLY","MEAL PREP"]),

dict(id="L-33", cat="Lunch/Dinner", name="Three-Bean Vegetarian Chili",
 servings=3, prep=10, cook=35,
 ing=[("kidney_beans",300,"1.5 cups"),("black_beans",300,"1.5 cups"),("pinto_beans",250,"1.25 cups"),
      ("marinara",350,"1.5 cups"),("onion",120,"1 medium"),("bell_pepper",150,"1.25 peppers"),
      ("sweet_corn",120,"3/4 cup"),("olive_oil",14,"1 tbsp"),("cocoa_powder",6,"1 tbsp"),
      ("spice_generic",6,"chili powder, cumin, oregano, smoked paprika"),("cheddar",90,"3/4 cup, to serve")],
 steps=["Fry onion and pepper in oil 8 minutes.",
        "Add spices and the cocoa powder for 1 minute. Cocoa in chili adds depth without tasting like chocolate.",
        "Add beans, corn, marinara and 300 ml water. Simmer 25 minutes uncovered.",
        "Top with cheddar."],
 storage="5 days, 3 months frozen.",
 prep_notes="Roughly 25 g fiber a serving. Start with half a portion if that is a jump from normal.",
 subs=["Add lentils or turkey.","Skip the cheese for a vegan version."],
 variations=["Serve over rice or a baked potato."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","BUDGET FRIENDLY","HIGH FIBER","HIGH SATIETY"]),

dict(id="L-34", cat="Lunch/Dinner", name="Mushroom Stroganoff with GF Pasta",
 servings=2, prep=8, cook=20,
 ing=[("mushrooms",400,"~32, sliced"),("gf_pasta_dry",160,"~5.5 oz dry"),("greek_yogurt_nonfat",250,"1 cup"),
      ("onion",100,"1 small"),("garlic",10,"3 cloves"),("olive_oil",18,"1.5 tbsp"),
      ("mustard_yellow",15,"1 tbsp"),("parmesan",40,"1/3 cup"),("spice_generic",3,"paprika, thyme, pepper")],
 steps=["Fry the mushrooms in a hot dry pan first, in batches, until they release water and then brown. Crowding them is why stroganoff usually tastes of nothing.",
        "Add oil, onion and garlic, cook 5 minutes. Add paprika and mustard.",
        "Kill the heat completely, then stir in the yogurt. Yogurt added over heat will split.",
        "Toss with the cooked pasta and parmesan."],
 storage="3 days. Reheat gently.",
 prep_notes="Yogurt off the heat is the technique that makes this work.",
 subs=["Add white beans or tofu for another 15 g protein.","Sour cream if you do not care about the protein."],
 variations=["Add a splash of GF stock and dill."],
 manual_tags=["QUICK","LOW CALORIE"]),

dict(id="L-35", cat="Lunch/Dinner", name="Lentil Shepherd's Pie with Sweet Potato",
 servings=3, prep=15, cook=35,
 ing=[("lentils",450,"2.25 cups cooked"),("sweet_potato",600,"2 large"),("carrot",150,"3 medium"),
      ("onion",120,"1 medium"),("peas_frozen",150,"1 cup"),("marinara",250,"1 cup"),
      ("cheddar",80,"2/3 cup"),("olive_oil",20,"1.5 tbsp"),("milk_2",80,"1/3 cup"),
      ("spice_generic",4,"thyme, rosemary, bay, pepper")],
 steps=["Boil the sweet potato 15 minutes, mash with the milk, half the oil and seasoning.",
        "Fry onion and carrot in the rest of the oil 8 minutes, add lentils, peas, marinara and herbs. Simmer 10 minutes until thick.",
        "Spread the mash over, fork the top so it crisps, scatter cheddar.",
        "Bake 25 minutes at 400F."],
 storage="4 days, 2 months frozen.",
 prep_notes="Vitamin A, fiber, iron and protein in one dish. One of the more nutrient-dense meals here.",
 subs=["Regular potato.","Add tofu crumble or turkey."],
 variations=["Add mushrooms for depth."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","HIGH FIBER","HIGH MICRONUTRIENT DENSITY"]),

dict(id="L-36", cat="Lunch/Dinner", name="Tofu Larb Lettuce Cups",
 servings=1, prep=10, cook=10,
 ing=[("tofu_extrafirm",250,"~5/6 block, crumbled"),("rice_white_cooked",150,"3/4 cup"),
      ("lemon_juice",30,"2 tbsp lime"),("soy_sauce_gf",20,"4 tsp tamari"),("sriracha",12,"2.5 tsp"),
      ("onion",40,"3 tbsp, red"),("carrot",60,"1 medium, shredded"),("olive_oil",10,"2 tsp"),
      ("spice_generic",2,"chili flakes, mint, cilantro"),("cucumber",80,"1/3 cucumber")],
 steps=["Crumble and fry the tofu hard in oil, 8 minutes, until genuinely browned and dry at the edges.",
        "Off the heat, toss with lime, tamari, sriracha, red onion and herbs.",
        "Serve in lettuce leaves with rice and cucumber on the side."],
 storage="Tofu mixture 4 days. Assemble fresh.",
 prep_notes="Lime and herbs are doing the work. Do not skimp on either.",
 subs=["Tempeh or ground turkey."], variations=["Add toasted rice powder if you can find GF."],
 manual_tags=["MEAL PREP","LOW CALORIE","QUICK"]),

dict(id="L-37", cat="Lunch/Dinner", name="Corn and Black Bean Quesadillas",
 servings=1, prep=6, cook=8,
 ing=[("corn_tortilla",104,"4 small"),("black_beans",180,"scant 1 cup"),("sweet_corn",100,"2/3 cup"),
      ("cheddar",60,"1/2 cup"),("cottage_cheese_2",120,"1/2 cup"),("salsa",60,"1/4 cup"),
      ("olive_oil",10,"2 tsp"),("spice_generic",3,"cumin, chili")],
 steps=["Mash half the beans with the spices so the filling holds together.",
        "Blend the cottage cheese smooth and mix with the cheddar.",
        "Fill two pairs of tortillas, dry-fry in a pan with a little oil, 3 minutes per side, pressing down with a spatula."],
 storage="2 days. Reheat in a pan.",
 prep_notes="Blended cottage cheese in a quesadilla adds 14 g of protein and nobody can tell.",
 subs=["GF wraps, larger and more expensive."],
 variations=["Add sauteed peppers and onions."],
 manual_tags=["QUICK","BUDGET FRIENDLY"]),

dict(id="L-38", cat="Lunch/Dinner", name="Roasted Vegetable and Feta Grain Bowl",
 servings=1, prep=10, cook=28,
 ing=[("sweet_potato",200,"1 medium"),("zucchini",150,"1 medium"),("bell_pepper",120,"1 pepper"),
      ("chickpeas",180,"scant 1 cup"),("rice_brown_cooked",200,"1 cup"),("feta",50,"~1/3 cup"),
      ("olive_oil",18,"1.5 tbsp"),("lemon_juice",15,"1 tbsp"),("spice_generic",3,"oregano, cumin, paprika"),
      ("greek_yogurt_nonfat",80,"1/3 cup")],
 steps=["Toss the vegetables and chickpeas in oil and spices. Roast at 425F for 25 minutes, turning once.",
        "The chickpeas should be crisp at the edges. If they are not, give them 5 more minutes.",
        "Build over rice with feta, lemon and a spoon of yogurt."],
 storage="4 days.", prep_notes="Roast a double tray of vegetables on Sunday and this becomes a five-minute meal.",
 subs=["Any vegetable that roasts.","Quinoa or potato instead of rice."],
 variations=["Add a tahini drizzle or harissa."],
 manual_tags=["MEAL PREP","HIGH FIBER","HIGH MICRONUTRIENT DENSITY"]),

dict(id="L-39", cat="Lunch/Dinner", name="Garlic White Bean and Kale Skillet",
 servings=1, prep=6, cook=14,
 ing=[("kidney_beans",300,"1.5 cups, or cannellini"),("kale",150,"4 packed cups"),("garlic",12,"4 cloves"),
      ("olive_oil",20,"1.5 tbsp"),("parmesan",30,"1/4 cup"),("lemon_juice",20,"4 tsp"),
      ("gf_bread",70,"2 slices, to serve"),("spice_generic",3,"chili flakes, rosemary, pepper")],
 steps=["Fry the sliced garlic in the oil over low heat 3 minutes until pale gold, not brown. Burnt garlic ruins the dish.",
        "Add kale and a splash of water, cover 4 minutes.",
        "Add beans, mash a third of them against the pan to thicken it, cook 5 more minutes.",
        "Lemon and parmesan at the end. Serve over toast."],
 storage="3 days.", prep_notes="Nine minutes of actual work. Good for a night you have nothing left.",
 subs=["Spinach instead of kale, 1 minute instead of 4."],
 variations=["Add a fried egg, or sausage in the M-section style."],
 manual_tags=["QUICK","HIGH FIBER","BUDGET FRIENDLY"]),

dict(id="L-40", cat="Lunch/Dinner", name="Zucchini and Cottage Cheese Lasagna",
 servings=3, prep=20, cook=40,
 ing=[("zucchini",600,"4 medium, sliced lengthwise"),("cottage_cheese_2",500,"2 cups"),
      ("marinara",450,"2 cups"),("mozzarella_ps",180,"1.5 cups"),("egg_whole",100,"2 large"),
      ("parmesan",50,"1/2 cup"),("spinach",150,"5 packed cups"),("garlic",10,"3 cloves"),
      ("spice_generic",3,"oregano, basil, pepper")],
 steps=["Slice the zucchini thin, salt it, lay it on paper towels for 20 minutes and blot hard. Skip this and you get soup.",
        "Blend the cottage cheese with the eggs, parmesan, garlic and wilted spinach.",
        "Layer zucchini, sauce, cheese mixture, repeat three times. Mozzarella on top.",
        "Bake 40 minutes at 375F, rest 15 minutes before cutting."],
 storage="4 days. Better on day two once it sets.",
 prep_notes="Roughly 45 g protein per serving for under 450 calories. The highest protein density main course in the catalog.",
 subs=["Ricotta instead of cottage cheese, higher fat, lower protein.","GF lasagna sheets for a conventional version."],
 variations=["Add mushrooms or lentils to the sauce."],
 manual_tags=["MEAL PREP","LOW CALORIE","LEUCINE PRIORITY","HIGH SATIETY"]),

# ============================== SNACKS ==============================
dict(id="S-43", cat="Snack", name="Marinated Tofu Cubes",
 servings=2, prep=10, cook=25,
 ing=[("tofu_extrafirm",300,"1 block"),("soy_sauce_gf",25,"5 tsp tamari"),("olive_oil",14,"1 tbsp"),
      ("lemon_juice",15,"1 tbsp"),("spice_generic",4,"garlic powder, onion powder, sesame, pepper")],
 steps=["Press the tofu 15 minutes, cube it.","Toss with everything, marinate 20 minutes or overnight.",
        "Bake at 400F for 25 minutes, turning once, until chewy at the edges."],
 storage="5 days. Eat cold from the fridge.",
 prep_notes="A container of these in the fridge is the vegetarian equivalent of sliced deli meat.",
 subs=["Air fryer 380F for 15 minutes."], variations=["Buffalo, teriyaki, or chili lime."],
 manual_tags=["MEAL PREP","SAVORY","LOW CALORIE"]),

dict(id="S-44", cat="Snack", name="Protein Rice Pudding",
 servings=1, prep=3, cook=8,
 ing=[("rice_white_cooked",200,"1 cup, cooked"),("milk_2",250,"1 cup"),("whey_isolate",25,"3/4 scoop vanilla"),
      ("raisins",25,"2.5 tbsp"),("cinnamon",3,"3/4 tsp"),("honey",12,"2 tsp")],
 steps=["Simmer the rice in the milk 8 minutes, stirring, until it thickens.",
        "Cool 2 minutes off the heat, then stir in the protein powder.",
        "Add raisins, cinnamon and honey."],
 storage="3 days. Thickens cold, loosen with milk.",
 prep_notes="Uses leftover rice.", subs=["Coconut milk for a richer version."],
 variations=["Cardamom and pistachio."],
 manual_tags=["BUDGET FRIENDLY","SWEET","QUICK"]),

dict(id="S-45", cat="Snack", name="Whipped Chocolate Protein Mousse",
 servings=1, prep=5, cook=0,
 ing=[("greek_yogurt_nonfat",200,"3/4 cup"),("casein_powder",25,"3/4 scoop chocolate"),
      ("cocoa_powder",8,"1.5 tbsp"),("milk_skim",60,"1/4 cup"),("maple_syrup",12,"2 tsp"),
      ("dark_chocolate_70",10,"~1/3 oz, shaved")],
 steps=["Whip the yogurt, casein, cocoa, milk and syrup with a hand mixer or a fork for 2 minutes. Whipping is what makes it mousse and not pudding.",
        "Chill 20 minutes.","Shave the dark chocolate over."],
 storage="3 days.", prep_notes="", subs=["Whey stays thinner; casein is the right choice."],
 variations=["Add espresso powder or orange zest."],
 manual_tags=["SWEET","LEUCINE PRIORITY","PRE-SLEEP"]),

dict(id="S-46", cat="Snack", name="Rosemary Roasted Almonds",
 servings=4, prep=3, cook=12,
 ing=[("almonds",200,"1.5 cups"),("olive_oil",10,"2 tsp"),("spice_generic",3,"rosemary, salt, chili flakes")],
 steps=["Toss the almonds in oil and seasoning.","Roast at 325F for 12 minutes, shaking once. Low heat, or they burn inside before they colour outside.",
        "Cool fully before storing, or they go soft."],
 storage="3 weeks airtight.",
 prep_notes="Portion into 50 g bags immediately. Nuts eaten from the container are how people accidentally eat 800 calories.",
 subs=["Cashews or walnuts."], variations=["Sweet: cinnamon and a little maple, roasted at 300F."],
 manual_tags=["MEAL PREP","HIGH CALORIE","HIGH HEALTHY FAT"]),

dict(id="S-47", cat="Snack", name="Cottage Cheese Tomato Toast",
 servings=1, prep=4, cook=2,
 ing=[("gf_bread",70,"2 slices"),("cottage_cheese_2",180,"3/4 cup"),("tomato",120,"1 medium"),
      ("olive_oil",10,"2 tsp"),("spice_generic",2,"black pepper, chili flakes, basil")],
 steps=["Toast the bread hard.","Spread the cottage cheese thickly, straight from the tub, not blended.",
        "Top with sliced tomato, olive oil, salt and plenty of pepper."],
 storage="Eat fresh.", prep_notes="Three minutes, 27 g of protein.",
 subs=["Ricotta, or blended cottage cheese if the curds bother you."],
 variations=["Add everything-bagel seasoning, checking it is GF."],
 manual_tags=["QUICK","SAVORY","HIGH SATIETY"]),

dict(id="S-48", cat="Snack", name="Protein Oat Waffle",
 servings=1, prep=5, cook=6,
 ing=[("gf_oat_flour",50,"1/2 cup"),("whey_isolate",25,"3/4 scoop"),("egg_whole",50,"1 large"),
      ("greek_yogurt_nonfat",80,"1/3 cup"),("milk_skim",60,"1/4 cup"),("baking_powder",4,"1 tsp"),
      ("sugar_free_syrup",25,"2 tbsp")],
 steps=["Whisk everything into a thick batter. Rest it 5 minutes so the oat flour hydrates.",
        "Cook in a hot waffle iron 5 to 6 minutes without opening it early.",
        "Syrup over the top."],
 storage="Freeze extras and toast from frozen.",
 prep_notes="Make six at once on a Sunday and toast them through the week.",
 subs=["Pancakes in a pan if you have no waffle iron."],
 variations=["Add cocoa or blueberries to the batter."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","SWEET"]),

dict(id="S-49", cat="Snack", name="Carrot Cake Protein Balls",
 servings=6, prep=15, cook=0,
 ing=[("oats_gf_dry",120,"1.5 cups"),("carrot",150,"3 medium, finely grated"),("dates_medjool",120,"~5 dates"),
      ("whey_isolate",45,"1.5 scoops vanilla"),("walnuts",60,"1/2 cup"),("raisins",40,"1/3 cup"),
      ("cinnamon",4,"1.25 tsp"),("almond_butter",40,"2.5 tbsp")],
 steps=["Squeeze the grated carrot dry in a towel.",
        "Process the oats and walnuts to a coarse meal, then add everything else and process until it clumps.",
        "Roll into 12 balls."],
 storage="1 week refrigerated, 3 months frozen.",
 prep_notes="", subs=["Peanut butter instead of almond butter."],
 variations=["Roll in desiccated coconut."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","HIGH FIBER"]),

dict(id="S-50", cat="Snack", name="Baked Tofu Nuggets with Yogurt Dip",
 servings=2, prep=12, cook=25,
 ing=[("tofu_extrafirm",300,"1 block"),("gf_oat_flour",50,"1/2 cup"),("nutritional_yeast",20,"1/4 cup"),
      ("egg_white",66,"2 whites"),("olive_oil",14,"1 tbsp"),("greek_yogurt_nonfat",120,"1/2 cup"),
      ("sriracha",15,"1 tbsp"),("spice_generic",4,"paprika, garlic powder, onion powder, pepper")],
 steps=["Press and tear the tofu into nugget-sized pieces. Torn edges hold coating better than cut ones.",
        "Dip in egg white, then in the oat flour, yeast and spice mixture.",
        "Bake at 425F for 25 minutes, turning once, with the oil drizzled over.",
        "Mix the yogurt and sriracha for the dip."],
 storage="3 days. Reheat in the oven.", prep_notes="",
 subs=["Air fryer 400F for 15 minutes."], variations=["Buffalo sauce toss after baking."],
 manual_tags=["MEAL PREP","SAVORY","HIGH SATIETY"]),

dict(id="S-51", cat="Snack", name="Smoky Pinto Bean Dip",
 servings=3, prep=6, cook=0,
 ing=[("pinto_beans",400,"2 cups"),("greek_yogurt_nonfat",120,"1/2 cup"),("lemon_juice",25,"5 tsp"),
      ("olive_oil",20,"1.5 tbsp"),("garlic",8,"2 cloves"),("spice_generic",4,"smoked paprika, cumin, chili"),
      ("carrot",200,"4 medium, as dippers")],
 steps=["Blend the beans, yogurt, lemon, oil, garlic and spices until smooth. Add water a spoon at a time to loosen.",
        "Taste for salt and acid. Bean dips almost always need more of both than you think.",
        "Serve with carrot sticks."],
 storage="5 days.", prep_notes="A third of the price of store hummus with more protein.",
 subs=["Any bean.","Tahini for a hummus-style version."],
 variations=["Add chipotle, or roasted red pepper."],
 manual_tags=["MEAL PREP","BUDGET FRIENDLY","HIGH FIBER","LOW CALORIE"]),

dict(id="S-52", cat="Snack", name="Kefir Berry Freezer Pops",
 servings=4, prep=8, cook=0,
 ing=[("kefir_plain",400,"1.75 cups"),("mixed_berries_frozen",250,"2 cups"),("whey_isolate",30,"1 scoop vanilla"),
      ("honey",30,"1.5 tbsp")],
 steps=["Blend everything smooth.","Pour into moulds or small paper cups with a stick.","Freeze 5 hours."],
 storage="2 months frozen.", prep_notes="",
 subs=["Greek yogurt thinned with milk."], variations=["Mango and lime."],
 manual_tags=["MEAL PREP","FREEZER FRIENDLY","LOW CALORIE"]),

dict(id="S-53", cat="Snack", name="Peanut Butter Stuffed Dates",
 servings=1, prep=3, cook=0,
 ing=[("dates_medjool",80,"4 dates"),("peanut_butter",32,"2 tbsp"),("dark_chocolate_70",15,"~1/2 oz"),
      ("salt",1,"flaky")],
 steps=["Split the dates, remove the pits, fill with peanut butter.",
        "Melt the chocolate and spoon it over. Sprinkle salt.",
        "Freeze 10 minutes to set."],
 storage="2 weeks refrigerated.",
 prep_notes="Roughly 60 g of fast carbohydrate. This is a good 30-minutes-before-training snack, not a general-purpose one.",
 subs=["Almond butter."], variations=["Add a crushed pretzel-style GF cracker for crunch."],
 manual_tags=["PRE-WORKOUT FRIENDLY","HIGH CALORIE","SWEET","QUICK"]),

dict(id="S-54", cat="Snack", name="Warm Cinnamon Apple with Yogurt",
 servings=1, prep=4, cook=5,
 ing=[("apple",200,"1 large"),("greek_yogurt_nonfat",200,"3/4 cup"),("cinnamon",3,"3/4 tsp"),
      ("walnuts",20,"~10 halves"),("maple_syrup",12,"2 tsp"),("oats_gf_dry",15,"3 tbsp")],
 steps=["Dice the apple, microwave 4 minutes with the cinnamon and a splash of water until soft.",
        "Toast the oats and walnuts in a dry pan 3 minutes.",
        "Spoon the warm apple over cold yogurt, top with the toasted crumble and syrup."],
 storage="Eat fresh.", prep_notes="Hot fruit over cold yogurt is a better texture than either alone.",
 subs=["Pear or frozen berries."], variations=["Add a scoop of protein powder to the yogurt."],
 manual_tags=["QUICK","HIGH SATIETY","SWEET"]),

dict(id="S-55", cat="Snack", name="Parmesan Roasted Broccoli",
 servings=2, prep=5, cook=22,
 ing=[("broccoli_cooked",400,"4 cups florets"),("parmesan",50,"1/2 cup"),("olive_oil",20,"1.5 tbsp"),
      ("garlic",10,"3 cloves"),("lemon_juice",15,"1 tbsp"),("spice_generic",2,"chili flakes, pepper")],
 steps=["Toss the florets in oil and sliced garlic. Spread them out; crowding steams them.",
        "Roast at 425F for 20 minutes until the edges char. Charred is the point, not a mistake.",
        "Parmesan and lemon straight out of the oven."],
 storage="3 days. Good cold.", prep_notes="Vitamin C, vitamin K and folate, and the only broccoli preparation most people will actually eat repeatedly.",
 subs=["Brussels sprouts or cauliflower."], variations=["Add almonds and chili oil."],
 manual_tags=["LOW CALORIE","SAVORY","HIGH MICRONUTRIENT DENSITY"]),

dict(id="S-56", cat="Snack", name="Protein Banana Muffin, Single Serve",
 servings=1, prep=4, cook=2,
 ing=[("banana",100,"1 medium"),("egg_whole",50,"1 large"),("gf_oat_flour",30,"1/4 cup"),
      ("whey_isolate",20,"2/3 scoop vanilla"),("baking_powder",3,"3/4 tsp"),("choc_chips_mini",10,"1 tbsp"),
      ("cinnamon",2,"1/2 tsp")],
 steps=["Mash the banana in a mug, beat in the egg.","Stir in the dry ingredients and chips.",
        "Microwave 90 seconds. Pull it while the top is just set."],
 storage="Eat fresh.", prep_notes="",
 subs=["Sugar-free syrup instead of chips."], variations=["Add peanut butter to the middle."],
 manual_tags=["QUICK","SWEET"]),

dict(id="S-57", cat="Snack", name="Hemp and Seed Yogurt Crunch Pot",
 servings=1, prep=3, cook=0,
 ing=[("skyr",200,"3/4 cup"),("hemp_hearts",20,"2 tbsp"),("pumpkin_seeds",20,"2.5 tbsp"),
      ("sunflower_seeds",15,"1.5 tbsp"),("honey",12,"2 tsp"),("blueberries",80,"1/2 cup")],
 steps=["Spoon the skyr into a jar.","Layer the seeds and berries over.","Honey to finish."],
 storage="Assemble in the morning, eat by evening. Seeds soften.",
 prep_notes="Zinc, magnesium and ALA in a snack you can make in three minutes. Two of those are ones I run low on.",
 subs=["Greek yogurt.","Any seed mix."],
 variations=["Savory: skip honey and berries, use olive oil, cucumber and za'atar."],
 manual_tags=["NO-COOK","QUICK","HIGH MICRONUTRIENT DENSITY","LEUCINE PRIORITY"]),

dict(id="S-58", cat="Snack", name="Refried Bean Nachos",
 servings=1, prep=5, cook=10,
 ing=[("corn_tortilla",78,"3 tortillas, cut into wedges"),("refried_beans_ff",200,"scant 1 cup"),
      ("cheddar",50,"scant 1/2 cup"),("greek_yogurt_nonfat",60,"1/4 cup"),("salsa",60,"1/4 cup"),
      ("pickled_jalapeno",25,"2.5 tbsp"),("spice_generic",2,"cumin, chili")],
 steps=["Bake the tortilla wedges at 400F for 8 minutes until crisp.",
        "Warm the beans with the spices, spread over the chips.",
        "Cheese on top, back in for 4 minutes. Yogurt, salsa and jalapeno at the end."],
 storage="Eat fresh.", prep_notes="Check that the refried beans are fat-free vegetarian; many brands use lard.",
 subs=["Black beans, mashed."], variations=["Add avocado and lime."],
 manual_tags=["QUICK","BUDGET FRIENDLY","SAVORY"]),

dict(id="S-59", cat="Snack", name="Lemon Protein Cheesecake Jars",
 servings=4, prep=15, cook=0,
 ing=[("greek_yogurt_nonfat",500,"2 cups"),("cottage_cheese_2",300,"1.25 cups"),("whey_isolate",60,"2 scoops vanilla"),
      ("lemon_juice",50,"3.5 tbsp"),("honey",60,"3 tbsp"),("oats_gf_dry",80,"1 cup"),
      ("almonds",60,"1/2 cup"),("butter",20,"1.5 tbsp")],
 steps=["Blitz the oats and almonds with the melted butter and a spoon of honey for the base. Press into four jars.",
        "Blend the yogurt, cottage cheese, protein powder, lemon and remaining honey until completely smooth. Two full minutes.",
        "Spoon over the base and chill 3 hours."],
 storage="4 days refrigerated.",
 prep_notes="Roughly 35 g of protein per jar. This is a dessert that does real work.",
 subs=["Ricotta instead of cottage cheese."], variations=["Berry swirl, or chocolate with cocoa instead of lemon."],
 manual_tags=["MEAL PREP","SWEET","LEUCINE PRIORITY","HIGH SATIETY"]),

dict(id="S-60", cat="Snack", name="Tamari Roasted Pumpkin Seeds",
 servings=3, prep=3, cook=14,
 ing=[("pumpkin_seeds",150,"1.25 cups"),("soy_sauce_gf",20,"4 tsp tamari"),("olive_oil",10,"2 tsp"),
      ("spice_generic",3,"smoked paprika, garlic powder, chili")],
 steps=["Toss the seeds with oil, tamari and spices.",
        "Roast at 325F for 12 to 14 minutes, shaking twice. They pop as they finish.",
        "Cool fully; they crisp as they cool."],
 storage="3 weeks airtight.",
 prep_notes="Best zinc and magnesium source in the catalog per gram, and both run low on a vegetarian gluten-free diet.",
 subs=["Sunflower seeds."], variations=["Sweet: maple and cinnamon."],
 manual_tags=["MEAL PREP","HIGH MICRONUTRIENT DENSITY","SAVORY"]),

# ============================== SDA MEAT / FISH ==============================
dict(id="M-17", cat="SDA Meat/Fish", name="Chicken and Vegetable Soup",
 servings=3, prep=12, cook=30,
 ing=[("chicken_breast",400,"~14 oz raw"),("carrot",200,"4 medium"),("onion",120,"1 medium"),
      ("potato",300,"2 medium"),("kale",120,"3 packed cups"),("peas_frozen",120,"3/4 cup"),
      ("olive_oil",18,"1.5 tbsp"),("lemon_juice",20,"4 tsp"),("spice_generic",4,"thyme, bay, pepper, salt")],
 steps=["Fry onion and carrot in oil 8 minutes.",
        "Add 1.2 litres of water or GF stock, the potato and herbs. Simmer 15 minutes.",
        "Add the whole chicken breasts, poach 12 minutes, then remove and shred. Poaching rather than boiling keeps it from going stringy.",
        "Return the chicken with the kale and peas, 3 more minutes. Lemon at the end."],
 storage="4 days, 3 months frozen.",
 prep_notes="Check any stock cube for gluten. Many contain wheat.",
 subs=["Chickpeas and white beans instead of chicken.","Add GF pasta or rice for calories."],
 variations=["Lemon and dill, or a curried version."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","FREEZER FRIENDLY","LOW CALORIE","HIGH SATIETY"]),

dict(id="M-18", cat="SDA Meat/Fish", name="Salmon Cakes with Yogurt Sauce",
 servings=2, prep=12, cook=12,
 ing=[("canned_salmon",300,"2 cans, drained"),("potato",250,"2 small, cooked and mashed"),
      ("egg_whole",50,"1 large"),("gf_oat_flour",40,"1/3 cup"),("onion",60,"1/2 small"),
      ("olive_oil",18,"1.5 tbsp"),("greek_yogurt_nonfat",120,"1/2 cup"),("lemon_juice",20,"4 tsp"),
      ("spice_generic",3,"dill, mustard powder, pepper")],
 steps=["Mash the salmon including the soft bones. That is where most of the calcium is and you will not notice them.",
        "Mix with potato, egg, oat flour, onion and seasoning. Chill 15 minutes so the cakes hold.",
        "Form 6 patties, fry in oil 4 minutes per side.",
        "Mix yogurt, lemon and dill for the sauce."],
 storage="3 days, 2 months frozen uncooked.",
 prep_notes="Canned salmon with bones is one of the best calcium plus vitamin D plus omega-3 combinations available, and it is cheap.",
 subs=["Canned tuna, far less omega-3 and no calcium."],
 variations=["Add capers and red onion."],
 manual_tags=["SDA-COMPATIBLE","OMEGA-3 RICH","MEAL PREP","HIGH MICRONUTRIENT DENSITY","FREEZER FRIENDLY"]),

dict(id="M-19", cat="SDA Meat/Fish", name="Turkey Meatballs in Marinara",
 servings=3, prep=15, cook=25,
 ing=[("ground_turkey_93",450,"1 lb"),("egg_whole",50,"1 large"),("gf_oat_flour",50,"1/2 cup"),
      ("parmesan",50,"1/2 cup"),("marinara",500,"2 cups"),("garlic",10,"3 cloves"),
      ("onion",70,"1/2 medium, grated"),("olive_oil",14,"1 tbsp"),("spice_generic",3,"oregano, basil, pepper"),
      ("gf_pasta_dry",180,"~6 oz dry, to serve")],
 steps=["Mix the turkey with egg, oat flour, parmesan, grated onion and seasoning. Grated onion rather than diced keeps them moist.",
        "Roll 15 balls. Handle them lightly; compressed meatballs go dense.",
        "Brown in oil 5 minutes, then simmer in the marinara 20 minutes covered.",
        "Serve over GF pasta."],
 storage="4 days, 3 months frozen in sauce.",
 prep_notes="Freeze in portions. Reheats better than almost anything else here.",
 subs=["Lentil and mushroom meatballs for the vegetarian version.","Chicken instead of turkey."],
 variations=["Sub in a meatball sandwich on GF bread with mozzarella."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","FREEZER FRIENDLY","LEUCINE PRIORITY"]),

dict(id="M-20", cat="SDA Meat/Fish", name="Chicken Shawarma Bowl",
 servings=2, prep=15, cook=20,
 ing=[("chicken_thigh",400,"~14 oz, boneless"),("rice_white_cooked",400,"2 cups"),("cucumber",150,"1/2 cucumber"),
      ("tomato",150,"1.5 medium"),("greek_yogurt_nonfat",150,"2/3 cup"),("tahini",25,"1.5 tbsp"),
      ("lemon_juice",30,"2 tbsp"),("olive_oil",20,"1.5 tbsp"),("garlic",10,"3 cloves"),
      ("spice_generic",6,"cumin, coriander, paprika, turmeric, cinnamon, cayenne")],
 steps=["Marinate the thighs in half the oil, half the lemon, the garlic and all the spices for at least 30 minutes, ideally overnight.",
        "Roast at 425F for 20 minutes, then broil 3 minutes to char the edges. The char is the entire point of shawarma.",
        "Rest 5 minutes, then slice thin.",
        "Whisk yogurt, tahini and remaining lemon into a sauce. Build over rice with cucumber and tomato."],
 storage="4 days.", prep_notes="Thighs rather than breast here. Higher fat, and they do not dry out under a broiler.",
 subs=["Chicken breast, roast 15 minutes instead of 20.","Cauliflower and chickpeas for a vegetarian version."],
 variations=["Add pickled turnip, red onion and hot sauce."],
 manual_tags=["SDA-COMPATIBLE","MEAL PREP","LEUCINE PRIORITY","HIGH SATIETY"]),
]
