# -*- coding: utf-8 -*-
"""The sync endpoint, written out to api/sync.php by build.py.

One JSON file on the server holds the shared state. Every device pulls it on
open and pushes a debounced copy on change, so a plan added on a phone shows up
on the laptop and neither one is authoritative.

The token is a hash of the key the gate already derives from the passcode, so
nothing new has to be remembered and the endpoint is exactly as private as the
app is. That does mean anyone who knows the code and the URL can read the file,
which is the same boundary as the app itself, not a weaker one.
"""

SYNC_PHP = r"""<?php
/* Generated by src/build.py. Edit src/sync_php.py, not this file. */
declare(strict_types=1);

/* sha256 of the mac key the browser derives from the passcode. */
const TOKEN = '__TOKEN__';

/* Kept out of the web root where the host allows it, so the file is not
   fetchable even if a rule is dropped. Falls back to a denied directory. */
function store_dir(): string {
    $outside = dirname(__DIR__, 2) . '/handbook-data';
    if (is_dir($outside) || @mkdir($outside, 0770, true)) {
        if (is_writable($outside)) return $outside;
    }
    $inside = __DIR__ . '/data';
    if (!is_dir($inside)) @mkdir($inside, 0770, true);
    $guard = $inside . '/.htaccess';
    if (!file_exists($guard)) {
        @file_put_contents($guard, "Require all denied\nDeny from all\n");
    }
    return $inside;
}

function send(int $code, array $body): void {
    http_response_code($code);
    header('Content-Type: application/json');
    header('Cache-Control: no-store, no-cache, must-revalidate');
    header('X-Robots-Tag: noindex, nofollow');
    echo json_encode($body, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
if ($method === 'OPTIONS') send(204, []);

/* Same origin only. No CORS headers anywhere in this file, on purpose.
   The query fallback exists because sendBeacon on page hide cannot set
   headers; nothing else should use it. */
$given = $_SERVER['HTTP_X_HANDBOOK_TOKEN'] ?? ($_GET['t'] ?? '');
if (!is_string($given) || !hash_equals(TOKEN, $given)) {
    send(401, ['error' => 'unauthorised']);
}

$path = store_dir() . '/state.json';

/* One lock for the whole read-modify-write, so two phones saving at the same
   moment cannot interleave and produce half a document. */
$fh = @fopen($path, 'c+');
if ($fh === false) send(500, ['error' => 'cannot open the store']);
if (!flock($fh, LOCK_EX)) { fclose($fh); send(500, ['error' => 'cannot lock the store']); }

$raw = stream_get_contents($fh);
$saved = ($raw === '' || $raw === false) ? null : json_decode($raw, true);
if (!is_array($saved)) $saved = ['version' => 0, 'updatedAt' => null, 'state' => null];

if ($method === 'GET') {
    flock($fh, LOCK_UN); fclose($fh);
    send(200, $saved);
}

if ($method !== 'POST') {
    flock($fh, LOCK_UN); fclose($fh);
    send(405, ['error' => 'method not allowed']);
}

$body = json_decode(file_get_contents('php://input') ?: '', true);
if (!is_array($body) || !array_key_exists('state', $body)) {
    flock($fh, LOCK_UN); fclose($fh);
    send(400, ['error' => 'expected {baseVersion, state}']);
}

$base = isset($body['baseVersion']) ? (int)$body['baseVersion'] : 0;
$current = (int)($saved['version'] ?? 0);

/* Somebody else wrote since this device last pulled. Hand back what is on the
   server and let the client merge; never silently overwrite. */
if ($base !== $current) {
    flock($fh, LOCK_UN); fclose($fh);
    send(409, ['error' => 'version conflict', 'version' => $current,
               'updatedAt' => $saved['updatedAt'] ?? null, 'state' => $saved['state'] ?? null]);
}

$next = ['version' => $current + 1,
         'updatedAt' => gmdate('c'),
         'state' => $body['state']];

$encoded = json_encode($next, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
if ($encoded === false) {
    flock($fh, LOCK_UN); fclose($fh);
    send(400, ['error' => 'state did not encode']);
}

/* Keep one previous copy. Cheap insurance against a bad write. */
if ($raw !== '' && $raw !== false) @file_put_contents($path . '.bak', $raw);

ftruncate($fh, 0);
rewind($fh);
fwrite($fh, $encoded);
fflush($fh);
flock($fh, LOCK_UN);
fclose($fh);

send(200, ['ok' => true, 'version' => $next['version'], 'updatedAt' => $next['updatedAt']]);
"""
